import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/druid/balance/dps-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Druid',
    spec: 'Balance',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

export const balanceDruidPhase2Bis: BisList = {
  id: 'balance-druid-phase-2-starter',
  className: 'Druid',
  spec: 'Balance',
  phase: 2,
  title: 'Balance Druid Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'nordrassil-headpiece',
      recommendedGemIds: ['insightful-earthstorm-diamond', 'runed-living-ruby'],
      notes: 'Tier 5 Balance set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'sun-kings-talisman',
      notes: 'Shared caster neck (also picked by Elemental Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', instance: 'Tempest Keep', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'nordrassil-wrath-mantle',
      notes: 'Tier 5 Balance set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'brute-cloak-of-the-ogre-magi',
      notes: 'Shared caster cloak (also picked by Elemental Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'High King Maulgar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'nordrassil-chestpiece',
      recommendedGemIds: ['runed-living-ruby', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 Balance set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'mindstorm-wristbands',
      recommendedEnchantId: 'spellpower-wrists',
      notes: 'Shared caster wrists (also picked by Elemental Shaman/Shadow Priest).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'nordrassil-gauntlets',
      notes: 'Tier 5 Balance set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-blasting',
      notes: 'Shared crafted caster-DPS belt (also picked by Elemental Shaman/Shadow Priest).',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'spellstrike-pants',
      notes: 'Crafted Spellfire Tailoring legs.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'boots-of-blasting',
      notes: 'Crafted caster boots.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'ring-of-recurrence',
      notes: 'Karazhan Chess Event drop.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Chess Event', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'band-of-eternity',
      notes: 'Hybrid caster/healer quest ring.',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'icon-of-the-silver-crescent',
      notes: 'Badge of Justice vendor trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'quagmirrans-eye',
      notes: 'Shared caster trinket (also picked by Shadow Priest); proc effect not modeled yet.',
      sourceName: 'Starter sample',
      source: source({ type: 'Heroic Dungeon', instance: 'The Slave Pens', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'the-nexus-key',
      recommendedEnchantId: 'major-spellpower-weapon',
      notes: 'Shared caster weapon (also picked by Elemental Shaman); weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'orb-of-the-soul-eater',
      notes: 'Two-handed staff main-hand leaves this slot generic; shared with Shadow Priest.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Relic',
      rank: 1,
      itemId: 'idol-of-the-raven-goddess',
      notes: 'Balance Druid relic proof-of-concept row.',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
