import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/warlock/destruction/dps-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Warlock',
    spec: 'Destruction',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const destructionWarlockPhase2Bis: BisList = {
  id: 'destruction-warlock-phase-2-starter',
  className: 'Warlock',
  spec: 'Destruction',
  phase: 2,
  title: 'Destruction Warlock Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'voidheart-cover',
      recommendedGemIds: ['chaotic-skyfire-diamond', 'runed-living-ruby'],
      notes: 'Tier 5 Warlock set piece; shared by all three specs.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'sun-kings-talisman',
      notes: 'Shared caster neck (also picked by Mage/Elemental Shaman/Balance Druid).',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', instance: 'Tempest Keep', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'voidheart-mantle',
      recommendedEnchantId: 'inscription-of-discipline',
      notes: 'Tier 5 Warlock set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'High King Maulgar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'royal-cloak-of-the-sunstriders',
      notes: 'Shared caster cloak (also picked by Mage/Shadow Priest).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'voidheart-robe',
      recommendedGemIds: ['runed-living-ruby', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 Warlock set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'mindstorm-wristbands',
      recommendedEnchantId: 'spellpower-wrists',
      notes: 'Shared caster wrists.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'voidheart-gloves',
      notes: 'Tier 5 Warlock set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'The Curator', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-blasting',
      notes: 'Shared crafted caster-DPS belt.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'voidheart-leggings',
      notes: 'Tier 5 Warlock set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Fathom-Lord Karathress', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'boots-of-blasting',
      notes: 'Shared crafted caster-DPS boots.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'violet-signet-of-the-archmage',
      notes: 'The Violet Eye reputation ring.',
      sourceName: 'Starter sample',
      source: source({ type: 'Reputation', reputation: 'The Violet Eye', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'ring-of-endless-coils',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'quagmirrans-eye',
      notes: 'On-cast haste proc is not modeled yet.',
      sourceName: 'Starter sample',
      source: source({ type: 'Heroic Dungeon', instance: 'The Slave Pens', boss: 'Quagmirran', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'icon-of-the-silver-crescent',
      notes: 'Badge of Justice vendor trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'fang-of-the-leviathan',
      recommendedEnchantId: 'major-spellpower-weapon',
      notes: 'Shared caster dagger (also picked by Fire/Frost Mage); weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'fathomstone',
      notes: 'Caster off-hand frill, not a weapon.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Hydross the Unstable', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'wand-of-the-forgotten-star',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'High Astromancer Solarian', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
