import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/priest/healer-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Priest',
    spec: 'Discipline',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const sharedNote = 'Discipline shares the Holy Priest healing gear catalog in TBC Phase 2 rather than having a distinct itemization; priority differs (mana/utility vs. raw throughput) but the item picks are the same.'
const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const disciplinePriestPhase2Bis: BisList = {
  id: 'discipline-priest-phase-2-starter',
  className: 'Priest',
  spec: 'Discipline',
  phase: 2,
  title: 'Discipline Priest Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'cowl-of-the-avatar',
      recommendedEnchantId: 'glyph-of-renewal',
      recommendedGemIds: ['insightful-earthstorm-diamond', 'royal-nightseye'],
      notes: `Tier 5 Holy/Discipline set piece. ${sharedNote}`,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'lord-sanguinars-claim',
      notes: 'Shared healer neck.',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', instance: 'Tempest Keep', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'mantle-of-the-avatar',
      recommendedEnchantId: 'inscription-of-faith',
      notes: 'Tier 5 Holy/Discipline set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'sunshower-light-cloak',
      notes: 'Shared healer cloak.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'vestments-of-the-avatar',
      recommendedGemIds: ['royal-nightseye', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 Holy/Discipline set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'wraps-of-purification',
      recommendedEnchantId: 'superior-healing-wrists',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Hydross the Unstable', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'gloves-of-the-avatar',
      recommendedEnchantId: 'healing-hands',
      notes: 'Tier 5 Holy/Discipline set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-the-long-road',
      notes: 'Crafted Tailoring belt.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'breeches-of-the-avatar',
      notes: 'Tier 5 Holy/Discipline set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Fathom-Lord Karathress', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'soul-strider-boots',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Fathom-Lord Karathress', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'coral-band-of-the-revived',
      notes: 'Shared healer ring.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'violet-signet-of-the-grand-restorer',
      notes: 'The Violet Eye reputation ring.',
      sourceName: 'Starter sample',
      source: source({ type: 'Reputation', reputation: 'The Violet Eye', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'essence-of-the-martyr',
      notes: 'Badge of Justice vendor trinket (41 badges); shared healer pick.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'earring-of-soulful-meditation',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'The Lurker Below', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'lightfathom-scepter',
      recommendedEnchantId: 'major-healing-weapon',
      notes: 'Shared healer weapon; weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'windcallers-orb',
      notes: 'Cenarion Expedition reputation off-hand.',
      sourceName: 'Starter sample',
      source: source({ type: 'Reputation', reputation: 'Cenarion Expedition', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'luminescent-rod-of-the-naaru',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Morogrim Tidewalker', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
