import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/shaman/elemental/dps-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Shaman',
    spec: 'Elemental',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/WoWSims data before treating as final.'

export const elementalShamanPhase2Bis: BisList = {
  id: 'elemental-shaman-phase-2-starter',
  className: 'Shaman',
  spec: 'Elemental',
  phase: 2,
  title: 'Elemental Shaman Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/Warcraft Tavern/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'cataclysm-helm',
      wowItemId: 30190,
      recommendedGemIds: ['chaotic-skyfire-diamond', 'runed-living-ruby'],
      notes: 'Tier 5 package row; shared hybrid itemization across all three Shaman specs.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep / Serpentshrine Cavern', phase: 2, notes: 'Tier token source varies by token; source needs final audit.', needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'sun-kings-talisman',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', instance: 'Tempest Keep', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'cyclone-shoulderguards',
      recommendedEnchantId: 'inscription-of-discipline',
      notes: 'Tier 4 Elemental set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'High King Maulgar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'brute-cloak-of-the-ogre-magi',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'High King Maulgar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'cataclysm-chestplate',
      wowItemId: 30185,
      recommendedGemIds: ['runed-living-ruby', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 package row; shared hybrid itemization across all three Shaman specs.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'mindstorm-wristbands',
      recommendedEnchantId: 'spellpower-wrists',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'soul-eaters-handwraps',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Magtheridon's Lair", boss: 'Magtheridon', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-blasting',
      notes: 'Shared crafted caster-DPS belt across every caster spec.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'cataclysm-legplates',
      wowItemId: 30192,
      recommendedGemIds: ['runed-living-ruby', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 package row; shared hybrid itemization across all three Shaman specs.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Fathom-Lord Karathress', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'velvet-boots-of-the-guardian',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'The Lurker Below', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'ring-of-unrelenting-storms',
      notes: 'Trash drop; verify against current guides.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'ring-of-endless-coils',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'the-lightning-capacitor',
      notes: 'Proc effect (Chain Lightning bolt on stacked spell crits) is not modeled yet.',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', instance: 'Karazhan', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'icon-of-the-silver-crescent',
      notes: 'Badge of Justice vendor trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'the-nexus-key',
      recommendedEnchantId: 'major-spellpower-weapon',
      notes: 'Weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'orb-of-prototype-power',
      notes: 'Two-handed staff main-hand leaves the off-hand slot generic; a dedicated Phase 2 off-hand item is future work.',
      sourceName: 'Existing generic caster off-hand sample',
      source: source({ type: 'Other', phase: 1, notes: 'Placeholder pending a dedicated Phase 2 Elemental off-hand pick.', needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'no-ranged-enhancement-shaman',
      notes: 'Elemental Shaman should use Totems in the Relic slot; bows, guns, and crossbows are not relevant recommendations.',
      sourceName: 'Class restriction placeholder',
      source: source({ type: 'Other', phase: 2, notes: 'Intentional no-item placeholder for Shaman ranged compatibility.' }),
    }),
    entry({
      slot: 'Relic',
      rank: 1,
      itemId: 'totem-of-the-void',
      notes: 'Elemental Totem proof-of-concept row.',
      sourceName: 'Starter sample',
      source: source({ type: 'Dungeon', instance: 'The Mechanar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
