import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/shaman/enhancement/dps-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Shaman',
    spec: 'Enhancement',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/source against current Wowhead/Icy Veins/WoWSims data before treating as final.'

export const enhancementShamanPhase2Bis: BisList = {
  id: 'enhancement-shaman-phase-2-starter',
  className: 'Shaman',
  spec: 'Enhancement',
  phase: 2,
  title: 'Enhancement Shaman Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/WoWSims workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'cataclysm-helm',
      wowItemId: 30190,
      recommendedGemIds: ['relentless-earthstorm-diamond', 'delicate-living-ruby'],
      notes: 'Tier package starter row; set bonuses should outrank naive raw-stat sorting.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep / Serpentshrine Cavern', phase: 2, notes: 'Tier token source varies by token; source needs final audit.', needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'telonicus-pendant-of-mayhem',
      wowItemId: 30017,
      notes: 'Physical DPS neck sample for Phase 2 planning.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'The Eye', boss: 'High Astromancer Solarian', phase: 2 }),
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'shoulderpads-of-the-stranger',
      wowItemId: 30055,
      notes: 'Offset shoulder sample used with Cataclysm set-package assumptions.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Hydross the Unstable', phase: 2 }),
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'drape-of-the-dark-reavers',
      wowItemId: 28672,
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Shade of Aran', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'cataclysm-chestplate',
      wowItemId: 30185,
      recommendedGemIds: ['delicate-living-ruby', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 package sample.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep / Serpentshrine Cavern', phase: 2, notes: 'Tier token source needs final audit.', needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'true-aim-stalker-bands',
      wowItemId: 30091,
      notes: 'Known Enhancement Shaman Phase 2 proof case.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2 }),
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'cataclysm-gauntlets',
      wowItemId: 30189,
      notes: 'Tier 5 set package sample.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep / Serpentshrine Cavern', phase: 2, notes: 'Tier token source needs final audit.', needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-one-hundred-deaths',
      wowItemId: 30106,
      notes: 'Physical DPS belt sample.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2 }),
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'cataclysm-legplates',
      wowItemId: 30192,
      notes: 'Tier 5 package sample.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', phase: 2, notes: 'Tier token source needs final audit.', needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'boots-of-utter-darkness',
      wowItemId: 30039,
      notes: 'Leatherworking profession option sample; profession gating comes later.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Crafted', craftedBy: 'Leatherworking', phase: 2 }),
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'ring-of-a-thousand-marks',
      wowItemId: 28757,
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Prince Malchezaar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'garonas-signet-ring',
      wowItemId: 28649,
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'dragonspine-trophy',
      wowItemId: 28830,
      notes: 'Known high-value physical DPS trinket sample.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'Gruul the Dragonkiller', phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 2,
      itemId: 'tsunami-talisman',
      wowItemId: 30627,
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 2',
      rank: 3,
      itemId: 'bloodlust-brooch',
      wowItemId: 29383,
      notes: 'Badge trinket fallback sample; compatible with either displayed trinket slot.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'talon-of-the-phoenix',
      wowItemId: 32944,
      recommendedEnchantId: 'mongoose-main-hand',
      notes: 'Enhancement-appropriate weapon sample; weapon speed/DPS modeling is future work.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'The Eye', boss: "Kael'thas Sunstrider", phase: 2 }),
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'rod-of-the-sun-king',
      wowItemId: 29996,
      recommendedEnchantId: 'mongoose-main-hand',
      notes: 'Off-hand weapon sample for Enhancement dual-wield planning.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Raid', instance: 'The Eye', boss: "Kael'thas Sunstrider", phase: 2 }),
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'no-ranged-enhancement-shaman',
      notes: 'Enhancement Shaman should use Totems in the Relic slot; bows, guns, and crossbows are not relevant recommendations.',
      sourceName: 'Class restriction placeholder',
      source: source({ type: 'Other', phase: 2, notes: 'Intentional no-item placeholder for Enhancement Shaman ranged compatibility.' }),
    }),
    entry({
      slot: 'Relic',
      rank: 1,
      itemId: 'totem-of-the-astral-winds',
      wowItemId: 27815,
      notes: 'Enhancement Totem proof-of-concept row.',
      sourceName: 'Wowhead-style guide sample',
      source: source({ type: 'Dungeon', instance: 'The Mechanar', phase: 1, notes: 'Boss/source needs final audit.', needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
