import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/warrior/fury/dps-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Warrior',
    spec: 'Fury',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const furyWarriorPhase2Bis: BisList = {
  id: 'fury-warrior-phase-2-starter',
  className: 'Warrior',
  spec: 'Fury',
  phase: 2,
  title: 'Fury Warrior Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'destroyer-battle-helm',
      recommendedGemIds: ['relentless-earthstorm-diamond', 'bold-living-ruby'],
      notes: 'Tier 5 DPS set piece shared with Arms.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'telonicus-pendant-of-mayhem',
      wowItemId: 30017,
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'The Eye', boss: 'High Astromancer Solarian', phase: 2 }),
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'destroyer-shoulderblades',
      notes: 'Tier 5 Fury set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'vengeance-wrap',
      wowItemId: 24259,
      notes: 'Shared Arms/Fury crafted cloak.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 1 }),
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'destroyer-breastplate',
      recommendedGemIds: ['bold-living-ruby', 'gleaming-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 DPS set piece shared with Arms.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'bracers-of-eradication',
      recommendedEnchantId: 'assault-wrists',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'The Lurker Below', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'destroyer-gauntlets',
      notes: 'Tier 5 DPS set piece shared with Arms.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-one-hundred-deaths',
      wowItemId: 30106,
      notes: 'Shared Arms/Fury/Protection belt.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2 }),
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'leggings-of-murderous-intent',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'warboots-of-obliteration',
      notes: 'Shared Arms/Fury boots.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Morogrim Tidewalker', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'band-of-the-ranger-general',
      notes: 'Shared Arms/Fury ring.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'ring-of-a-thousand-marks',
      wowItemId: 28757,
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Prince Malchezaar', phase: 1 }),
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'dragonspine-trophy',
      wowItemId: 28830,
      notes: 'Shared Arms/Fury trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'Gruul the Dragonkiller', phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'tsunami-talisman',
      wowItemId: 30627,
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'dragonstrike',
      wowItemId: 28439,
      recommendedEnchantId: 'mongoose-main-hand',
      notes: 'Dual-wield main-hand; crafted Blacksmithing weapon.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Blacksmithing', phase: 1 }),
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'talon-of-azshara',
      recommendedEnchantId: 'mongoose-main-hand',
      notes: 'Dual-wield off-hand.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Morogrim Tidewalker', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'serpent-spine-longbow',
      notes: 'Shared Arms/Fury ranged weapon.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
