import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/paladin/holy/healer-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Paladin',
    spec: 'Holy',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const holyPaladinPhase2Bis: BisList = {
  id: 'holy-paladin-phase-2-starter',
  className: 'Paladin',
  spec: 'Holy',
  phase: 2,
  title: 'Holy Paladin Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'crystalforge-greathelm',
      recommendedEnchantId: 'glyph-of-renewal',
      recommendedGemIds: ['insightful-earthstorm-diamond', 'royal-nightseye'],
      notes: 'Tier 5 Holy set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'lord-sanguinars-claim',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', instance: 'Tempest Keep', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'crystalforge-pauldrons',
      recommendedEnchantId: 'inscription-of-faith',
      notes: 'Tier 5 Holy set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'sunshower-light-cloak',
      notes: 'Shared healer cloak (also picked by Restoration Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'crystalforge-chestpiece',
      recommendedGemIds: ['royal-nightseye', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 Holy set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'blackfathom-warbands',
      recommendedEnchantId: 'superior-healing-wrists',
      notes: 'Shared healer wrists (also picked by Restoration Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Hydross the Unstable', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'glorious-gauntlets-of-crestfall',
      recommendedEnchantId: 'healing-hands',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'girdle-of-fallen-stars',
      notes: 'Trash drop.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'sunhawk-leggings',
      notes: 'Shared healer legs (also picked by Restoration Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'boots-of-courage-unending',
      notes: 'Trash drop.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'coral-band-of-the-revived',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'phoenix-ring-of-rebirth',
      notes: 'Shared healer ring (also picked by Restoration Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'essence-of-the-martyr',
      notes: 'Badge of Justice vendor trinket (41 badges); shared healer pick.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'ribbon-of-sacrifice',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Opera Event', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'lightfathom-scepter',
      recommendedEnchantId: 'major-healing-weapon',
      notes: 'Shared healer weapon (also picked by Restoration Shaman); weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'aegis-of-the-vindicator',
      recommendedEnchantId: 'intellect-shield',
      notes: 'Shared healer shield (Priest/Paladin/Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Magtheridon's Lair", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Relic',
      rank: 1,
      itemId: 'blessed-book-of-nagrand',
      notes: 'Holy Paladin relic proof-of-concept row; quest reward in Nagrand.',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
