import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/warrior/protection/tank-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Warrior',
    spec: 'Protection',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const protectionWarriorPhase2Bis: BisList = {
  id: 'protection-warrior-phase-2-starter',
  className: 'Warrior',
  spec: 'Protection',
  phase: 2,
  title: 'Protection Warrior Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'destroyer-greathelm',
      recommendedGemIds: ['solid-star-of-elune', 'rigid-dawnstone'],
      notes: 'Tier 5 Protection set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'veterans-pendant-of-triumph',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'PvP', vendor: 'PvP vendor (Honor + Eye of the Storm marks)', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'destroyer-shoulderguards-tank',
      notes: 'Tier 5 Protection set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'phoenix-wing-cloak',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'destroyer-chestguard-tank',
      recommendedGemIds: ['solid-star-of-elune', 'rigid-dawnstone', 'bold-living-ruby'],
      notes: 'Tier 5 Protection set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'veterans-plate-bracers',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'PvP', vendor: 'PvP vendor (Honor + Warsong Gulch marks)', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'gloves-of-the-searing-grip',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-one-hundred-deaths',
      wowItemId: 30106,
      notes: 'Shared Arms/Fury/Protection belt.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2 }),
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'destroyer-legguards-tank',
      notes: 'Tier 5 Protection set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Fathom-Lord Karathress', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'veterans-plate-greaves',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'PvP', vendor: 'PvP vendor (Honor + Eye of the Storm marks)', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'shapeshifters-signet',
      notes: 'Hybrid DPS/Tank reputation ring.',
      sourceName: 'Starter sample',
      source: source({ type: 'Reputation', reputation: 'Lower City', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'ring-of-sundered-souls',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Morogrim Tidewalker', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'icon-of-unyielding-courage',
      notes: 'On-use proc not modeled yet.',
      sourceName: 'Starter sample',
      source: source({ type: 'Heroic Dungeon', instance: 'The Blood Furnace', boss: "Keli'dan the Breaker", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'bloodlust-brooch',
      wowItemId: 29383,
      notes: 'Badge of Justice vendor trinket; DPS-flavored fallback for threat generation.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'mallet-of-the-tides',
      recommendedEnchantId: 'major-agility-weapon',
      notes: 'Weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'The Lurker Below', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'aldori-legacy-defender',
      recommendedEnchantId: 'defense-shield',
      notes: 'Tank shield.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'gyro-balanced-khorium-destroyer',
      notes: 'Crafted Engineering ranged filler.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Engineering', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
