import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/paladin/tank-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Paladin',
    spec: 'Protection',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const protectionPaladinPhase2Bis: BisList = {
  id: 'protection-paladin-phase-2-starter',
  className: 'Paladin',
  spec: 'Protection',
  phase: 2,
  title: 'Protection Paladin Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'crystalforge-faceguard',
      recommendedGemIds: ['powerful-earthstorm-diamond', 'solid-star-of-elune'],
      notes: 'Tier 5 Protection set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'veterans-pendant-of-triumph',
      notes: 'Shared tank neck (also picked by Protection Warrior).',
      sourceName: 'Starter sample',
      source: source({ type: 'PvP', vendor: 'PvP vendor (Honor + Eye of the Storm marks)', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'justicar-shoulderguards',
      recommendedEnchantId: 'inscription-of-warding',
      notes: 'Tier 4 Protection set piece that remains a Phase 2 pick.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'High King Maulgar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'phoenix-wing-cloak',
      notes: 'Shared tank cloak (also picked by Protection Warrior).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'justicar-chestguard',
      notes: 'Tier 4 Protection set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Magtheridon's Lair", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'wristguards-of-determination',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'crystalforge-handguards',
      notes: 'Tier 5 Protection set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-the-guardian',
      notes: 'Crafted Blacksmithing tank belt.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Blacksmithing', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'crystalforge-legguards',
      recommendedEnchantId: 'clefthide-leg-armor',
      notes: 'Tier 5 Protection set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Fathom-Lord Karathress', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'boots-of-the-resilient',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'High Astromancer Solarian', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'the-seal-of-danzalar',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'The Lurker Below', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'ashyens-gift',
      notes: 'Cenarion Expedition reputation ring.',
      sourceName: 'Starter sample',
      source: source({ type: 'Reputation', reputation: 'Cenarion Expedition', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'icon-of-the-silver-crescent',
      notes: 'Spell power trinket valued for Holy Shield/Consecration threat scaling.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'tome-of-fiery-redemption',
      notes: 'On-use proc not modeled yet.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'justicars-warblade',
      notes: "Weapon DPS/speed modeling is future work. No tank weapon enchant is modeled yet, so none is recommended here.",
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'aldori-legacy-defender',
      recommendedEnchantId: 'defense-shield',
      notes: 'Shared tank shield (also picked by Protection Warrior).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Relic',
      rank: 1,
      itemId: 'libram-of-the-eternal-rest',
      notes: 'Protection Paladin relic proof-of-concept row.',
      sourceName: 'Starter sample',
      source: source({ type: 'Dungeon', instance: 'Sethekk Halls', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
