import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/shaman/healer-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Shaman',
    spec: 'Restoration',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const restorationShamanPhase2Bis: BisList = {
  id: 'restoration-shaman-phase-2-starter',
  className: 'Shaman',
  spec: 'Restoration',
  phase: 2,
  title: 'Restoration Shaman Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'cataclysm-helm',
      wowItemId: 30190,
      recommendedEnchantId: 'glyph-of-renewal',
      recommendedGemIds: ['insightful-earthstorm-diamond', 'royal-nightseye'],
      notes: 'Tier 5 package row; shared hybrid itemization across all three Shaman specs.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'lord-sanguinars-claim',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', instance: 'Tempest Keep', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'cataclysm-shoulderplates',
      recommendedEnchantId: 'inscription-of-faith',
      wowItemId: 30194,
      notes: 'Tier 5 package row; shared hybrid itemization across all three Shaman specs.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'sunshower-light-cloak',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'cataclysm-chestplate',
      wowItemId: 30185,
      recommendedGemIds: ['royal-nightseye', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 package row; shared hybrid itemization across all three Shaman specs.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'blackfathom-warbands',
      recommendedEnchantId: 'superior-healing-wrists',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Hydross the Unstable', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'worldstorm-gauntlets',
      recommendedEnchantId: 'healing-hands',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'High Astromancer Solarian', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'primal-mooncloth-belt',
      notes: 'Shared crafted healer belt, not Shaman-specific.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'sunhawk-leggings',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'orca-hide-boots',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'jade-ring-of-the-everliving',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Prince Malchezaar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'phoenix-ring-of-rebirth',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'essence-of-the-martyr',
      notes: 'Badge of Justice vendor trinket (41 badges).',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'scarab-of-the-infinite-cycle',
      notes: 'On-use haste proc is not modeled yet.',
      sourceName: 'Starter sample',
      source: source({ type: 'Heroic Dungeon', instance: 'The Black Morass', boss: 'Aeonus', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'lightfathom-scepter',
      recommendedEnchantId: 'major-healing-weapon',
      notes: 'Weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'aegis-of-the-vindicator',
      recommendedEnchantId: 'intellect-shield',
      notes: 'Shared healer shield (Priest/Paladin/Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Magtheridon's Lair", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'no-ranged-enhancement-shaman',
      notes: 'Restoration Shaman should use Totems in the Relic slot; bows, guns, and crossbows are not relevant recommendations.',
      sourceName: 'Class restriction placeholder',
      source: source({ type: 'Other', phase: 2, notes: 'Intentional no-item placeholder for Shaman ranged compatibility.' }),
    }),
    entry({
      slot: 'Relic',
      rank: 1,
      itemId: 'totem-of-healing-rains',
      notes: 'Restoration Shaman relic proof-of-concept row.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Maiden of Virtue', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
