import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/druid/healer-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Druid',
    spec: 'Restoration',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const restorationDruidPhase2Bis: BisList = {
  id: 'restoration-druid-phase-2-starter',
  className: 'Druid',
  spec: 'Restoration',
  phase: 2,
  title: 'Restoration Druid Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'nordrassil-headguard',
      recommendedGemIds: ['insightful-earthstorm-diamond', 'royal-nightseye'],
      notes: 'Tier 5 Restoration set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'lord-sanguinars-claim',
      notes: 'Shared healer neck.',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', instance: 'Tempest Keep', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'nordrassil-life-mantle',
      recommendedEnchantId: 'inscription-of-faith',
      notes: 'Tier 5 Restoration set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'sunshower-light-cloak',
      notes: 'Shared healer cloak.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'nordrassil-chestguard',
      recommendedGemIds: ['royal-nightseye', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 Restoration set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'grove-bands-of-remulos',
      recommendedEnchantId: 'superior-healing-wrists',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'The Lurker Below', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'mitts-of-the-treemender',
      recommendedEnchantId: 'healing-hands',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Maiden of Virtue', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-the-long-road',
      notes: 'Shared crafted healer belt (also picked by Holy/Discipline Priest).',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'earthsoul-leggings',
      notes: 'Karazhan Opera Event drop.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Opera Event', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'orca-hide-boots',
      notes: 'Shared healer boots (also picked by Restoration Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Leotheras the Blind', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'coral-band-of-the-revived',
      notes: 'Shared healer ring (also picked by Holy Paladin/Priest).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'jade-ring-of-the-everliving',
      notes: 'Shared healer ring (also picked by Restoration Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Prince Malchezaar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'essence-of-the-martyr',
      notes: 'Badge of Justice vendor trinket (41 badges); shared healer pick.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'lower-city-prayerbook',
      notes: 'Lower City reputation trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Reputation', reputation: 'Lower City', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'lightfathom-scepter',
      recommendedEnchantId: 'major-healing-weapon',
      notes: 'Shared healer weapon; weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'tears-of-heaven',
      notes: 'Badge of Justice vendor off-hand.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Relic',
      rank: 1,
      itemId: 'idol-of-the-emerald-queen',
      notes: 'Restoration Druid relic proof-of-concept row.',
      sourceName: 'Starter sample',
      source: source({ type: 'Dungeon', instance: 'Shadow Labyrinth', boss: 'Ambassador Hellmaw', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
