import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/paladin/retribution/dps-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Paladin',
    spec: 'Retribution',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const retributionPaladinPhase2Bis: BisList = {
  id: 'retribution-paladin-phase-2-starter',
  className: 'Paladin',
  spec: 'Retribution',
  phase: 2,
  title: 'Retribution Paladin Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'furious-gizmatic-goggles',
      notes: 'Crafted Engineering headpiece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Engineering', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'pendant-of-the-perilous',
      notes: 'Shared physical DPS neck (also picked by Arms Warrior).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'shoulderpads-of-the-stranger',
      recommendedEnchantId: 'inscription-of-vengeance',
      wowItemId: 30055,
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Hydross the Unstable', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'razor-scale-battlecloak',
      recommendedEnchantId: 'enchant-cloak-greater-agility',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Morogrim Tidewalker', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'crystalforge-breastplate',
      recommendedGemIds: ['bold-living-ruby', 'gleaming-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 Retribution set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'bladespire-warbands',
      recommendedEnchantId: 'assault-wrists',
      notes: 'Shared physical DPS wrists (also picked by Arms Warrior).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'High King Maulgar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'gloves-of-the-searing-grip',
      notes: 'Shared physical DPS/tank hands (also picked by Protection Warrior).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-one-hundred-deaths',
      wowItemId: 30106,
      notes: 'Shared physical DPS belt.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2 }),
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'shattrath-leggings',
      recommendedEnchantId: 'nethercobra-leg-armor',
      notes: 'Quest reward legs in Shattrath City.',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'warboots-of-obliteration',
      notes: 'Shared physical DPS boots (also picked by Arms/Fury Warrior).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Morogrim Tidewalker', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'shapeshifters-signet',
      notes: 'Hybrid DPS/Tank reputation ring (also picked by Arms/Protection Warrior).',
      sourceName: 'Starter sample',
      source: source({ type: 'Reputation', reputation: 'Lower City', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'ancestral-ring-of-conquest',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'The Lurker Below', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'dragonspine-trophy',
      wowItemId: 28830,
      notes: 'Shared physical DPS trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'Gruul the Dragonkiller', phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'bloodlust-brooch',
      wowItemId: 29383,
      notes: 'Badge of Justice vendor trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'lionheart-executioner',
      notes: 'Crafted two-handed Blacksmithing weapon; weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Blacksmithing', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'claw-of-the-phoenix',
      notes: 'Two-handed main-hand leaves this slot generic pending 2H-exclusivity modeling; not a real Retribution recommendation.',
      sourceName: 'Existing generic filler',
      source: source({ type: 'Other', phase: 2, notes: 'Placeholder pending 2H weapon exclusivity support.', needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Relic',
      rank: 1,
      itemId: 'libram-of-avengement',
      notes: 'Retribution Paladin relic.',
      sourceName: 'Starter sample',
      source: source({ type: 'Dungeon', instance: 'The Blood Furnace', boss: 'The Maker', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
