import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/priest/shadow/dps-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Priest',
    spec: 'Shadow',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const shadowPriestPhase2Bis: BisList = {
  id: 'shadow-priest-phase-2-starter',
  className: 'Priest',
  spec: 'Shadow',
  phase: 2,
  title: 'Shadow Priest Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'cowl-of-the-grand-engineer',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'ritssyns-lost-pendant',
      notes: 'Trash drop.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'frozen-shadoweave-shoulders',
      recommendedEnchantId: 'inscription-of-discipline',
      notes: 'Crafted Shadoweave Tailoring shoulders.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'royal-cloak-of-the-sunstriders',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'vestments-of-the-sea-witch',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'mindstorm-wristbands',
      recommendedEnchantId: 'spellpower-wrists',
      notes: 'Shared caster wrists (also picked by Elemental Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'soul-eaters-handwraps',
      notes: 'Shared caster hands (also picked by Elemental Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Magtheridon's Lair", boss: 'Magtheridon', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-blasting',
      notes: 'Shared crafted caster-DPS belt (also picked by Elemental Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'trousers-of-the-astromancer',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'High Astromancer Solarian', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'frozen-shadoweave-boots',
      notes: 'Crafted Shadoweave Tailoring boots.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Tailoring', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'ring-of-endless-coils',
      notes: 'Shared caster ring (also picked by Elemental Shaman).',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'band-of-alar',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Al'ar", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'icon-of-the-silver-crescent',
      notes: 'Badge of Justice vendor trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'quagmirrans-eye',
      notes: 'Proc effect (stacking spell haste) is not modeled yet.',
      sourceName: 'Starter sample',
      source: source({ type: 'Heroic Dungeon', instance: 'The Slave Pens', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'nathrezim-mindblade',
      recommendedEnchantId: 'major-spellpower-weapon',
      notes: 'Weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Prince Malchezaar', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'orb-of-the-soul-eater',
      notes: 'Badge of Justice vendor off-hand (25 badges).',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'wand-of-the-forgotten-star',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'High Astromancer Solarian', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
