import type { RankedGearEntry, RankedGearSource, BisList } from './bisTypes'

const guideUrl = 'https://www.wowhead.com/tbc/guide/classes/hunter/survival/dps-bis-gear-pve-phase-2'

function source(source: RankedGearSource): RankedGearSource {
  return source
}

function entry(values: Omit<RankedGearEntry, 'className' | 'spec' | 'phase' | 'sourceUrl'>): RankedGearEntry {
  return {
    className: 'Hunter',
    spec: 'Survival',
    phase: 2,
    sourceUrl: guideUrl,
    ...values,
  }
}

const verifyNote = 'Starter row; verify exact final ranking/stats against current Wowhead/Icy Veins/wowtbc.gg data before treating as final.'

export const survivalHunterPhase2Bis: BisList = {
  id: 'survival-hunter-phase-2-starter',
  className: 'Hunter',
  spec: 'Survival',
  phase: 2,
  title: 'Survival Hunter Phase 2 Starter Ranked List',
  sourceName: 'Starter guide-structured sample inspired by Wowhead/wowtbc.gg workflows',
  sourceUrl: guideUrl,
  entries: [
    entry({
      slot: 'Head',
      rank: 1,
      itemId: 'rift-stalker-helm',
      recommendedGemIds: ['relentless-earthstorm-diamond', 'delicate-living-ruby'],
      notes: 'Tier 5 Hunter set piece; shared with Beast Mastery/Marksmanship.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Neck',
      rank: 1,
      itemId: 'telonicus-pendant-of-mayhem',
      wowItemId: 30017,
      notes: 'Shared physical DPS neck.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'The Eye', boss: 'High Astromancer Solarian', phase: 2 }),
    }),
    entry({
      slot: 'Shoulders',
      rank: 1,
      itemId: 'rift-stalker-mantle',
      notes: 'Tier 5 Hunter set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'Void Reaver', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Back',
      rank: 1,
      itemId: 'thalassian-wildercloak',
      notes: 'Shared physical DPS cloak.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Chest',
      rank: 1,
      itemId: 'rift-stalker-hauberk',
      recommendedGemIds: ['delicate-living-ruby', 'rigid-dawnstone', 'solid-star-of-elune'],
      notes: 'Tier 5 Hunter set piece.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Wrists',
      rank: 1,
      itemId: 'vambraces-of-ending',
      wowItemId: 28514,
      notes: 'Shared physical DPS wrists.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: 'High Astromancer Solarian', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Hands',
      rank: 1,
      itemId: 'gloves-of-dexterous-manipulation',
      notes: 'Survival-preferred hands (expertise); differs from the Beast Mastery/Marksmanship tier pick.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Karazhan', boss: 'Attumen the Huntsman', phase: 1, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Waist',
      rank: 1,
      itemId: 'belt-of-deep-shadow',
      wowItemId: 30040,
      notes: 'Shared crafted Leatherworking belt.',
      sourceName: 'Starter sample',
      source: source({ type: 'Crafted', craftedBy: 'Leatherworking', phase: 2 }),
    }),
    entry({
      slot: 'Legs',
      rank: 1,
      itemId: 'rift-stalker-leggings',
      notes: 'Tier 5 Hunter set piece (Survival-preferred); differs from the Beast Mastery/Marksmanship pick.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Fathom-Lord Karathress', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Feet',
      rank: 1,
      itemId: 'cobra-lash-boots',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Serpentshrine Cavern', boss: 'Lady Vashj', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 1',
      rank: 1,
      itemId: 'band-of-eternity',
      notes: 'Hybrid caster/healer quest ring reused for its stamina/agility-adjacent stat budget; also a Balance Druid pick.',
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Finger 2',
      rank: 1,
      itemId: 'ring-of-the-recalcitrant',
      notes: verifyNote,
      sourceName: 'Starter sample',
      source: source({ type: 'Quest', phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Trinket 1',
      rank: 1,
      itemId: 'dragonspine-trophy',
      wowItemId: 28830,
      notes: 'Shared physical DPS trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: "Gruul's Lair", boss: 'Gruul the Dragonkiller', phase: 1 }),
    }),
    entry({
      slot: 'Trinket 2',
      rank: 1,
      itemId: 'bloodlust-brooch',
      wowItemId: 29383,
      notes: 'Badge of Justice vendor trinket.',
      sourceName: 'Starter sample',
      source: source({ type: 'Vendor', vendor: "G'eras", phase: 1 }),
    }),
    entry({
      slot: 'Main Hand',
      rank: 1,
      itemId: 'twinblade-of-the-phoenix',
      notes: 'Melee stat-stick weapon (used for weaving, not primary damage); shared with Arms Warrior. Weapon DPS/speed modeling is future work.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Off Hand',
      rank: 1,
      itemId: 'claw-of-the-phoenix',
      notes: 'Two-handed main-hand leaves this slot generic pending 2H-exclusivity modeling; not a real Hunter recommendation.',
      sourceName: 'Existing generic filler',
      source: source({ type: 'Other', phase: 2, notes: 'Placeholder pending 2H weapon exclusivity support.', needsVerification: true }),
      needsVerification: true,
    }),
    entry({
      slot: 'Ranged',
      rank: 1,
      itemId: 'sunfury-bow-of-the-phoenix',
      notes: 'The primary damage weapon for every Hunter spec.',
      sourceName: 'Starter sample',
      source: source({ type: 'Raid', instance: 'Tempest Keep', boss: "Kael'thas Sunstrider", phase: 2, needsVerification: true }),
      needsVerification: true,
    }),
  ],
}
