import rawIcons from './raidcompIcons.json' with { type: 'json' }
import type { TbcClass, TbcSpec } from '../character/characterTypes'

/**
 * Icon names for the raid planner, generated by `tools/ingest/ingest-raidcomp-icons.mjs`.
 *
 * Names only. Resolving one to a path is a UI concern and stays out of `domain/`, the same split
 * `domain/icons` already keeps for items and gems — see `ItemIcon` for the rendering side.
 *
 * **A spec has no icon of its own in TBC.** The convention is the tree's deepest talent — Mangle for
 * Feral, Shadowstep for Subtlety, Avenger's Shield for Protection Paladin — so these are derived from
 * talent data already in the repo rather than fetched. The talent each one came from is recorded in
 * the JSON, so the choice is auditable rather than magic.
 */
type SpellIcon = { name: string; spellId: number; icon: string; spellName?: string }
type SpecIcon = { className: string; spec: string; icon: string; fromTalent: string }

const spellIcons = rawIcons.spellIcons as Record<string, SpellIcon>
const specIcons = rawIcons.specIcons as Record<string, SpecIcon>

/** Icon for a buff or debuff, by its catalogue id. */
export function getBuffIcon(id: string): string | undefined {
  return spellIcons[id]?.icon
}

export function getSpecIcon(className: TbcClass, spec: TbcSpec): string | undefined {
  return specIcons[`${className}|${spec}`]?.icon
}

/** The talent a spec's icon was taken from — surfaced in a tooltip so the choice is explainable. */
export function getSpecIconSource(className: TbcClass, spec: TbcSpec): string | undefined {
  return specIcons[`${className}|${spec}`]?.fromTalent
}

export const buffIconCount = Object.keys(spellIcons).length
export const specIconCount = Object.keys(specIcons).length
