import rawCosts from './acquisitionCosts.json' with { type: 'json' }

/**
 * What a crafted or bought BiS pick costs, generated by `tools/ingest/ingest-acquisition-cost.mts`.
 *
 * **"Where" was only half a plan.** `resolveAcquisition` will tell you a robe is Tailoring and a
 * trinket is bought from G'eras, and both then read as "go and get it" — the robe wants 14 Primal
 * Fire, and the trinket wants 41 Badges of Justice, which is a fortnight of heroics. Those two
 * facts belong on the same row as the recommendation, not in a browser tab beside it.
 *
 * Read from Wowhead's own item pages: reagents come from the `created-by-spell` listview, prices from
 * `sold-by`. Nothing is estimated, so there is no `needsVerification` here — an item this has no
 * entry for is simply absent, which the surface reports as "no cost recorded" rather than as free.
 */

/** One line of a price: 41 Badges of Justice, 1030 Arena Points, 14 Primal Fire. */
export type CostLine = {
  name: string
  quantity: number
  /** Present when the price is paid in an item rather than an abstract currency. */
  wowItemId?: number
}

export type AcquisitionCost = {
  wowItemId: number
  name: string
  type: 'Crafted' | 'Vendor'
  /** Crafted only. */
  profession?: string
  requiredSkill?: number
  reagents?: CostLine[]
  /** Vendor only. */
  vendor?: string
  price?: CostLine[]
  /** The Wowhead page each figure came off, so a doubtful number can be checked rather than argued. */
  source: string
}

const costs = rawCosts.costs as AcquisitionCost[]

const byItemId = new Map<number, AcquisitionCost>(costs.map((cost) => [cost.wowItemId, cost]))

/** Undefined for anything not crafted or bought, and for the handful whose page carried no price. */
export function getAcquisitionCost(wowItemId: number | undefined): AcquisitionCost | undefined {
  return wowItemId === undefined ? undefined : byItemId.get(wowItemId)
}

/**
 * The price as one readable line: "41x Badge of Justice", "14x Primal Fire · 16x Netherweb Spider Silk".
 *
 * Joined with a middot rather than a comma because reagent names contain commas often enough that a
 * comma-joined list reads as one long name.
 */
export function describeCost(cost: AcquisitionCost | undefined): string | undefined {
  const lines = cost?.type === 'Crafted' ? cost.reagents : cost?.price
  if (!lines?.length) return undefined
  return lines
    // "63 gold", not "63x gold" — a quantity of a currency reads as an amount, not a count of things.
    .map((line) => (line.name === 'gold' ? `${line.quantity} gold` : `${line.quantity}x ${line.name}`))
    .join(' · ')
}

/** Counts, exported so the test suite asserts the dataset's reach rather than trusting it. */
export const acquisitionCostCounts = {
  total: costs.length,
  crafted: costs.filter((cost) => cost.type === 'Crafted').length,
  vendor: costs.filter((cost) => cost.type === 'Vendor').length,
}
