import type { GearSlot } from './gearSlots'
import type { GearItem } from './itemTypes'
import { isItemCompatibleWithGearSlot } from './slotCompatibility'

export const sampleItems: readonly GearItem[] = [
  {
    id: 'prototype-adventurer-helm',
    name: 'Prototype Adventurer Helm',
    slot: 'Head',
    quality: 'Rare',
    source: 'Other',
    phase: 1,
    stats: { stamina: 18, critRating: 8 },
    sockets: ['Meta', 'Red'],
    socketBonus: { hitRating: 4 },
    notes: 'Original local starter item retained as a generic fallback.',
  },
  {
    id: 'cataclysm-helm',
    wowItemId: 30190,
    name: 'Cataclysm Headguard',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    stats: { agility: 33, stamina: 39, intellect: 25, attackPower: 66, critRating: 24, hitRating: 12 },
    sockets: ['Meta', 'Red'],
    socketBonus: { hitRating: 4 },
    zone: 'Tempest Keep',
    instance: 'The Eye',
    notes: 'Enhancement Phase 2 tier-piece proof case; set-bonus context should beat naive raw-stat sorting.',
  },
  {
    id: 'cowl-of-defiance',
    wowItemId: 28732,
    name: 'Cowl of Defiance',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 125,
    stats: { agility: 34, stamina: 33, attackPower: 60, critRating: 24, hitRating: 16 },
    instance: 'Karazhan',
    notes: 'Strong raw-stat comparison item for Enhancement Shaman tier-vs-offset testing.',
  },
  {
    id: 'seer-pendant',
    name: "Seer's Pendant",
    slot: 'Neck',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { intellect: 14, spellPower: 18, spellCritRating: 6 },
  },
  {
    id: 'telonicus-pendant-of-mayhem',
    wowItemId: 30017,
    name: "Telonicus's Pendant of Mayhem",
    slot: 'Neck',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { stamina: 27, attackPower: 64, critRating: 21, hitRating: 19 },
    instance: 'The Eye',
    boss: 'High Astromancer Solarian',
    notes: 'Physical DPS neck sample for Phase 2 rankings.',
  },
  {
    id: 'choker-of-animalistic-fury',
    wowItemId: 29381,
    name: 'Choker of Animalistic Fury',
    slot: 'Neck',
    quality: 'Epic',
    source: 'Vendor',
    phase: 1,
    itemLevel: 110,
    stats: { agility: 24, stamina: 22, attackPower: 48 },
    vendor: "G'eras",
    notes: 'Badge fallback neck used to keep the slot populated before raid drops.',
  },
  {
    id: 'battle-tuned-shoulderguards',
    name: 'Battle-Tuned Shoulderguards',
    slot: 'Shoulders',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { strength: 14, agility: 10, attackPower: 22 },
  },
  {
    id: 'shoulderpads-of-the-stranger',
    wowItemId: 30055,
    name: 'Shoulderpads of the Stranger',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 32, stamina: 28, attackPower: 68, critRating: 22, hitRating: 13 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { agility: 3 },
    instance: 'Serpentshrine Cavern',
    boss: 'Hydross the Unstable',
    notes: 'Physical DPS offset shoulder sample.',
  },
  {
    id: 'cataclysm-shoulderplates',
    wowItemId: 30194,
    name: 'Cataclysm Shoulderplates',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    stats: { agility: 29, stamina: 34, intellect: 23, attackPower: 58, critRating: 20 },
    sockets: ['Red', 'Blue'],
    socketBonus: { attackPower: 4 },
    zone: 'Serpentshrine Cavern / Tempest Keep',
    notes: 'Tier 5 Enhancement set package option.',
  },
  {
    id: 'cloak-of-practice',
    name: 'Cloak of Practice',
    slot: 'Back',
    quality: 'Uncommon',
    source: 'Quest',
    phase: 1,
    stats: { stamina: 12, dodgeRating: 6 },
  },
  {
    id: 'drape-of-the-dark-reavers',
    wowItemId: 28672,
    name: 'Drape of the Dark Reavers',
    slot: 'Back',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    stats: { agility: 22, stamina: 21, attackPower: 48, hitRating: 15 },
    instance: 'Karazhan',
    boss: 'Shade of Aran',
    notes: 'Starter physical DPS cloak; rank should be validated against imported guides.',
  },
  {
    id: 'vengeance-wrap',
    wowItemId: 24259,
    name: 'Vengeance Wrap',
    slot: 'Back',
    quality: 'Epic',
    source: 'Crafted',
    phase: 1,
    itemLevel: 105,
    stats: { agility: 23, stamina: 18, attackPower: 46 },
    craftedBy: 'Tailoring',
    notes: 'Crafted DPS cloak fallback.',
  },
  {
    id: 'runed-battle-vest',
    name: 'Runed Battle Vest',
    slot: 'Chest',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { agility: 12, stamina: 20, hitRating: 8 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { critRating: 4 },
  },
  {
    id: 'spellfire-training-robe',
    name: 'Spellfire Training Robe',
    slot: 'Chest',
    quality: 'Rare',
    source: 'Crafted',
    phase: 1,
    stats: { intellect: 18, spellPower: 34, spellHitRating: 8 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { spellPower: 5 },
  },
  {
    id: 'bulwark-chestguard',
    name: 'Bulwark Chestguard',
    slot: 'Chest',
    quality: 'Rare',
    source: 'Heroic Dungeon',
    phase: 1,
    stats: { stamina: 32, defenseRating: 18, armor: 620 },
  },
  {
    id: 'cataclysm-chestplate',
    wowItemId: 30185,
    name: 'Cataclysm Chestplate',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    stats: { agility: 40, stamina: 45, intellect: 30, attackPower: 80, critRating: 27, hitRating: 18 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { agility: 4 },
    zone: 'Tempest Keep',
    instance: 'The Eye',
    notes: 'Tier 5 Enhancement chest sample.',
  },
  {
    id: 'wrists-of-focus',
    name: 'Wrists of Focus',
    slot: 'Wrists',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { spellPower: 16, spellHitRating: 8 },
  },
  {
    id: 'true-aim-stalker-bands',
    wowItemId: 30091,
    name: 'True-Aim Stalker Bands',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 28, stamina: 24, attackPower: 56, hitRating: 18 },
    instance: 'Serpentshrine Cavern',
    notes: 'Known Enhancement Shaman Phase 2 proof case.',
  },
  {
    id: 'vambraces-of-ending',
    wowItemId: 28514,
    name: 'Vambraces of Ending',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    stats: { strength: 21, stamina: 22, attackPower: 44, critRating: 14 },
    instance: 'Karazhan',
    notes: 'Melee physical fallback bracer.',
  },
  {
    id: 'gloves-of-focus',
    name: 'Gloves of Focus',
    slot: 'Hands',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { intellect: 14, spellPower: 22, spellCritRating: 6 },
  },
  {
    id: 'healers-grace-gloves',
    name: "Healer's Grace Gloves",
    slot: 'Hands',
    quality: 'Rare',
    source: 'Reputation',
    phase: 1,
    stats: { intellect: 14, healingPower: 38, mp5: 4 },
  },
  {
    id: 'cataclysm-gauntlets',
    wowItemId: 30189,
    name: 'Cataclysm Gauntlets',
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    stats: { agility: 33, stamina: 35, intellect: 23, attackPower: 66, critRating: 24, hitRating: 14 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { attackPower: 4 },
    zone: 'Serpentshrine Cavern / Tempest Keep',
    notes: 'Tier 5 Enhancement hand sample.',
  },
  {
    id: 'girdle-of-testing',
    name: 'Girdle of Testing',
    slot: 'Waist',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { strength: 12, hitRating: 8, expertiseRating: 6 },
  },
  {
    id: 'belt-of-one-hundred-deaths',
    wowItemId: 30106,
    name: 'Belt of One-Hundred Deaths',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 29, stamina: 28, attackPower: 74, critRating: 23, hitRating: 16 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { agility: 3 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    notes: 'Physical DPS belt sample.',
  },
  {
    id: 'belt-of-deep-shadow',
    wowItemId: 30040,
    name: 'Belt of Deep Shadow',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 29, stamina: 28, attackPower: 72, critRating: 21, hitRating: 15 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { agility: 3 },
    craftedBy: 'Leatherworking',
    notes: 'Crafted leatherworking DPS option; later profession filters should highlight, not hide, this row.',
  },
  {
    id: 'legguards-of-practice',
    name: 'Legguards of Practice',
    slot: 'Legs',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { strength: 10, agility: 10, stamina: 18 },
    sockets: ['Red', 'Blue'],
    socketBonus: { stamina: 4 },
  },
  {
    id: 'cataclysm-legplates',
    wowItemId: 30192,
    name: 'Cataclysm Legplates',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    stats: { agility: 42, stamina: 45, intellect: 30, attackPower: 82, critRating: 29, hitRating: 16 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { agility: 4 },
    zone: 'Serpentshrine Cavern',
    notes: 'Tier 5 Enhancement leg sample.',
  },
  {
    id: 'midnight-legguards',
    wowItemId: 30538,
    name: 'Midnight Legguards',
    slot: 'Legs',
    quality: 'Epic',
    source: 'World Drop',
    phase: 1,
    itemLevel: 105,
    stats: { agility: 30, stamina: 31, attackPower: 60, critRating: 22 },
    notes: 'World-drop fallback physical DPS legs.',
  },
  {
    id: 'boots-of-surefooting',
    name: 'Boots of Surefooting',
    slot: 'Feet',
    quality: 'Rare',
    source: 'Crafted',
    phase: 1,
    stats: { stamina: 16, hitRating: 10, critRating: 6 },
  },
  {
    id: 'boots-of-utter-darkness',
    wowItemId: 30039,
    name: 'Boots of Utter Darkness',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 30, stamina: 28, attackPower: 72, hitRating: 18, critRating: 20 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { agility: 3 },
    craftedBy: 'Leatherworking',
    notes: 'Crafted physical DPS boot option.',
  },
  {
    id: 'edgewalker-longboots',
    wowItemId: 28545,
    name: 'Edgewalker Longboots',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    stats: { agility: 30, stamina: 28, attackPower: 56, hitRating: 13 },
    instance: 'Karazhan',
    notes: 'Raid fallback physical DPS boots.',
  },
  {
    id: 'band-of-balance',
    name: 'Band of Balance',
    slot: 'Finger 1',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    unique: true,
    stats: { spellPower: 14, healingPower: 22, mp5: 3 },
  },
  {
    id: 'ring-of-a-thousand-marks',
    wowItemId: 28757,
    name: 'Ring of a Thousand Marks',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 125,
    unique: true,
    stats: { agility: 25, stamina: 24, attackPower: 50, hitRating: 18 },
    instance: 'Karazhan',
    boss: 'Prince Malchezaar',
    notes: 'Physical DPS ring sample.',
  },
  {
    id: 'ring-of-lethality',
    name: 'Garona\'s Signet Ring',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    unique: true,
    stats: { agility: 22, stamina: 22, attackPower: 46, critRating: 16 },
    instance: 'Karazhan',
    notes: 'Alternate physical ring included in Finger 1 to avoid single-slot scarcity; item ID intentionally withheld pending source audit.',
  },
  {
    id: 'signet-of-pressure',
    name: 'Signet of Pressure',
    slot: 'Finger 2',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    unique: true,
    stats: { attackPower: 28, critRating: 8 },
  },
  {
    id: 'garonas-signet-ring',
    wowItemId: 28649,
    name: "Garona's Signet Ring",
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    unique: true,
    stats: { agility: 22, stamina: 22, attackPower: 46, critRating: 16 },
    instance: 'Karazhan',
    notes: 'Physical DPS ring fallback.',
  },
  {
    id: 'veterans-band-of-triumph',
    wowItemId: 33057,
    name: "Veteran's Band of Triumph",
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'PvP',
    phase: 2,
    itemLevel: 136,
    unique: true,
    stats: { stamina: 31, attackPower: 60, critRating: 21, resilienceRating: 18 },
    vendor: 'PvP vendor',
    notes: 'PvP fallback ring with resilience tradeoff.',
  },
  {
    id: 'badge-of-momentum',
    name: 'Badge of Momentum',
    slot: 'Trinket 1',
    quality: 'Rare',
    source: 'Vendor',
    phase: 1,
    unique: true,
    stats: { attackPower: 32, hitRating: 8 },
  },
  {
    id: 'dragonspine-trophy',
    wowItemId: 28830,
    name: 'Dragonspine Trophy',
    slot: 'Trinket 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 125,
    unique: true,
    stats: { attackPower: 40, hasteRating: 40 },
    instance: "Gruul's Lair",
    boss: 'Gruul the Dragonkiller',
    notes: 'High-value physical DPS trinket sample.',
  },
  {
    id: 'bloodlust-brooch',
    wowItemId: 29383,
    name: 'Bloodlust Brooch',
    slot: 'Trinket 1',
    quality: 'Epic',
    source: 'Vendor',
    phase: 1,
    itemLevel: 110,
    unique: true,
    stats: { attackPower: 72 },
    vendor: "G'eras",
    notes: 'Badge of Justice physical DPS trinket fallback.',
  },
  {
    id: 'charm-of-embers',
    name: 'Charm of Embers',
    slot: 'Trinket 2',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    unique: true,
    stats: { spellPower: 30, spellCritRating: 8 },
  },
  {
    id: 'tsunami-talisman',
    wowItemId: 30627,
    name: 'Tsunami Talisman',
    slot: 'Trinket 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    stats: { attackPower: 38, critRating: 28, hitRating: 10 },
    instance: 'Serpentshrine Cavern',
    notes: 'Physical DPS trinket sample.',
  },
  {
    id: 'hourglass-of-the-unraveller',
    wowItemId: 28034,
    name: 'Hourglass of the Unraveller',
    slot: 'Trinket 2',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    itemLevel: 112,
    unique: true,
    stats: { attackPower: 32, critRating: 25 },
    instance: 'The Black Morass',
    boss: 'Temporus',
    notes: 'Accessible dungeon physical DPS trinket fallback.',
  },
  {
    id: 'training-sword',
    name: 'Training Sword',
    slot: 'Main Hand',
    quality: 'Rare',
    source: 'Vendor',
    phase: 1,
    stats: { attackPower: 40, critRating: 10 },
  },
  {
    id: 'apprentice-focus-staff',
    name: 'Apprentice Focus Staff',
    slot: 'Main Hand',
    quality: 'Rare',
    source: 'Vendor',
    phase: 1,
    stats: { spellPower: 54, spellHitRating: 10 },
  },
  {
    id: 'talon-of-the-phoenix',
    wowItemId: 32944,
    name: 'Talon of the Phoenix',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 141,
    stats: { agility: 20, stamina: 19, attackPower: 44, critRating: 18, hitRating: 12 },
    instance: 'The Eye',
    boss: "Kael'thas Sunstrider",
    notes: 'Enhancement Shaman weapon sample; weapon DPS/speed modeling is future work.',
  },
  {
    id: 'dragonstrike',
    wowItemId: 28439,
    name: 'Dragonstrike',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Crafted',
    phase: 1,
    itemLevel: 136,
    stats: { attackPower: 80, hasteRating: 30, critRating: 18 },
    craftedBy: 'Blacksmithing',
    notes: 'Dragonmaw upgrade path weapon; should remain visible even when Blacksmithing is not selected.',
  },
  {
    id: 'shield-of-rehearsal',
    name: 'Shield of Rehearsal',
    slot: 'Off Hand',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { stamina: 18, defenseRating: 12, blockRating: 10, blockValue: 24, armor: 900 },
  },
  {
    id: 'orb-of-prototype-power',
    name: 'Orb of Prototype Power',
    slot: 'Off Hand',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    stats: { intellect: 12, spellPower: 24 },
  },
  {
    id: 'rod-of-the-sun-king',
    wowItemId: 29996,
    name: 'Rod of the Sun King',
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 141,
    stats: { agility: 18, stamina: 18, attackPower: 42, hitRating: 12, critRating: 16 },
    instance: 'The Eye',
    boss: "Kael'thas Sunstrider",
    notes: 'Enhancement off-hand sample; weapon legality and speed modeling are future work.',
  },
  {
    id: 'claw-of-the-phoenix',
    wowItemId: 29948,
    name: 'Claw of the Phoenix',
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 138,
    stats: { agility: 18, stamina: 17, attackPower: 40, critRating: 15 },
    instance: 'The Eye',
    notes: 'Alternative off-hand melee weapon sample.',
  },
  {
    id: 'practice-longbow',
    name: 'Practice Longbow',
    slot: 'Ranged',
    quality: 'Rare',
    source: 'Vendor',
    phase: 1,
    stats: { rangedAttackPower: 36, hitRating: 8 },
  },
  {
    id: 'serpent-spine-longbow',
    name: 'Sunfury Bow of the Phoenix',
    slot: 'Ranged',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 138,
    stats: { agility: 18, rangedAttackPower: 42, critRating: 14 },
    instance: 'The Eye',
    notes: 'Hunter-style ranged weapon sample; item ID intentionally withheld pending source audit.',
  },
  {
    id: 'arcanite-steam-pistol',
    wowItemId: 29949,
    name: 'Arcanite Steam-Pistol',
    slot: 'Ranged',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { stamina: 14, rangedAttackPower: 38, hitRating: 12 },
    instance: 'Serpentshrine Cavern',
    notes: 'Ranged slot fallback sample.',
  },
  {
    id: 'totem-of-testing',
    name: 'Totem of Testing',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    allowedClasses: ['Shaman'],
    stats: { spellPower: 12, healingPower: 20 },
  },
  {
    id: 'idol-of-testing',
    name: 'Idol of Testing',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    allowedClasses: ['Druid'],
    stats: { attackPower: 16, healingPower: 18 },
  },
  {
    id: 'libram-of-testing',
    name: 'Libram of Testing',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    allowedClasses: ['Paladin'],
    stats: { defenseRating: 8, healingPower: 18 },
  },
  {
    id: 'totem-of-the-astral-winds',
    wowItemId: 27815,
    name: 'Totem of the Astral Winds',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    allowedClasses: ['Shaman'],
    stats: { attackPower: 44 },
    instance: 'The Mechanar',
    notes: 'Enhancement Shaman relic proof-of-concept option.',
  },
  {
    id: 'libram-of-avengement',
    name: 'Libram of Avengement',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    allowedClasses: ['Paladin'],
    stats: { strength: 16, critRating: 8 },
    notes: 'Paladin relic placeholder until final item ID/source audit.',
  },
  {
    id: 'idol-of-ferocity',
    name: 'Idol of Ferocity',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    allowedClasses: ['Druid'],
    stats: { attackPower: 34, agility: 8 },
    notes: 'Druid relic placeholder until final item ID/source audit.',
  },
]

export function getItemsForSlot(slot: GearSlot) {
  return sampleItems.filter((item) => isItemCompatibleWithGearSlot(item, slot))
}

export function getItemById(id: string) {
  return sampleItems.find((item) => item.id === id)
}
