import type { GearSlot } from './gearSlots'
import type { GearItem } from './itemTypes'
import { isItemCompatibleWithGearSlot } from './slotCompatibility'

export const sampleItems: readonly GearItem[] = [
  {
    id: 'prototype-adventurer-helm',
    name: 'Prototype Adventurer Helm',
    slot: 'Head',
    quality: 'Rare',
    source: 'Other',
    phase: 1,
    stats: { stamina: 18, critRating: 8 },
    sockets: ['Meta', 'Red'],
    socketBonus: { hitRating: 4 },
    notes: 'Original local starter item retained as a generic fallback.',
  },
  {
    id: 'cataclysm-helm',
    wowItemId: 30190,
    name: 'Cataclysm Headguard',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Enhancement', 'Elemental', 'Restoration'],
    armorType: 'Mail',
    roles: ['Physical DPS', 'Caster DPS', 'Healer'],
    stats: { agility: 33, stamina: 39, intellect: 25, attackPower: 66, critRating: 24, hitRating: 12 },
    sockets: ['Meta', 'Red'],
    socketBonus: { hitRating: 4 },
    zone: 'Tempest Keep',
    instance: 'The Eye',
    notes: 'Tier 5 Shaman set piece shared by all three specs (hybrid itemization); set-bonus context should beat naive raw-stat sorting.',
  },
  {
    id: 'cowl-of-defiance',
    wowItemId: 28732,
    name: 'Cowl of Defiance',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 125,
    stats: { agility: 34, stamina: 33, attackPower: 60, critRating: 24, hitRating: 16 },
    armorType: 'Leather',
    roles: ['Physical DPS'],
    instance: 'Karazhan',
    notes: 'Strong raw-stat comparison item for Enhancement Shaman tier-vs-offset testing.',
  },
  {
    id: 'seer-pendant',
    name: "Seer's Pendant",
    slot: 'Neck',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    roles: ['Caster DPS'],
    stats: { intellect: 14, spellPower: 18, spellCritRating: 6 },
  },
  {
    id: 'telonicus-pendant-of-mayhem',
    wowItemId: 30017,
    name: "Telonicus's Pendant of Mayhem",
    slot: 'Neck',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { stamina: 27, attackPower: 64, critRating: 21, hitRating: 19 },
    roles: ['Physical DPS'],
    instance: 'The Eye',
    boss: 'High Astromancer Solarian',
    notes: 'Physical DPS neck sample for Phase 2 rankings.',
  },
  {
    id: 'choker-of-animalistic-fury',
    wowItemId: 29381,
    name: 'Choker of Animalistic Fury',
    slot: 'Neck',
    quality: 'Epic',
    source: 'Vendor',
    phase: 1,
    itemLevel: 110,
    stats: { agility: 24, stamina: 22, attackPower: 48 },
    roles: ['Physical DPS'],
    vendor: "G'eras",
    notes: 'Badge fallback neck used to keep the slot populated before raid drops.',
  },
  {
    id: 'battle-tuned-shoulderguards',
    name: 'Battle-Tuned Shoulderguards',
    slot: 'Shoulders',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { strength: 14, agility: 10, attackPower: 22 },
  },
  {
    id: 'shoulderpads-of-the-stranger',
    wowItemId: 30055,
    name: 'Shoulderpads of the Stranger',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 32, stamina: 28, attackPower: 68, critRating: 22, hitRating: 13 },
    armorType: 'Leather',
    roles: ['Physical DPS'],
    sockets: ['Red', 'Yellow'],
    socketBonus: { agility: 3 },
    instance: 'Serpentshrine Cavern',
    boss: 'Hydross the Unstable',
    notes: 'Physical DPS offset shoulder sample.',
  },
  {
    id: 'cataclysm-shoulderplates',
    wowItemId: 30194,
    name: 'Cataclysm Shoulderplates',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Enhancement', 'Elemental', 'Restoration'],
    armorType: 'Mail',
    roles: ['Physical DPS', 'Caster DPS', 'Healer'],
    stats: { agility: 29, stamina: 34, intellect: 23, attackPower: 58, critRating: 20 },
    sockets: ['Red', 'Blue'],
    socketBonus: { attackPower: 4 },
    zone: 'Serpentshrine Cavern / Tempest Keep',
    notes: 'Tier 5 Shaman set piece shared by all three specs.',
  },
  {
    id: 'cloak-of-practice',
    name: 'Cloak of Practice',
    slot: 'Back',
    quality: 'Uncommon',
    source: 'Quest',
    phase: 1,
    stats: { stamina: 12, dodgeRating: 6 },
  },
  {
    id: 'drape-of-the-dark-reavers',
    wowItemId: 28672,
    name: 'Drape of the Dark Reavers',
    slot: 'Back',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    stats: { agility: 22, stamina: 21, attackPower: 48, hitRating: 15 },
    roles: ['Physical DPS'],
    instance: 'Karazhan',
    boss: 'Shade of Aran',
    notes: 'Starter physical DPS cloak; rank should be validated against imported guides.',
  },
  {
    id: 'vengeance-wrap',
    wowItemId: 24259,
    name: 'Vengeance Wrap',
    slot: 'Back',
    quality: 'Epic',
    source: 'Crafted',
    phase: 1,
    itemLevel: 105,
    stats: { agility: 23, stamina: 18, attackPower: 46 },
    roles: ['Physical DPS'],
    craftedBy: 'Tailoring',
    crafting: {
      requiredSkill: 350,
      recipeSource: 'BoE world drop pattern',
      materials: [
        { name: 'Primal Shadow', quantity: 2, farmSource: 'Shadow-school elementals/demons in Outland instances; also purchasable from other players via trade/AH.', needsVerification: true },
        { name: 'Bolt of Netherweave', quantity: 4, farmSource: 'Crafted from Netherweave Cloth, farmed off most Outland humanoids.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe/material list is a starter approximation pending final Wowhead audit.',
    },
    notes: 'Crafted DPS cloak fallback.',
  },
  {
    id: 'runed-battle-vest',
    name: 'Runed Battle Vest',
    slot: 'Chest',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { agility: 12, stamina: 20, hitRating: 8 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { critRating: 4 },
  },
  {
    id: 'spellfire-training-robe',
    name: 'Spellfire Training Robe',
    slot: 'Chest',
    quality: 'Rare',
    source: 'Crafted',
    phase: 1,
    roles: ['Caster DPS'],
    craftedBy: 'Tailoring',
    crafting: {
      requiredSkill: 350,
      specialization: 'Spellfire Tailoring',
      recipeSource: "Gidge Spellweave, Lower City, Shattrath City — sold once you've completed the Spellfire specialization quest (no reputation or drop RNG involved).",
      materials: [
        { name: 'Spellcloth', quantity: 4, farmSource: 'Crafted sub-recipe from Primal Mana + Primal Fire + Primal Life; not purchasable directly.' },
        { name: 'Primal Mana', quantity: 2, farmSource: 'Dropped by Arcane elementals in Netherstorm.' },
        { name: 'Primal Fire', quantity: 2, farmSource: 'Dropped by Fire elementals near the Throne of the Elements (Nagrand) and Fel flame mobs in Shadowmoon Valley.' },
        { name: 'Bolt of Imbued Netherweave', quantity: 2, farmSource: 'Crafted from Netherweave Cloth (farmed off most Outland humanoids) plus an Arcane Dust/Primal Mana infusion.' },
      ],
      needsVerification: true,
      notes: 'Recipe source and Spellcloth requirement are confirmed; exact per-piece material counts are approximate pending final Wowhead audit.',
    },
    stats: { intellect: 18, spellPower: 34, spellHitRating: 8 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { spellPower: 5 },
  },
  {
    id: 'bulwark-chestguard',
    name: 'Bulwark Chestguard',
    slot: 'Chest',
    quality: 'Rare',
    source: 'Heroic Dungeon',
    phase: 1,
    stats: { stamina: 32, defenseRating: 18, armor: 620 },
  },
  {
    id: 'cataclysm-chestplate',
    wowItemId: 30185,
    name: 'Cataclysm Chestplate',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Enhancement', 'Elemental', 'Restoration'],
    armorType: 'Mail',
    roles: ['Physical DPS', 'Caster DPS', 'Healer'],
    stats: { agility: 40, stamina: 45, intellect: 30, attackPower: 80, critRating: 27, hitRating: 18 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { agility: 4 },
    zone: 'Tempest Keep',
    instance: 'The Eye',
    notes: 'Tier 5 Shaman set piece shared by all three specs.',
  },
  {
    id: 'wrists-of-focus',
    name: 'Wrists of Focus',
    slot: 'Wrists',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    roles: ['Caster DPS'],
    stats: { spellPower: 16, spellHitRating: 8 },
  },
  {
    id: 'true-aim-stalker-bands',
    wowItemId: 30091,
    name: 'True-Aim Stalker Bands',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 28, stamina: 24, attackPower: 56, hitRating: 18 },
    armorType: 'Mail',
    roles: ['Physical DPS'],
    instance: 'Serpentshrine Cavern',
    boss: 'Leotheras the Blind',
    notes: 'Known Enhancement Shaman Phase 2 proof case.',
  },
  {
    id: 'vambraces-of-ending',
    wowItemId: 28514,
    name: 'Vambraces of Ending',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    stats: { strength: 21, stamina: 22, attackPower: 44, critRating: 14 },
    roles: ['Physical DPS'],
    instance: 'Karazhan',
    notes: 'Melee physical fallback bracer.',
  },
  {
    id: 'gloves-of-focus',
    name: 'Gloves of Focus',
    slot: 'Hands',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    roles: ['Caster DPS'],
    stats: { intellect: 14, spellPower: 22, spellCritRating: 6 },
  },
  {
    id: 'healers-grace-gloves',
    name: "Healer's Grace Gloves",
    slot: 'Hands',
    quality: 'Rare',
    source: 'Reputation',
    phase: 1,
    roles: ['Healer'],
    stats: { intellect: 14, healingPower: 38, mp5: 4 },
  },
  {
    id: 'cataclysm-gauntlets',
    wowItemId: 30189,
    name: 'Cataclysm Gauntlets',
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Enhancement', 'Elemental', 'Restoration'],
    armorType: 'Mail',
    roles: ['Physical DPS', 'Caster DPS', 'Healer'],
    stats: { agility: 33, stamina: 35, intellect: 23, attackPower: 66, critRating: 24, hitRating: 14 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { attackPower: 4 },
    zone: 'Serpentshrine Cavern / Tempest Keep',
    notes: 'Tier 5 Shaman set piece shared by all three specs.',
  },
  {
    id: 'girdle-of-testing',
    name: 'Girdle of Testing',
    slot: 'Waist',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { strength: 12, hitRating: 8, expertiseRating: 6 },
  },
  {
    id: 'belt-of-one-hundred-deaths',
    wowItemId: 30106,
    name: 'Belt of One-Hundred Deaths',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 29, stamina: 28, attackPower: 74, critRating: 23, hitRating: 16 },
    roles: ['Physical DPS'],
    sockets: ['Red', 'Yellow'],
    socketBonus: { agility: 3 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    notes: 'Physical DPS belt sample.',
  },
  {
    id: 'belt-of-deep-shadow',
    wowItemId: 30040,
    name: 'Belt of Deep Shadow',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 29, stamina: 28, attackPower: 72, critRating: 21, hitRating: 15 },
    armorType: 'Leather',
    roles: ['Physical DPS'],
    sockets: ['Red', 'Yellow'],
    socketBonus: { agility: 3 },
    craftedBy: 'Leatherworking',
    crafting: {
      requiredSkill: 340,
      recipeSource: 'BoE world drop pattern (exact source needs final audit).',
      materials: [
        { name: 'Knothide Leather', quantity: 8, farmSource: 'Crafted from Knothide Leather Scraps, skinned throughout Outland.', needsVerification: true },
        { name: 'Primal Shadow', quantity: 2, farmSource: 'Shadow-school elementals/demons in Outland instances; also purchasable from other players via trade/AH.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe source and material list are a starter approximation pending final Wowhead audit.',
    },
    notes: 'Crafted leatherworking DPS option; later profession filters should highlight, not hide, this row.',
  },
  {
    id: 'legguards-of-practice',
    name: 'Legguards of Practice',
    slot: 'Legs',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    stats: { strength: 10, agility: 10, stamina: 18 },
    sockets: ['Red', 'Blue'],
    socketBonus: { stamina: 4 },
  },
  {
    id: 'cataclysm-legplates',
    wowItemId: 30192,
    name: 'Cataclysm Legplates',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Enhancement', 'Elemental', 'Restoration'],
    armorType: 'Mail',
    roles: ['Physical DPS', 'Caster DPS', 'Healer'],
    stats: { agility: 42, stamina: 45, intellect: 30, attackPower: 82, critRating: 29, hitRating: 16 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { agility: 4 },
    zone: 'Serpentshrine Cavern',
    notes: 'Tier 5 Shaman set piece shared by all three specs.',
  },
  {
    id: 'midnight-legguards',
    wowItemId: 30538,
    name: 'Midnight Legguards',
    slot: 'Legs',
    quality: 'Epic',
    source: 'World Drop',
    phase: 1,
    itemLevel: 105,
    stats: { agility: 30, stamina: 31, attackPower: 60, critRating: 22 },
    roles: ['Physical DPS'],
    notes: 'World-drop fallback physical DPS legs.',
  },
  {
    id: 'boots-of-surefooting',
    name: 'Boots of Surefooting',
    slot: 'Feet',
    quality: 'Rare',
    source: 'Crafted',
    phase: 1,
    stats: { stamina: 16, hitRating: 10, critRating: 6 },
  },
  {
    id: 'boots-of-utter-darkness',
    wowItemId: 30039,
    name: 'Boots of Utter Darkness',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    stats: { agility: 30, stamina: 28, attackPower: 72, hitRating: 18, critRating: 20 },
    armorType: 'Leather',
    roles: ['Physical DPS'],
    sockets: ['Red', 'Yellow'],
    socketBonus: { agility: 3 },
    craftedBy: 'Leatherworking',
    crafting: {
      requiredSkill: 350,
      specialization: 'Dragonscale Leatherworking',
      recipeSource: 'Leatherworking trainer or BoE world drop pattern (exact source needs final audit).',
      materials: [
        { name: 'Primal Life', quantity: 2, farmSource: 'Dropped by Life-school elementals/treants in Outland zones such as Nagrand and Zangarmarsh.', needsVerification: true },
        { name: 'Fel Scales', quantity: 4, farmSource: 'Skinned from Outland demon-type beasts (Felboars, Fel Stalkers).', needsVerification: true },
        { name: 'Knothide Leather', quantity: 6, farmSource: 'Crafted from Knothide Leather Scraps, skinned throughout Outland.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe source and material list are a starter approximation pending final Wowhead audit.',
    },
    notes: 'Crafted physical DPS boot option.',
  },
  {
    id: 'edgewalker-longboots',
    wowItemId: 28545,
    name: 'Edgewalker Longboots',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    stats: { agility: 30, stamina: 28, attackPower: 56, hitRating: 13 },
    roles: ['Physical DPS'],
    instance: 'Karazhan',
    notes: 'Raid fallback physical DPS boots.',
  },
  {
    id: 'band-of-balance',
    name: 'Band of Balance',
    slot: 'Finger 1',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    unique: true,
    stats: { spellPower: 14, healingPower: 22, mp5: 3 },
    roles: ['Healer', 'Caster DPS'],
  },
  {
    id: 'ring-of-a-thousand-marks',
    wowItemId: 28757,
    name: 'Ring of a Thousand Marks',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 125,
    unique: true,
    stats: { agility: 25, stamina: 24, attackPower: 50, hitRating: 18 },
    roles: ['Physical DPS'],
    instance: 'Karazhan',
    boss: 'Prince Malchezaar',
    notes: 'Physical DPS ring sample.',
  },
  {
    id: 'ring-of-lethality',
    name: 'Garona\'s Signet Ring',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    unique: true,
    stats: { agility: 22, stamina: 22, attackPower: 46, critRating: 16 },
    roles: ['Physical DPS'],
    instance: 'Karazhan',
    notes: 'Alternate physical ring included in Finger 1 to avoid single-slot scarcity; item ID intentionally withheld pending source audit.',
  },
  {
    id: 'signet-of-pressure',
    name: 'Signet of Pressure',
    slot: 'Finger 2',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    unique: true,
    stats: { attackPower: 28, critRating: 8 },
    roles: ['Physical DPS'],
  },
  {
    id: 'garonas-signet-ring',
    wowItemId: 28649,
    name: "Garona's Signet Ring",
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    unique: true,
    stats: { agility: 22, stamina: 22, attackPower: 46, critRating: 16 },
    roles: ['Physical DPS'],
    instance: 'Karazhan',
    notes: 'Physical DPS ring fallback.',
  },
  {
    id: 'veterans-band-of-triumph',
    wowItemId: 33057,
    name: "Veteran's Band of Triumph",
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'PvP',
    phase: 2,
    itemLevel: 136,
    unique: true,
    stats: { stamina: 31, attackPower: 60, critRating: 21, resilienceRating: 18 },
    roles: ['Physical DPS'],
    vendor: 'PvP vendor',
    notes: 'PvP fallback ring with resilience tradeoff.',
  },
  {
    id: 'badge-of-momentum',
    name: 'Badge of Momentum',
    slot: 'Trinket 1',
    quality: 'Rare',
    source: 'Vendor',
    phase: 1,
    unique: true,
    stats: { attackPower: 32, hitRating: 8 },
    roles: ['Physical DPS'],
  },
  {
    id: 'dragonspine-trophy',
    wowItemId: 28830,
    name: 'Dragonspine Trophy',
    slot: 'Trinket 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 125,
    unique: true,
    stats: { attackPower: 40, hasteRating: 40 },
    roles: ['Physical DPS'],
    instance: "Gruul's Lair",
    boss: 'Gruul the Dragonkiller',
    notes: 'High-value physical DPS trinket sample.',
  },
  {
    id: 'bloodlust-brooch',
    wowItemId: 29383,
    name: 'Bloodlust Brooch',
    slot: 'Trinket 1',
    quality: 'Epic',
    source: 'Vendor',
    phase: 1,
    itemLevel: 110,
    unique: true,
    stats: { attackPower: 72 },
    roles: ['Physical DPS'],
    vendor: "G'eras",
    notes: 'Badge of Justice physical DPS trinket fallback.',
  },
  {
    id: 'charm-of-embers',
    name: 'Charm of Embers',
    slot: 'Trinket 2',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    unique: true,
    stats: { spellPower: 30, spellCritRating: 8 },
    roles: ['Caster DPS'],
  },
  {
    id: 'tsunami-talisman',
    wowItemId: 30627,
    name: 'Tsunami Talisman',
    slot: 'Trinket 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    stats: { attackPower: 38, critRating: 28, hitRating: 10 },
    roles: ['Physical DPS'],
    needsVerification: true,
    instance: 'Serpentshrine Cavern',
    notes: 'Physical DPS trinket sample.',
  },
  {
    id: 'hourglass-of-the-unraveller',
    wowItemId: 28034,
    name: 'Hourglass of the Unraveller',
    slot: 'Trinket 2',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    itemLevel: 112,
    unique: true,
    stats: { attackPower: 32, critRating: 25 },
    roles: ['Physical DPS'],
    instance: 'The Black Morass',
    boss: 'Temporus',
    notes: 'Accessible dungeon physical DPS trinket fallback.',
  },
  {
    id: 'training-sword',
    name: 'Training Sword',
    slot: 'Main Hand',
    quality: 'Rare',
    source: 'Vendor',
    phase: 1,
    weaponType: 'Sword',
    roles: ['Physical DPS'],
    stats: { attackPower: 40, critRating: 10 },
  },
  {
    id: 'apprentice-focus-staff',
    name: 'Apprentice Focus Staff',
    slot: 'Main Hand',
    quality: 'Rare',
    source: 'Vendor',
    phase: 1,
    weaponType: 'Staff',
    roles: ['Caster DPS', 'Healer'],
    stats: { spellPower: 54, spellHitRating: 10 },
  },
  {
    id: 'talon-of-the-phoenix',
    wowItemId: 32944,
    name: 'Talon of the Phoenix',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 141,
    weaponType: 'Fist Weapon',
    roles: ['Physical DPS'],
    stats: { agility: 20, stamina: 19, attackPower: 44, critRating: 18, hitRating: 12 },
    instance: 'The Eye',
    boss: "Kael'thas Sunstrider",
    notes: 'Enhancement Shaman weapon sample; weapon DPS/speed modeling is future work.',
  },
  {
    id: 'dragonstrike',
    wowItemId: 28439,
    name: 'Dragonstrike',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Crafted',
    phase: 1,
    itemLevel: 136,
    weaponType: 'Mace',
    roles: ['Physical DPS'],
    stats: { attackPower: 80, hasteRating: 30, critRating: 18 },
    craftedBy: 'Blacksmithing',
    crafting: {
      requiredSkill: 375,
      specialization: 'Hammersmith',
      recipeSource: 'Weaponsmith trainer (requires the Hammersmith specialization quest); crafted in three stages, each stage upgrading the previous weapon in place.',
      materials: [
        { name: 'Adamantite Bar', quantity: 8, farmSource: 'Smelted from Adamantite Ore, mined throughout Outland (Blade\'s Edge Mountains, Nagrand, etc.).', needsVerification: true },
        { name: 'Primal Might', quantity: 1, farmSource: 'Crafted by an Alchemist (Transmute: Primal Might) from Primal Nether plus one of each other Primal.', needsVerification: true },
        { name: 'Primal Nether', quantity: 1, farmSource: 'Drops from the final boss of Heroic (non-normal) 5-man dungeons; also usable for the stage-2 upgrade.' },
        { name: 'Nether Vortex', quantity: 1, farmSource: 'Drops from trash and bosses in Serpentshrine Cavern and Tempest Keep (stage-3 upgrade).' },
      ],
      needsVerification: true,
      notes: 'Multi-stage Blacksmithing upgrade path; exact per-stage material counts are approximate pending final Wowhead audit.',
    },
    notes: 'Dragonmaw upgrade path weapon; should remain visible even when Blacksmithing is not selected.',
  },
  {
    id: 'shield-of-rehearsal',
    name: 'Shield of Rehearsal',
    slot: 'Off Hand',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    armorType: 'Shield',
    weaponType: 'Shield',
    roles: ['Tank'],
    stats: { stamina: 18, defenseRating: 12, blockRating: 10, blockValue: 24, armor: 900 },
  },
  {
    id: 'orb-of-prototype-power',
    name: 'Orb of Prototype Power',
    slot: 'Off Hand',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    weaponType: 'Held In Off-hand',
    roles: ['Caster DPS', 'Healer'],
    stats: { intellect: 12, spellPower: 24 },
  },
  {
    id: 'rod-of-the-sun-king',
    wowItemId: 29996,
    name: 'Rod of the Sun King',
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 141,
    weaponType: 'Mace',
    roles: ['Physical DPS'],
    stats: { agility: 18, stamina: 18, attackPower: 42, hitRating: 12, critRating: 16 },
    instance: 'The Eye',
    boss: "Kael'thas Sunstrider",
    notes: 'Enhancement off-hand sample; weapon legality and speed modeling are future work.',
  },
  {
    id: 'claw-of-the-phoenix',
    wowItemId: 29948,
    name: 'Claw of the Phoenix',
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 138,
    weaponType: 'Fist Weapon',
    roles: ['Physical DPS'],
    needsVerification: true,
    stats: { agility: 18, stamina: 17, attackPower: 40, critRating: 15 },
    instance: 'The Eye',
    notes: 'Alternative off-hand melee weapon sample.',
  },
  {
    id: 'practice-longbow',
    name: 'Practice Longbow',
    slot: 'Ranged',
    quality: 'Rare',
    source: 'Vendor',
    phase: 1,
    weaponType: 'Bow',
    roles: ['Physical DPS'],
    stats: { rangedAttackPower: 36, hitRating: 8 },
  },
  {
    id: 'serpent-spine-longbow',
    name: 'Sunfury Bow of the Phoenix',
    slot: 'Ranged',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 138,
    weaponType: 'Bow',
    roles: ['Physical DPS'],
    needsVerification: true,
    stats: { agility: 18, rangedAttackPower: 42, critRating: 14 },
    instance: 'The Eye',
    notes: 'Hunter-style ranged weapon sample; item ID intentionally withheld pending source audit.',
  },
  {
    id: 'arcanite-steam-pistol',
    wowItemId: 29949,
    name: 'Arcanite Steam-Pistol',
    slot: 'Ranged',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    weaponType: 'Gun',
    roles: ['Physical DPS'],
    stats: { stamina: 14, rangedAttackPower: 38, hitRating: 12 },
    instance: 'Serpentshrine Cavern',
    notes: 'Ranged slot fallback sample.',
  },
  {
    id: 'no-ranged-enhancement-shaman',
    name: 'No Ranged Weapon Recommended',
    slot: 'Ranged',
    quality: 'Common',
    source: 'Other',
    phase: 2,
    allowedClasses: ['Shaman', 'Paladin', 'Druid'],
    weaponType: 'Other',
    stats: {},
    notes: 'Shaman, Paladin, and Druid use the Relic slot (Totem/Libram/Idol) instead of a Ranged weapon; Ranged and Relic are the same equipment slot in real TBC.',
  },
  {
    id: 'totem-of-testing',
    name: 'Totem of Testing',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    allowedClasses: ['Shaman'],
    weaponType: 'Totem',
    armorType: 'Relic',
    roles: ['Caster DPS', 'Healer'],
    stats: { spellPower: 12, healingPower: 20 },
  },
  {
    id: 'idol-of-testing',
    name: 'Idol of Testing',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    allowedClasses: ['Druid'],
    weaponType: 'Idol',
    armorType: 'Relic',
    stats: { attackPower: 16, healingPower: 18 },
  },
  {
    id: 'libram-of-testing',
    name: 'Libram of Testing',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    allowedClasses: ['Paladin'],
    weaponType: 'Libram',
    armorType: 'Relic',
    stats: { defenseRating: 8, healingPower: 18 },
  },
  {
    id: 'totem-of-the-astral-winds',
    wowItemId: 27815,
    name: 'Totem of the Astral Winds',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Enhancement'],
    weaponType: 'Totem',
    armorType: 'Relic',
    roles: ['Physical DPS'],
    stats: { attackPower: 44 },
    instance: 'The Mechanar',
    notes: 'Enhancement Shaman relic proof-of-concept option.',
  },
  {
    id: 'libram-of-avengement',
    name: 'Libram of Avengement',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Retribution'],
    weaponType: 'Libram',
    armorType: 'Relic',
    roles: ['Physical DPS'],
    stats: { strength: 16, critRating: 8 },
    instance: 'The Blood Furnace',
    boss: 'The Maker',
    needsVerification: true,
    notes: 'Retribution Paladin relic; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'idol-of-ferocity',
    name: 'Idol of Ferocity',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    allowedClasses: ['Druid'],
    weaponType: 'Idol',
    armorType: 'Relic',
    stats: { attackPower: 34, agility: 8 },
    notes: 'Druid relic placeholder until final item ID/source audit.',
  },

  // Elemental Shaman Phase 1/2 starter items (see src/domain/bis/elementalShamanPhase2.ts).
  {
    id: 'sun-kings-talisman',
    name: "The Sun King's Talisman",
    slot: 'Neck',
    quality: 'Epic',
    source: 'Quest',
    phase: 2,
    itemLevel: 128,
    allowedClasses: ['Shaman'],
    roles: ['Caster DPS'],
    stats: { intellect: 20, spellPower: 54, spellCritRating: 15 },
    zone: 'Tempest Keep',
    needsVerification: true,
    notes: "Quest reward from the Kael'thas Sunstrider encounter chain; stats are approximate pending final Wowhead audit.",
  },
  {
    id: 'cyclone-shoulderguards',
    name: 'Cyclone Shoulderguards',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Elemental'],
    armorType: 'Mail',
    roles: ['Caster DPS'],
    stats: { intellect: 24, stamina: 26, spellPower: 40, spellCritRating: 14, spellHitRating: 10 },
    sockets: ['Yellow', 'Blue'],
    socketBonus: { spellPower: 3 },
    instance: "Gruul's Lair",
    boss: 'High King Maulgar',
    needsVerification: true,
    notes: 'Tier 4 Elemental set piece (token drop); stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'brute-cloak-of-the-ogre-magi',
    name: 'Brute Cloak of the Ogre-Magi',
    slot: 'Back',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    roles: ['Caster DPS'],
    stats: { intellect: 20, stamina: 18, spellPower: 36, spellHitRating: 14 },
    instance: "Gruul's Lair",
    boss: 'High King Maulgar',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'mindstorm-wristbands',
    name: 'Mindstorm Wristbands',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Caster DPS'],
    stats: { intellect: 30, spellPower: 34, spellCritRating: 12 },
    instance: 'Tempest Keep',
    boss: "Al'ar",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'soul-eaters-handwraps',
    name: "Soul-Eater's Handwraps",
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 120,
    roles: ['Caster DPS'],
    stats: { intellect: 24, stamina: 20, spellPower: 42, spellHitRating: 14 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { spellPower: 3 },
    instance: "Magtheridon's Lair",
    boss: 'Magtheridon',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'belt-of-blasting',
    name: 'Belt of Blasting',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    craftedBy: 'Tailoring',
    roles: ['Caster DPS'],
    stats: { intellect: 28, stamina: 24, spellPower: 44, spellHitRating: 16 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { intellect: 4 },
    needsVerification: true,
    notes: 'Generic caster-DPS crafted belt shared by every caster spec, not Shaman-specific; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'velvet-boots-of-the-guardian',
    name: 'Velvet Boots of the Guardian',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Caster DPS', 'Healer'],
    stats: { intellect: 24, stamina: 22, spellPower: 38, mp5: 6 },
    instance: 'Serpentshrine Cavern',
    boss: 'The Lurker Below',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'ring-of-unrelenting-storms',
    name: 'Ring of Unrelenting Storms',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    unique: true,
    roles: ['Caster DPS'],
    stats: { intellect: 20, spellPower: 30, spellCritRating: 10 },
    instance: 'Karazhan',
    needsVerification: true,
    notes: 'Trash drop; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'ring-of-endless-coils',
    name: 'Ring of Endless Coils',
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Caster DPS'],
    stats: { intellect: 22, stamina: 20, spellPower: 34, spellHitRating: 12 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'the-lightning-capacitor',
    name: 'The Lightning Capacitor',
    slot: 'Trinket 1',
    quality: 'Epic',
    source: 'Quest',
    phase: 1,
    unique: true,
    roles: ['Caster DPS'],
    stats: { intellect: 20, spellCritRating: 20 },
    instance: 'Karazhan',
    needsVerification: true,
    notes: 'Proc effect (Chain Lightning bolt on stacked spell crits) is not modeled yet; passive stats only, pending final Wowhead audit.',
  },
  {
    id: 'icon-of-the-silver-crescent',
    name: 'Icon of the Silver Crescent',
    slot: 'Trinket 2',
    quality: 'Epic',
    source: 'Vendor',
    phase: 1,
    unique: true,
    roles: ['Caster DPS', 'Tank'],
    stats: { spellPower: 34 },
    vendor: "G'eras",
    needsVerification: true,
    notes: 'Badge of Justice vendor trinket; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'the-nexus-key',
    name: 'The Nexus-Key',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 141,
    weaponType: 'Staff',
    roles: ['Caster DPS'],
    stats: { intellect: 30, stamina: 24, spellPower: 85, spellCritRating: 20 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Weapon DPS/speed modeling is future work; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'totem-of-the-void',
    name: 'Totem of the Void',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Elemental'],
    weaponType: 'Totem',
    armorType: 'Relic',
    roles: ['Caster DPS'],
    stats: { spellPower: 28 },
    instance: 'The Mechanar',
    needsVerification: true,
    notes: 'Elemental Shaman relic proof-of-concept row; stats are approximate pending final Wowhead audit.',
  },

  // Restoration Shaman Phase 1/2 starter items (see src/domain/bis/restorationShamanPhase2.ts).
  {
    id: 'lord-sanguinars-claim',
    name: "Lord Sanguinar's Claim",
    slot: 'Neck',
    quality: 'Epic',
    source: 'Quest',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 20, stamina: 18, healingPower: 46, mp5: 5 },
    zone: 'Tempest Keep',
    needsVerification: true,
    notes: "Quest reward from the Kael'thas Sunstrider encounter chain; stats are approximate pending final Wowhead audit.",
  },
  {
    id: 'sunshower-light-cloak',
    name: 'Sunshower Light Cloak',
    slot: 'Back',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 20, stamina: 18, healingPower: 40, mp5: 5 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'blackfathom-warbands',
    name: 'Blackfathom Warbands',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 20, stamina: 18, healingPower: 44 },
    instance: 'Serpentshrine Cavern',
    boss: 'Hydross the Unstable',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'worldstorm-gauntlets',
    name: 'Worldstorm Gauntlets',
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 24, stamina: 20, healingPower: 50, mp5: 6 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { mp5: 2 },
    instance: 'Tempest Keep',
    boss: 'High Astromancer Solarian',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'primal-mooncloth-belt',
    name: 'Primal Mooncloth Belt',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    craftedBy: 'Tailoring',
    roles: ['Healer'],
    stats: { intellect: 26, stamina: 22, healingPower: 46, mp5: 6 },
    sockets: ['Yellow'],
    socketBonus: { intellect: 3 },
    needsVerification: true,
    notes: 'Generic healer crafted belt, not Shaman-specific; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'sunhawk-leggings',
    name: 'Sunhawk Leggings',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    roles: ['Healer'],
    stats: { intellect: 28, stamina: 26, healingPower: 58, mp5: 8 },
    sockets: ['Blue', 'Yellow'],
    socketBonus: { mp5: 2 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'orca-hide-boots',
    name: 'Orca-Hide Boots',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 22, stamina: 20, healingPower: 42, mp5: 5 },
    instance: 'Serpentshrine Cavern',
    boss: 'Leotheras the Blind',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'jade-ring-of-the-everliving',
    name: 'Jade Ring of the Everliving',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    unique: true,
    roles: ['Healer'],
    stats: { intellect: 18, stamina: 16, healingPower: 34, mp5: 4 },
    instance: 'Karazhan',
    boss: 'Prince Malchezaar',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'phoenix-ring-of-rebirth',
    name: 'Phoenix-Ring of Rebirth',
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Healer'],
    stats: { intellect: 20, stamina: 18, healingPower: 38, mp5: 5 },
    instance: 'Tempest Keep',
    boss: "Al'ar",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'essence-of-the-martyr',
    name: 'Essence of the Martyr',
    slot: 'Trinket 1',
    quality: 'Epic',
    source: 'Vendor',
    phase: 1,
    unique: true,
    roles: ['Healer'],
    stats: { healingPower: 54 },
    vendor: "G'eras",
    needsVerification: true,
    notes: 'Badge of Justice vendor trinket (41 badges); stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'scarab-of-the-infinite-cycle',
    name: 'Scarab of the Infinite Cycle',
    slot: 'Trinket 2',
    quality: 'Rare',
    source: 'Heroic Dungeon',
    phase: 1,
    unique: true,
    roles: ['Healer'],
    stats: { healingPower: 34 },
    instance: 'The Black Morass',
    boss: 'Aeonus',
    needsVerification: true,
    notes: 'On-use haste proc is not modeled yet; passive stats only, pending final Wowhead audit.',
  },
  {
    id: 'lightfathom-scepter',
    name: 'Lightfathom Scepter',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 141,
    weaponType: 'Mace',
    roles: ['Healer'],
    stats: { intellect: 26, stamina: 22, healingPower: 95, mp5: 8 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Weapon DPS/speed modeling is future work; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'aegis-of-the-vindicator',
    name: 'Aegis of the Vindicator',
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 120,
    weaponType: 'Shield',
    armorType: 'Shield',
    roles: ['Healer'],
    stats: { stamina: 24, intellect: 20, healingPower: 40 },
    instance: "Magtheridon's Lair",
    needsVerification: true,
    notes: 'Shared healer shield (Priest/Paladin/Shaman); stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'totem-of-healing-rains',
    name: 'Totem of Healing Rains',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Raid',
    phase: 1,
    allowedClasses: ['Shaman'],
    allowedSpecs: ['Restoration'],
    weaponType: 'Totem',
    armorType: 'Relic',
    roles: ['Healer'],
    stats: { healingPower: 34 },
    instance: 'Karazhan',
    boss: 'Maiden of Virtue',
    needsVerification: true,
    notes: 'Restoration Shaman relic proof-of-concept row; stats are approximate pending final Wowhead audit.',
  },

  // Warrior Phase 1/2 starter items (see src/domain/bis/{arms,fury,protection}WarriorPhase2.ts).
  {
    id: 'destroyer-battle-helm',
    name: 'Destroyer Battle-Helm',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Warrior'],
    allowedSpecs: ['Arms', 'Fury'],
    armorType: 'Plate',
    roles: ['Physical DPS'],
    stats: { strength: 38, stamina: 40, critRating: 26, hitRating: 18 },
    sockets: ['Meta', 'Red'],
    socketBonus: { hitRating: 4 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Tier 5 DPS set piece shared by Arms and Fury; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'destroyer-greathelm',
    name: 'Destroyer Greathelm',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Warrior'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 42, defenseRating: 22, dodgeRating: 14, parryRating: 12 },
    sockets: ['Meta', 'Red'],
    socketBonus: { stamina: 4 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Tier 5 Protection set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'pendant-of-the-perilous',
    name: 'Pendant of the Perilous',
    slot: 'Neck',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Physical DPS'],
    stats: { strength: 24, stamina: 20, critRating: 20, hitRating: 14 },
    instance: 'Serpentshrine Cavern',
    needsVerification: true,
    notes: 'Trash drop; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'veterans-pendant-of-triumph',
    name: "Veteran's Pendant of Triumph",
    slot: 'Neck',
    quality: 'Epic',
    source: 'PvP',
    phase: 2,
    itemLevel: 128,
    roles: ['Tank'],
    stats: { stamina: 26, defenseRating: 16, resilienceRating: 12 },
    vendor: 'PvP vendor (Honor + Eye of the Storm marks)',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'destroyer-shoulderblades',
    name: 'Destroyer Shoulderblades',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    allowedClasses: ['Warrior'],
    allowedSpecs: ['Fury'],
    armorType: 'Plate',
    roles: ['Physical DPS'],
    stats: { strength: 32, stamina: 30, critRating: 22, hitRating: 14 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { strength: 3 },
    instance: 'Tempest Keep',
    boss: 'Void Reaver',
    needsVerification: true,
    notes: 'Tier 5 Fury set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'destroyer-shoulderguards-tank',
    name: 'Destroyer Shoulderguards',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    allowedClasses: ['Warrior'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 34, defenseRating: 20, dodgeRating: 14, parryRating: 10 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { stamina: 3 },
    instance: 'Tempest Keep',
    boss: 'Void Reaver',
    needsVerification: true,
    notes: 'Tier 5 Protection set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'phoenix-wing-cloak',
    name: 'Phoenix-Wing Cloak',
    slot: 'Back',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Tank'],
    stats: { stamina: 24, defenseRating: 18, dodgeRating: 12 },
    instance: 'Tempest Keep',
    boss: "Al'ar",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'destroyer-breastplate',
    name: 'Destroyer Breastplate',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Warrior'],
    allowedSpecs: ['Arms', 'Fury'],
    armorType: 'Plate',
    roles: ['Physical DPS'],
    stats: { strength: 44, stamina: 46, critRating: 28, hitRating: 20 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { strength: 4 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Tier 5 DPS set piece shared by Arms and Fury; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'destroyer-chestguard-tank',
    name: 'Destroyer Chestguard',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Warrior'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 48, defenseRating: 24, dodgeRating: 16, parryRating: 12 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { stamina: 4 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Tier 5 Protection set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'bladespire-warbands',
    name: 'Bladespire Warbands',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    roles: ['Physical DPS'],
    stats: { strength: 26, stamina: 22, critRating: 16 },
    instance: "Gruul's Lair",
    boss: 'High King Maulgar',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'bracers-of-eradication',
    name: 'Bracers of Eradication',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Physical DPS'],
    stats: { strength: 28, stamina: 24, hitRating: 16 },
    instance: 'Serpentshrine Cavern',
    boss: 'The Lurker Below',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'veterans-plate-bracers',
    name: "Veteran's Plate Bracers",
    slot: 'Wrists',
    quality: 'Epic',
    source: 'PvP',
    phase: 2,
    itemLevel: 128,
    roles: ['Tank'],
    stats: { stamina: 28, defenseRating: 18 },
    vendor: 'PvP vendor (Honor + Warsong Gulch marks)',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'destroyer-gauntlets',
    name: 'Destroyer Gauntlets',
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    allowedClasses: ['Warrior'],
    allowedSpecs: ['Arms', 'Fury'],
    armorType: 'Plate',
    roles: ['Physical DPS'],
    stats: { strength: 34, stamina: 30, critRating: 22, hitRating: 16 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { strength: 4 },
    instance: 'Serpentshrine Cavern',
    boss: 'Leotheras the Blind',
    needsVerification: true,
    notes: 'Tier 5 DPS set piece shared by Arms and Fury; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'gloves-of-the-searing-grip',
    name: 'Gloves of the Searing Grip',
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Tank', 'Physical DPS'],
    stats: { stamina: 30, defenseRating: 20, hitRating: 12 },
    instance: 'Tempest Keep',
    boss: "Al'ar",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'destroyer-greaves',
    name: 'Destroyer Greaves',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    roles: ['Physical DPS'],
    stats: { strength: 40, stamina: 36, critRating: 26, hitRating: 18 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { strength: 4 },
    instance: 'Serpentshrine Cavern',
    boss: 'Fathom-Lord Karathress',
    needsVerification: true,
    notes: 'Arms Phase 2 legs; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'leggings-of-murderous-intent',
    name: 'Leggings of Murderous Intent',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Physical DPS'],
    stats: { strength: 36, stamina: 32, hasteRating: 20, critRating: 18 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Fury Phase 2 legs; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'destroyer-legguards-tank',
    name: 'Destroyer Legguards',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Warrior'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 50, defenseRating: 26, dodgeRating: 18, parryRating: 12 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { stamina: 4 },
    instance: 'Serpentshrine Cavern',
    boss: 'Fathom-Lord Karathress',
    needsVerification: true,
    notes: 'Tier 5 Protection set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'warboots-of-obliteration',
    name: 'Warboots of Obliteration',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Physical DPS'],
    stats: { strength: 30, stamina: 28, hitRating: 18, critRating: 16 },
    instance: 'Serpentshrine Cavern',
    boss: 'Morogrim Tidewalker',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'veterans-plate-greaves',
    name: "Veteran's Plate Greaves",
    slot: 'Feet',
    quality: 'Epic',
    source: 'PvP',
    phase: 2,
    itemLevel: 128,
    roles: ['Tank'],
    stats: { stamina: 30, defenseRating: 20, resilienceRating: 12 },
    vendor: 'PvP vendor (Honor + Eye of the Storm marks)',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'band-of-the-ranger-general',
    name: 'Band of the Ranger-General',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Physical DPS'],
    stats: { strength: 24, stamina: 22, critRating: 18, hitRating: 14 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Shared Arms/Fury Phase 2 ring; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'shapeshifters-signet',
    name: "Shapeshifter's Signet",
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Reputation',
    phase: 2,
    itemLevel: 120,
    unique: true,
    roles: ['Physical DPS', 'Tank'],
    stats: { stamina: 24, defenseRating: 12, attackPower: 34 },
    reputation: 'Lower City (Exalted)',
    needsVerification: true,
    notes: 'Hybrid DPS/Tank reputation ring usable by Arms and Protection; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'ring-of-sundered-souls',
    name: 'Ring of Sundered Souls',
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Tank'],
    stats: { stamina: 26, defenseRating: 18, dodgeRating: 10 },
    instance: 'Serpentshrine Cavern',
    boss: 'Morogrim Tidewalker',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'icon-of-unyielding-courage',
    name: 'Icon of Unyielding Courage',
    slot: 'Trinket 1',
    quality: 'Rare',
    source: 'Heroic Dungeon',
    phase: 1,
    unique: true,
    roles: ['Tank'],
    stats: { stamina: 20, defenseRating: 22 },
    instance: 'The Blood Furnace',
    boss: "Keli'dan the Breaker",
    needsVerification: true,
    notes: 'On-use threat/avoidance proc is not modeled yet; passive stats only, pending final Wowhead audit.',
  },
  {
    id: 'twinblade-of-the-phoenix',
    name: 'Twinblade of the Phoenix',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 141,
    weaponType: 'Sword',
    roles: ['Physical DPS'],
    stats: { strength: 38, stamina: 30, critRating: 24, hitRating: 18 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Arms two-hander; weapon DPS/speed modeling is future work, stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'talon-of-azshara',
    name: 'Talon of Azshara',
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    weaponType: 'Axe',
    roles: ['Physical DPS'],
    stats: { agility: 20, stamina: 18, attackPower: 46, critRating: 16 },
    instance: 'Serpentshrine Cavern',
    boss: 'Morogrim Tidewalker',
    needsVerification: true,
    notes: 'Fury dual-wield off-hand; weapon type is approximate pending final Wowhead audit.',
  },
  {
    id: 'mallet-of-the-tides',
    name: 'Mallet of the Tides',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    weaponType: 'Mace',
    roles: ['Tank'],
    stats: { stamina: 32, defenseRating: 20, blockRating: 12 },
    instance: 'Serpentshrine Cavern',
    boss: 'The Lurker Below',
    needsVerification: true,
    notes: 'Protection main-hand; weapon DPS/speed modeling is future work.',
  },
  {
    id: 'aldori-legacy-defender',
    name: 'Aldori Legacy Defender',
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 120,
    weaponType: 'Shield',
    armorType: 'Shield',
    roles: ['Tank'],
    stats: { stamina: 28, defenseRating: 22, blockRating: 14, armor: 1400 },
    instance: "Gruul's Lair",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'gyro-balanced-khorium-destroyer',
    name: 'Gyro-Balanced Khorium Destroyer',
    slot: 'Ranged',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    weaponType: 'Gun',
    roles: ['Tank'],
    stats: { stamina: 14, defenseRating: 10, hitRating: 8 },
    craftedBy: 'Engineering',
    needsVerification: true,
    notes: 'Protection ranged filler; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'no-relic-placeholder',
    name: 'No Relic Recommended',
    slot: 'Relic',
    quality: 'Common',
    source: 'Other',
    allowedClasses: ['Warrior', 'Hunter', 'Mage', 'Priest', 'Rogue', 'Warlock'],
    weaponType: 'Other',
    armorType: 'Relic',
    stats: {},
    notes: 'Only Shaman, Paladin, and Druid use the Relic slot in TBC; this zero-stat placeholder keeps other classes from silently inheriting phantom stats from a previously equipped Totem/Libram/Idol.',
  },

  // Holy Paladin Phase 1/2 starter items (see src/domain/bis/holyPaladinPhase2.ts).
  {
    id: 'crystalforge-greathelm',
    name: 'Crystalforge Greathelm',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Holy'],
    armorType: 'Plate',
    roles: ['Healer'],
    stats: { intellect: 30, stamina: 34, spirit: 22, healingPower: 62, mp5: 8 },
    sockets: ['Meta', 'Blue'],
    socketBonus: { mp5: 3 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Tier 5 Holy set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'crystalforge-pauldrons',
    name: 'Crystalforge Pauldrons',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Holy'],
    armorType: 'Plate',
    roles: ['Healer'],
    stats: { intellect: 24, stamina: 28, spirit: 18, healingPower: 50, mp5: 6 },
    sockets: ['Blue', 'Yellow'],
    socketBonus: { intellect: 3 },
    instance: 'Tempest Keep',
    boss: 'Void Reaver',
    needsVerification: true,
    notes: 'Tier 5 Holy set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'crystalforge-chestpiece',
    name: 'Crystalforge Chestpiece',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Holy'],
    armorType: 'Plate',
    roles: ['Healer'],
    stats: { intellect: 34, stamina: 38, spirit: 24, healingPower: 68, mp5: 9 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { healingPower: 6 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Tier 5 Holy set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'glorious-gauntlets-of-crestfall',
    name: 'Glorious Gauntlets of Crestfall',
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 24, stamina: 22, spirit: 16, healingPower: 46, mp5: 5 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'girdle-of-fallen-stars',
    name: 'Girdle of Fallen Stars',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 26, stamina: 24, spirit: 18, healingPower: 48 },
    instance: 'Tempest Keep',
    needsVerification: true,
    notes: 'Trash drop; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'boots-of-courage-unending',
    name: 'Boots of Courage Unending',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 22, stamina: 20, spirit: 20, healingPower: 42, mp5: 5 },
    instance: 'Serpentshrine Cavern',
    needsVerification: true,
    notes: 'Trash drop; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'coral-band-of-the-revived',
    name: 'Coral Band of the Revived',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Healer'],
    stats: { intellect: 20, stamina: 18, healingPower: 40, mp5: 5 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'ribbon-of-sacrifice',
    name: 'Ribbon of Sacrifice',
    slot: 'Trinket 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    unique: true,
    roles: ['Healer'],
    stats: { healingPower: 40, mp5: 4 },
    instance: 'Karazhan',
    boss: 'Opera Event',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'blessed-book-of-nagrand',
    name: 'Blessed Book of Nagrand',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Quest',
    phase: 1,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Holy'],
    weaponType: 'Libram',
    armorType: 'Relic',
    roles: ['Healer'],
    stats: { healingPower: 32, mp5: 4 },
    zone: 'Nagrand',
    needsVerification: true,
    notes: 'Holy Paladin relic proof-of-concept row; stats are approximate pending final Wowhead audit.',
  },

  // Protection Paladin Phase 1/2 starter items (see src/domain/bis/protectionPaladinPhase2.ts).
  {
    id: 'crystalforge-faceguard',
    name: 'Crystalforge Faceguard',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 44, defenseRating: 24, dodgeRating: 14, parryRating: 12 },
    sockets: ['Meta', 'Red'],
    socketBonus: { stamina: 4 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Tier 5 Protection set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'justicar-shoulderguards',
    name: 'Justicar Shoulderguards',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 32, defenseRating: 18, dodgeRating: 12 },
    instance: "Gruul's Lair",
    boss: 'High King Maulgar',
    needsVerification: true,
    notes: 'Tier 4 Protection set piece that remains a Phase 2 pick; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'justicar-chestguard',
    name: 'Justicar Chestguard',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 40, defenseRating: 24, dodgeRating: 14, parryRating: 10 },
    instance: "Magtheridon's Lair",
    needsVerification: true,
    notes: 'Tier 4 Protection set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'wristguards-of-determination',
    name: 'Wristguards of Determination',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Tank'],
    stats: { stamina: 28, defenseRating: 20 },
    instance: 'Tempest Keep',
    boss: 'Void Reaver',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'crystalforge-handguards',
    name: 'Crystalforge Handguards',
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 30, defenseRating: 20, hitRating: 10 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { stamina: 3 },
    instance: 'Serpentshrine Cavern',
    boss: 'Leotheras the Blind',
    needsVerification: true,
    notes: 'Tier 5 Protection set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'belt-of-the-guardian',
    name: 'Belt of the Guardian',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    craftedBy: 'Blacksmithing',
    roles: ['Tank'],
    stats: { stamina: 32, defenseRating: 22, dodgeRating: 10 },
    crafting: {
      requiredSkill: 350,
      recipeSource: 'Blacksmithing trainer or BoE world drop pattern (exact source needs final audit).',
      materials: [
        { name: 'Fel Iron Bar', quantity: 6, farmSource: 'Smelted from Fel Iron Ore, mined throughout Hellfire Peninsula/Zangarmarsh.', needsVerification: true },
        { name: 'Adamantite Bar', quantity: 4, farmSource: 'Smelted from Adamantite Ore, mined throughout Outland.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe source and material list are a starter approximation pending final Wowhead audit.',
    },
    needsVerification: true,
    notes: 'Crafted Blacksmithing tank belt; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'crystalforge-legguards',
    name: 'Crystalforge Legguards',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Protection'],
    armorType: 'Plate',
    roles: ['Tank'],
    stats: { stamina: 48, defenseRating: 26, dodgeRating: 16, parryRating: 14 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { stamina: 4 },
    instance: 'Serpentshrine Cavern',
    boss: 'Fathom-Lord Karathress',
    needsVerification: true,
    notes: 'Tier 5 Protection set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'boots-of-the-resilient',
    name: 'Boots of the Resilient',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Tank'],
    stats: { stamina: 30, defenseRating: 20, dodgeRating: 10 },
    instance: 'Tempest Keep',
    boss: 'High Astromancer Solarian',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'the-seal-of-danzalar',
    name: 'The Seal of Danzalar',
    slot: 'Finger 1',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Tank'],
    stats: { stamina: 26, defenseRating: 18, dodgeRating: 10 },
    instance: 'Serpentshrine Cavern',
    boss: 'The Lurker Below',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'ashyens-gift',
    name: "Ashyen's Gift",
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Reputation',
    phase: 2,
    itemLevel: 120,
    unique: true,
    roles: ['Tank'],
    stats: { stamina: 24, defenseRating: 16, parryRating: 8 },
    reputation: 'Cenarion Expedition (Exalted)',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'tome-of-fiery-redemption',
    name: 'Tome of Fiery Redemption',
    slot: 'Trinket 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Tank'],
    stats: { stamina: 22, defenseRating: 20 },
    instance: 'Tempest Keep',
    boss: "Al'ar",
    needsVerification: true,
    notes: 'On-use proc not modeled yet; passive stats only, pending final Wowhead audit.',
  },
  {
    id: 'fang-of-the-leviathan',
    name: 'Fang of the Leviathan',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    weaponType: 'Sword',
    roles: ['Tank'],
    stats: { stamina: 26, defenseRating: 20, blockRating: 10 },
    instance: 'Serpentshrine Cavern',
    boss: 'Leotheras the Blind',
    needsVerification: true,
    notes: 'Weapon type and DPS/speed modeling are approximate pending final Wowhead audit.',
  },
  {
    id: 'libram-of-the-eternal-rest',
    name: 'Libram of the Eternal Rest',
    slot: 'Relic',
    quality: 'Rare',
    source: 'Dungeon',
    phase: 1,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Protection'],
    weaponType: 'Libram',
    armorType: 'Relic',
    roles: ['Tank'],
    stats: { defenseRating: 14 },
    instance: 'Sethekk Halls',
    needsVerification: true,
    notes: 'Protection Paladin relic proof-of-concept row; stats are approximate pending final Wowhead audit.',
  },

  // Retribution Paladin Phase 1/2 starter items (see src/domain/bis/retributionPaladinPhase2.ts).
  {
    id: 'furious-gizmatic-goggles',
    name: 'Furious Gizmatic Goggles',
    slot: 'Head',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    craftedBy: 'Engineering',
    roles: ['Physical DPS'],
    stats: { strength: 30, stamina: 26, critRating: 22, hitRating: 16 },
    crafting: {
      requiredSkill: 350,
      recipeSource: 'Engineering trainer.',
      materials: [
        { name: 'Fel Iron Bar', quantity: 4, farmSource: 'Smelted from Fel Iron Ore, mined throughout Hellfire Peninsula/Zangarmarsh.', needsVerification: true },
        { name: 'Khorium Bar', quantity: 2, farmSource: 'Smelted from Khorium Ore, a rare Outland mining node drop.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe source and material list are a starter approximation pending final Wowhead audit.',
    },
    needsVerification: true,
    notes: 'Crafted Engineering headpiece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'razor-scale-battlecloak',
    name: 'Razor-Scale Battlecloak',
    slot: 'Back',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Physical DPS'],
    stats: { strength: 24, stamina: 20, critRating: 18, hitRating: 14 },
    instance: 'Serpentshrine Cavern',
    boss: 'Morogrim Tidewalker',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'crystalforge-breastplate',
    name: 'Crystalforge Breastplate',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Paladin'],
    allowedSpecs: ['Retribution'],
    armorType: 'Plate',
    roles: ['Physical DPS'],
    stats: { strength: 42, stamina: 40, critRating: 26, hitRating: 20 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { strength: 4 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Tier 5 Retribution set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'shattrath-leggings',
    name: 'Shattrath Leggings',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Quest',
    phase: 2,
    itemLevel: 128,
    roles: ['Physical DPS'],
    stats: { strength: 34, stamina: 32, critRating: 20, hitRating: 16 },
    zone: 'Shattrath City',
    needsVerification: true,
    notes: 'Quest reward legs; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'ancestral-ring-of-conquest',
    name: 'Ancestral Ring of Conquest',
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Physical DPS'],
    stats: { strength: 22, stamina: 20, critRating: 18, hitRating: 14 },
    instance: 'Serpentshrine Cavern',
    boss: 'The Lurker Below',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'lionheart-executioner',
    name: 'Lionheart Executioner',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 141,
    weaponType: 'Sword',
    craftedBy: 'Blacksmithing',
    roles: ['Physical DPS'],
    stats: { strength: 40, stamina: 32, critRating: 24, hitRating: 18 },
    crafting: {
      requiredSkill: 375,
      recipeSource: 'Weaponsmith trainer (Swordsmith specialization).',
      materials: [
        { name: 'Adamantite Bar', quantity: 10, farmSource: 'Smelted from Adamantite Ore, mined throughout Outland.', needsVerification: true },
        { name: 'Primal Might', quantity: 1, farmSource: 'Crafted by an Alchemist (Transmute: Primal Might) from Primal Nether plus one of each other Primal.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe source and material list are a starter approximation pending final Wowhead audit.',
    },
    needsVerification: true,
    notes: 'Crafted two-handed Blacksmithing weapon; weapon DPS/speed modeling is future work.',
  },

  // Holy Priest Phase 1/2 starter items (see src/domain/bis/holyPriestPhase2.ts; Discipline shares this
  // set with different priority rather than a distinct itemization, matching real TBC guide convention).
  {
    id: 'cowl-of-the-avatar',
    name: 'Cowl of the Avatar',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Priest'],
    armorType: 'Cloth',
    roles: ['Healer'],
    stats: { intellect: 30, stamina: 32, spirit: 24, healingPower: 64, mp5: 8 },
    sockets: ['Meta', 'Blue'],
    socketBonus: { mp5: 3 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Tier 5 Holy/Discipline set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'mantle-of-the-avatar',
    name: 'Mantle of the Avatar',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    allowedClasses: ['Priest'],
    armorType: 'Cloth',
    roles: ['Healer'],
    stats: { intellect: 24, stamina: 26, spirit: 20, healingPower: 52, mp5: 6 },
    instance: 'Tempest Keep',
    boss: 'Void Reaver',
    needsVerification: true,
    notes: 'Tier 5 Holy/Discipline set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'vestments-of-the-avatar',
    name: 'Vestments of the Avatar',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Priest'],
    armorType: 'Cloth',
    roles: ['Healer'],
    stats: { intellect: 34, stamina: 38, spirit: 26, healingPower: 70, mp5: 9 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { healingPower: 6 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Tier 5 Holy/Discipline set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'wraps-of-purification',
    name: 'Wraps of Purification',
    slot: 'Wrists',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 20, stamina: 18, spirit: 16, healingPower: 40 },
    instance: 'Serpentshrine Cavern',
    boss: 'Hydross the Unstable',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'gloves-of-the-avatar',
    name: 'Gloves of the Avatar',
    slot: 'Hands',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    allowedClasses: ['Priest'],
    armorType: 'Cloth',
    roles: ['Healer'],
    stats: { intellect: 24, stamina: 22, spirit: 18, healingPower: 48, mp5: 5 },
    sockets: ['Red', 'Yellow'],
    socketBonus: { mp5: 2 },
    instance: 'Serpentshrine Cavern',
    boss: 'Leotheras the Blind',
    needsVerification: true,
    notes: 'Tier 5 Holy/Discipline set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'belt-of-the-long-road',
    name: 'Belt of the Long Road',
    slot: 'Waist',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    craftedBy: 'Tailoring',
    roles: ['Healer'],
    stats: { intellect: 26, stamina: 22, spirit: 20, healingPower: 46, mp5: 6 },
    crafting: {
      requiredSkill: 350,
      recipeSource: 'BoE world drop pattern (exact source needs final audit).',
      materials: [
        { name: 'Primal Mana', quantity: 2, farmSource: 'Dropped by Arcane elementals in Netherstorm.', needsVerification: true },
        { name: 'Bolt of Imbued Netherweave', quantity: 3, farmSource: 'Crafted from Netherweave Cloth plus an Arcane Dust/Primal Mana infusion.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe source and material list are a starter approximation pending final Wowhead audit.',
    },
    needsVerification: true,
    notes: 'Crafted healer belt; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'breeches-of-the-avatar',
    name: 'Breeches of the Avatar',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    allowedClasses: ['Priest'],
    armorType: 'Cloth',
    roles: ['Healer'],
    stats: { intellect: 28, stamina: 30, spirit: 22, healingPower: 58, mp5: 8 },
    sockets: ['Blue', 'Yellow'],
    socketBonus: { mp5: 2 },
    instance: 'Serpentshrine Cavern',
    boss: 'Fathom-Lord Karathress',
    needsVerification: true,
    notes: 'Tier 5 Holy/Discipline set piece; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'soul-strider-boots',
    name: 'Soul-Strider Boots',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Healer'],
    stats: { intellect: 22, stamina: 20, spirit: 18, healingPower: 42, mp5: 5 },
    instance: 'Serpentshrine Cavern',
    boss: 'Fathom-Lord Karathress',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'violet-signet-of-the-grand-restorer',
    name: 'Violet Signet of the Grand Restorer',
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Reputation',
    phase: 1,
    itemLevel: 115,
    unique: true,
    roles: ['Healer'],
    stats: { intellect: 18, stamina: 16, healingPower: 34, mp5: 4 },
    reputation: 'The Violet Eye (Exalted)',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'earring-of-soulful-meditation',
    name: 'Earring of Soulful Meditation',
    slot: 'Trinket 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Healer'],
    stats: { healingPower: 38, mp5: 5 },
    instance: 'Serpentshrine Cavern',
    boss: 'The Lurker Below',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'windcallers-orb',
    name: "Windcaller's Orb",
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Reputation',
    phase: 1,
    itemLevel: 115,
    weaponType: 'Held In Off-hand',
    roles: ['Healer'],
    stats: { intellect: 16, healingPower: 30 },
    reputation: 'Cenarion Expedition (Revered)',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'luminescent-rod-of-the-naaru',
    name: 'Luminescent Rod of the Naaru',
    slot: 'Ranged',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    weaponType: 'Wand',
    roles: ['Healer'],
    stats: { healingPower: 40 },
    instance: 'Serpentshrine Cavern',
    boss: 'Morogrim Tidewalker',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },

  // Shadow Priest Phase 1/2 starter items (see src/domain/bis/shadowPriestPhase2.ts).
  {
    id: 'cowl-of-the-grand-engineer',
    name: 'Cowl of the Grand Engineer',
    slot: 'Head',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Caster DPS'],
    stats: { intellect: 28, stamina: 26, spellPower: 46, spellHitRating: 16 },
    instance: 'Tempest Keep',
    boss: 'Void Reaver',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'ritssyns-lost-pendant',
    name: "Ritssyn's Lost Pendant",
    slot: 'Neck',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    roles: ['Caster DPS'],
    stats: { intellect: 20, spellPower: 32, spellCritRating: 10 },
    instance: 'Karazhan',
    needsVerification: true,
    notes: 'Trash drop; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'frozen-shadoweave-shoulders',
    name: 'Frozen Shadoweave Shoulders',
    slot: 'Shoulders',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    craftedBy: 'Tailoring',
    roles: ['Caster DPS'],
    stats: { intellect: 22, stamina: 20, spellPower: 38, spellHitRating: 14 },
    crafting: {
      requiredSkill: 375,
      recipeSource: 'Tailoring trainer (Shadoweave Tailoring specialization).',
      materials: [
        { name: 'Shadowcloth', quantity: 2, farmSource: 'Crafted sub-recipe from Primal Shadow + Void Crystal + Netherweave Cloth; not purchasable directly.', needsVerification: true },
        { name: 'Primal Shadow', quantity: 2, farmSource: 'Shadow-school elementals/demons in Outland instances; also purchasable from other players via trade/AH.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe source confirmed (Shadoweave specialization); exact material counts are approximate pending final Wowhead audit.',
    },
    needsVerification: true,
    notes: 'Crafted Shadow-specialization Tailoring shoulders; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'royal-cloak-of-the-sunstriders',
    name: 'Royal Cloak of the Sunstriders',
    slot: 'Back',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Caster DPS'],
    stats: { intellect: 20, stamina: 18, spellPower: 34, spellHitRating: 12 },
    instance: 'Tempest Keep',
    boss: "Kael'thas Sunstrider",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'vestments-of-the-sea-witch',
    name: 'Vestments of the Sea-Witch',
    slot: 'Chest',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 133,
    roles: ['Caster DPS'],
    stats: { intellect: 32, stamina: 34, spellPower: 58, spellHitRating: 20 },
    sockets: ['Red', 'Yellow', 'Blue'],
    socketBonus: { spellPower: 5 },
    instance: 'Serpentshrine Cavern',
    boss: 'Lady Vashj',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'trousers-of-the-astromancer',
    name: 'Trousers of the Astromancer',
    slot: 'Legs',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    roles: ['Caster DPS'],
    stats: { intellect: 28, stamina: 26, spellPower: 48, spellHitRating: 16 },
    instance: 'Tempest Keep',
    boss: 'High Astromancer Solarian',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'frozen-shadoweave-boots',
    name: 'Frozen Shadoweave Boots',
    slot: 'Feet',
    quality: 'Epic',
    source: 'Crafted',
    phase: 2,
    itemLevel: 128,
    craftedBy: 'Tailoring',
    roles: ['Caster DPS'],
    stats: { intellect: 20, stamina: 18, spellPower: 34, spellHitRating: 12 },
    crafting: {
      requiredSkill: 375,
      recipeSource: 'Tailoring trainer (Shadoweave Tailoring specialization).',
      materials: [
        { name: 'Shadowcloth', quantity: 2, farmSource: 'Crafted sub-recipe from Primal Shadow + Void Crystal + Netherweave Cloth; not purchasable directly.', needsVerification: true },
      ],
      needsVerification: true,
      notes: 'Recipe source confirmed (Shadoweave specialization); exact material counts are approximate pending final Wowhead audit.',
    },
    needsVerification: true,
    notes: 'Crafted Shadow-specialization Tailoring boots; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'band-of-alar',
    name: "Band of Al'ar",
    slot: 'Finger 2',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    unique: true,
    roles: ['Caster DPS'],
    stats: { intellect: 20, spellPower: 30, spellCritRating: 12 },
    instance: 'Tempest Keep',
    boss: "Al'ar",
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'quagmirrans-eye',
    name: "Quagmirran's Eye",
    slot: 'Trinket 2',
    quality: 'Epic',
    source: 'Heroic Dungeon',
    phase: 1,
    unique: true,
    roles: ['Caster DPS'],
    stats: { spellPower: 28 },
    instance: 'The Slave Pens',
    needsVerification: true,
    notes: 'Proc effect (stacking spell haste on crit) is not modeled yet; passive stats only, pending final Wowhead audit.',
  },
  {
    id: 'nathrezim-mindblade',
    name: 'Nathrezim Mindblade',
    slot: 'Main Hand',
    quality: 'Epic',
    source: 'Raid',
    phase: 1,
    itemLevel: 115,
    weaponType: 'Dagger',
    roles: ['Caster DPS'],
    stats: { intellect: 22, spellPower: 48, spellHitRating: 14 },
    instance: 'Karazhan',
    boss: 'Prince Malchezaar',
    needsVerification: true,
    notes: 'Weapon DPS/speed modeling is future work; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'orb-of-the-soul-eater',
    name: 'Orb of the Soul-Eater',
    slot: 'Off Hand',
    quality: 'Epic',
    source: 'Vendor',
    phase: 1,
    itemLevel: 112,
    weaponType: 'Held In Off-hand',
    roles: ['Caster DPS'],
    stats: { intellect: 14, spellPower: 26 },
    vendor: "G'eras",
    needsVerification: true,
    notes: 'Badge of Justice vendor off-hand (25 badges); stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'wand-of-the-forgotten-star',
    name: 'Wand of the Forgotten Star',
    slot: 'Ranged',
    quality: 'Epic',
    source: 'Raid',
    phase: 2,
    itemLevel: 128,
    weaponType: 'Wand',
    roles: ['Caster DPS'],
    stats: { spellPower: 32 },
    instance: 'Tempest Keep',
    boss: 'High Astromancer Solarian',
    needsVerification: true,
    notes: 'Stats are approximate pending final Wowhead audit.',
  },
]

export function getItemsForSlot(slot: GearSlot) {
  return sampleItems.filter((item) => isItemCompatibleWithGearSlot(item, slot))
}

export function getItemById(id: string) {
  return sampleItems.find((item) => item.id === id)
}
