import { RATING_PER_PERCENT } from '../simulation/combatConstants'
import type { Buff } from './buffTypes'

/**
 * The thirty-three raid buffs of TBC Phase 2.
 *
 * Every number below was read by hand off the Wowhead tooltip of the spell rank named in `spellId`,
 * then cross-checked against wowsims/tbc `sim/core/buffs.go` @3301fca5 — the same commit the item,
 * gem and enchant catalogues come from. Nothing here is inferred. This replaces fourteen entries
 * that were all flagged `needsVerification`, and rightly so: five of them were materially wrong.
 *
 * **Why this was done by hand.** Three automated routes were tried and abandoned before this
 * (recorded in HANDOFF.md), and the tooltips show exactly why: Mana Spring Totem reads "Summons a
 * Mana Spring Totem with 5 health ... that restores 20 mana every 2 seconds", so a parser takes 5,
 * a careful reader takes 20-per-2s and converts it to 50 mp5. The ambiguity is only ambiguous to a
 * regex. What made the by-hand pass tractable was resolving each spell through Wowhead's *listing*
 * page first, which carries rank, level and required class — enough to pick the max rank a raid
 * actually uses and to reject the NPC copies that made id selection ambiguous before.
 *
 * **Where the two sources disagree, the tooltip wins.** wowsims models Blessing of Wisdom at 42 mp5;
 * spells 27142 and 27143 both say "restoring 41 mana every 5 seconds". 41 is used here. That is the
 * only outright conflict — everything else agreed to the digit.
 *
 * **Base ranks, not talented ranks.** Values are the untalented tooltip figure, which is what can be
 * cited. Where a talent or an idol raises it, the improved value is named in `notes` and attributed,
 * rather than being silently baked into a number nobody can check.
 *
 * **Fifteen of the thirty-three carry `notModelled` instead of stats** — threat, maximum health,
 * resistances, damage multipliers, weapon procs and timed cooldowns have nowhere to go in
 * `StatBlock`. They are listed anyway, with their real effect, because a raid planner that silently
 * omits Bloodlust reads as an oversight rather than a stated limit.
 */
export const sampleBuffs: readonly Buff[] = [
  // ---- Warrior ----
  {
    id: 'battle-shout',
    name: 'Battle Shout',
    providedByClass: 'Warrior',
    spellId: 2048,
    roles: ['Physical DPS', 'Tank'],
    stats: { attackPower: 306 },
    notes:
      'Rank 8: "increasing the melee attack power of all party members within 20 yards by 306". Melee only — it does not touch ranged attack power, which is why a Hunter gains nothing here. Commanding Presence 5/5 raises it to 382 (wowsims applies a flat 1.25).',
  },
  {
    id: 'commanding-shout',
    name: 'Commanding Shout',
    providedByClass: 'Warrior',
    spellId: 469,
    extraStats: { Health: 1080 },
    notModelled:
      'Increases maximum health of all party members by 1080. Flat maximum health, which StatBlock has no field for — it carries Stamina, and converting 1080 health into 108 Stamina would be wrong, because Stamina then gets multiplied again by Blessing of Kings and Gift of the Wild.',
    notes: 'Rank 1, the only rank in TBC. Improved Commanding Shout 5/5 raises it to 1350.',
  },

  // ---- Paladin ----
  {
    id: 'blessing-of-might',
    name: 'Greater Blessing of Might',
    providedByClass: 'Paladin',
    spellId: 27141,
    roles: ['Physical DPS', 'Tank'],
    stats: { attackPower: 220, rangedAttackPower: 220 },
    notes:
      'Rank 3: "increasing attack power by 220". The tooltip says attack power without qualification and wowsims applies it to melee and ranged alike, unlike Battle Shout. Improved Blessing of Might 5/5 raises it to 264.',
  },
  {
    id: 'blessing-of-kings',
    name: 'Greater Blessing of Kings',
    providedByClass: 'Paladin',
    spellId: 25898,
    statMultipliers: { strength: 0.1, agility: 0.1, stamina: 0.1, intellect: 0.1, spirit: 0.1 },
    notes:
      '"increasing total stats by 10%". Applied after gear, gems and enchants are totaled and before Attack Power and Spell Power are derived, so the 10% correctly cascades into both.',
  },
  {
    id: 'blessing-of-wisdom',
    name: 'Greater Blessing of Wisdom',
    providedByClass: 'Paladin',
    spellId: 27143,
    roles: ['Caster DPS', 'Healer'],
    stats: { mp5: 41 },
    notes:
      'Rank 3: "restoring 41 mana every 5 seconds". wowsims uses 42; spells 27142 and 27143 both say 41, so 41 is used. Improved Blessing of Wisdom 2/2 raises it by 20%, to 49.',
  },
  {
    id: 'blessing-of-salvation',
    name: 'Greater Blessing of Salvation',
    providedByClass: 'Paladin',
    spellId: 25895,
    roles: ['Physical DPS', 'Caster DPS', 'Healer'],
    notModelled:
      'Reduces all threat generated by 30%. This simulator does not model threat at all, so there is no quantity for it to reduce.',
  },
  {
    id: 'blessing-of-sanctuary',
    name: 'Greater Blessing of Sanctuary',
    providedByClass: 'Paladin',
    spellId: 27169,
    roles: ['Tank'],
    notModelled:
      'Reduces damage dealt from all sources by up to 80, and deals 46 Holy damage to an attacker whose melee attack the target blocks. Flat damage reduction applies after mitigation rather than as a stat, and the block component is a damage proc.',
  },
  {
    id: 'devotion-aura',
    name: 'Devotion Aura',
    providedByClass: 'Paladin',
    spellId: 27149,
    stats: { armor: 861 },
    notes:
      'Rank 8: "Gives 861 additional armor to party members within 30 yards". Improved Devotion Aura 5/5 raises it to 1205. Only one Paladin aura can be active per Paladin, so this and the two below compete for the same slot.',
  },
  {
    id: 'retribution-aura',
    name: 'Retribution Aura',
    providedByClass: 'Paladin',
    spellId: 27150,
    notModelled:
      'Causes 26 Holy damage to any creature that strikes a party member. Damage returned to the attacker, not a stat on the wearer. Improved Retribution Aura 2/2 raises it to 39.',
  },
  {
    id: 'sanctity-aura',
    name: 'Sanctity Aura',
    providedByClass: 'Paladin',
    spellId: 20218,
    notModelled:
      'Increases Holy damage done by party members by 10%. A school-specific damage multiplier, and this simulator applies no school multipliers. Improved Sanctity Aura 2/2 adds a further 2% to damage of all schools.',
  },

  // ---- Mage ----
  {
    id: 'arcane-intellect',
    name: 'Arcane Brilliance',
    providedByClass: 'Mage',
    spellId: 27127,
    roles: ['Caster DPS', 'Healer'],
    stats: { intellect: 40 },
    notes:
      'Rank 2: "increasing their Intellect by 40". Single-target Arcane Intellect (rank 6, spell 27126) gives the same 40 and does not stack with it, so the two are one entry rather than two that could both be ticked. The id predates the rename and is left alone so saved builds keep resolving.',
  },

  // ---- Priest ----
  {
    id: 'prayer-of-fortitude',
    name: 'Prayer of Fortitude',
    providedByClass: 'Priest',
    spellId: 25392,
    stats: { stamina: 79 },
    notes:
      'Rank 3: "increasing their Stamina by 79". Improved Power Word: Fortitude 2/2 raises it to 102.',
  },
  {
    id: 'prayer-of-spirit',
    name: 'Prayer of Spirit',
    providedByClass: 'Priest',
    spellId: 32999,
    roles: ['Caster DPS', 'Healer'],
    stats: { spirit: 50 },
    notes:
      'Rank 2: "increasing their Spirit by 50". Improved Divine Spirit additionally grants spell power equal to 10% of Spirit, which is a stat dependency rather than a flat bonus and is not applied here.',
  },
  {
    id: 'shadow-protection',
    name: 'Shadow Protection',
    providedByClass: 'Priest',
    spellId: 25433,
    extraStats: { ShadowResistance: 70 },
    notModelled:
      "Increases the target's resistance to Shadow spells by 70. StatBlock carries no resistances, and this simulator models no incoming spell damage for them to reduce.",
    notes: 'Rank 4. Prayer of Shadow Protection (rank 2, spell 39374) is the group version.',
  },
  {
    id: 'power-infusion',
    name: 'Power Infusion',
    providedByClass: 'Priest',
    // A 31-point Discipline talent. A Holy or Shadow Priest cannot cast it.
    providedBySpec: 'Discipline',
    spellId: 10060,
    roles: ['Caster DPS', 'Healer'],
    notModelled:
      'Increases spell casting speed by 20% and reduces the mana cost of all spells by 20% for 15 sec, on a 3 min cooldown. A timed cooldown from another player: averaging it over the fight would misstate it in both directions, and the mana half has nothing to act on while healer mana is unconstrained.',
  },

  // ---- Druid ----
  {
    id: 'mark-of-the-wild',
    name: 'Gift of the Wild',
    providedByClass: 'Druid',
    spellId: 26991,
    stats: { strength: 14, agility: 14, stamina: 14, intellect: 14, spirit: 14, armor: 340 },
    extraStats: { ArcaneResistance: 25, FireResistance: 25, FrostResistance: 25, NatureResistance: 25, ShadowResistance: 25 },
    notes:
      'Rank 3: "increasing armor by 340, all attributes by 14 and all resistances by 25". Flat, not a percentage — this entry previously modelled it as +5% to every primary stat, which is not a TBC effect at any rank. Improved Mark of the Wild 5/5 raises it to 18 and 459. The resistances have no home in StatBlock and sit in `extraStats`; the armor does, so it is applied.',
  },
  {
    id: 'thorns',
    name: 'Thorns',
    providedByClass: 'Druid',
    spellId: 26992,
    roles: ['Tank'],
    notModelled:
      'Causes 25 Nature damage to attackers when hit. Damage returned to the attacker, not a stat. Improved Thorns 3/3 raises it to 43.',
  },
  {
    id: 'innervate',
    name: 'Innervate',
    providedByClass: 'Druid',
    spellId: 29166,
    roles: ['Caster DPS', 'Healer'],
    notModelled:
      "Increases the target's Spirit-based mana regeneration by 400% and allows full regeneration while casting, for 20 sec on a 6 min cooldown. A timed mana cooldown, and this simulator does not model mana as a constraint.",
  },
  {
    id: 'leader-of-the-pack',
    name: 'Leader of the Pack',
    providedByClass: 'Druid',
    providedBySpec: 'Feral',
    spellId: 17007,
    roles: ['Physical DPS'],
    stats: { critRating: 5 * RATING_PER_PERCENT.meleeCrit },
    notes:
      '"increases ranged and melee critical chance of all party members within 45 yards by 5%". Stored as the rating that buys 5% at level 70 rather than as a flat 5, because everything downstream reads rating. The previous 34 was neither the percentage nor its rating. Idol of the Raven Goddess adds a further 20 crit rating to the aura.',
  },
  {
    id: 'moonkin-aura',
    name: 'Moonkin Aura',
    providedByClass: 'Druid',
    providedBySpec: 'Balance',
    spellId: 24858,
    roles: ['Caster DPS', 'Healer'],
    stats: { spellCritRating: 5 * RATING_PER_PERCENT.spellCrit },
    notes:
      'Moonkin Form: "all party members within 30 yards have their spell critical chance increased by 5%". Converted to rating at level 70, as with Leader of the Pack. Idol of the Raven Goddess adds a further 20 spell crit rating.',
  },

  // ---- Hunter ----
  {
    id: 'trueshot-aura',
    name: 'Trueshot Aura',
    providedByClass: 'Hunter',
    // A 31-point Marksmanship talent, so a Beast Mastery or Survival Hunter brings none of it.
    providedBySpec: 'Marksmanship',
    spellId: 27066,
    roles: ['Physical DPS'],
    stats: { attackPower: 125, rangedAttackPower: 125 },
    notes:
      'Rank 4: "Increases the attack power of party members within 45 yards by 125". Unqualified attack power, so it applies to ranged as well — the ranged half was missing before, which understated every Hunter.',
  },
  {
    id: 'ferocious-inspiration',
    name: 'Ferocious Inspiration',
    providedByClass: 'Hunter',
    providedBySpec: 'Beast Mastery',
    spellId: 34460,
    roles: ['Physical DPS', 'Caster DPS'],
    notModelled:
      'When the Hunter\'s pet scores a critical hit, all party members have all damage increased by 3% for 10 sec. A whole-damage multiplier gated on someone else\'s pet critting, so it has no fixed uptime to average over.',
  },

  // ---- Shaman ----
  {
    id: 'strength-of-earth-totem',
    name: 'Strength of Earth Totem',
    providedByClass: 'Shaman',
    spellId: 25528,
    roles: ['Physical DPS', 'Tank'],
    stats: { strength: 86 },
    notes:
      'Rank 6: "increases the strength of party members within 20 yards by 86". Two things raise it, and they are commonly confused: Enhancing Totems 2/2 (a talent, +15%) gives 98, and the Cyclone Harness 2-piece — not 4-piece — adds a flat 12 for the same 98 (spell 37223, "Improved Strength of Earth", which is a set bonus despite the name). Both together give 112.',
  },
  {
    id: 'grace-of-air-totem',
    name: 'Grace of Air Totem',
    providedByClass: 'Shaman',
    spellId: 25359,
    roles: ['Physical DPS'],
    stats: { agility: 77 },
    notes:
      'Rank 3, the highest in TBC: "increases the agility of party members within 20 yards by 77". Enhancing Totems 2/2 (+15%) raises it to 88.',
  },
  {
    id: 'mana-spring-totem',
    name: 'Mana Spring Totem',
    providedByClass: 'Shaman',
    spellId: 25570,
    roles: ['Caster DPS', 'Healer'],
    stats: { mp5: 50 },
    notes:
      'Rank 5: "restores 20 mana every 2 seconds", which is 50 per 5 seconds. Restorative Totems 5/5 (a talent, +25%) raises it to 62.5. Separately, the Cyclone Raiment 2-piece adds 3 mana every 2 sec — spell 37210, "Improved Mana Spring Totem", which is a set bonus and not the talent its name suggests.',
  },
  {
    id: 'totem-of-wrath',
    name: 'Totem of Wrath',
    providedByClass: 'Shaman',
    providedBySpec: 'Elemental',
    spellId: 30706,
    roles: ['Caster DPS', 'Healer'],
    stats: {
      spellCritRating: 3 * RATING_PER_PERCENT.spellCrit,
      spellHitRating: 3 * RATING_PER_PERCENT.spellHit,
    },
    notes:
      '"increases the chance to hit and critically strike with spells by 3% for all party members". Both are percentages, converted to rating at level 70. This entry previously read 141 spell power and 60 spell hit; Totem of Wrath grants no spell power in TBC at all.',
  },
  {
    id: 'wrath-of-air-totem',
    name: 'Wrath of Air Totem',
    providedByClass: 'Shaman',
    spellId: 3738,
    roles: ['Caster DPS', 'Healer'],
    stats: { spellPower: 101 },
    notes:
      '"Party members within 20 yards of the totem have their spell damage and healing increased by up to 101". Spell power, not haste — the haste version of this totem is a Wrath of the Lich King change, and this entry previously carried 101 spell haste rating. The 121 that wowsims models as the "improved" value is the Cyclone Regalia 2-piece set bonus, not a talent: spell 37212 is named "Improved Wrath of Air Totem" but is a set bonus granting an additional 20 spell damage.',
  },
  {
    id: 'windfury-totem',
    name: 'Windfury Totem',
    providedByClass: 'Shaman',
    spellId: 25587,
    roles: ['Physical DPS'],
    notModelled:
      'Enchants party members\' main-hand weapons; each hit has a 20% chance of granting the attacker one extra attack with 445 extra attack power. An extra swing rather than a stat, and it is suppressed entirely by any self-applied main-hand imbue.',
  },
  {
    id: 'mana-tide-totem',
    name: 'Mana Tide Totem',
    providedByClass: 'Shaman',
    providedBySpec: 'Restoration',
    spellId: 16190,
    roles: ['Caster DPS', 'Healer'],
    notModelled:
      'Restores 6% of total mana every 3 seconds for 12 sec — 24% in total — on a 5 min cooldown. A timed mana cooldown, and this simulator does not model mana as a constraint.',
  },
  {
    id: 'tranquil-air-totem',
    name: 'Tranquil Air Totem',
    providedByClass: 'Shaman',
    spellId: 25908,
    roles: ['Physical DPS', 'Caster DPS', 'Healer'],
    notModelled:
      'Reduces the threat caused by all party members within 20 yards by 20%. This simulator does not model threat. Shares the air totem slot with Wrath of Air and Grace of Air.',
  },
  {
    id: 'unleashed-rage',
    name: 'Unleashed Rage',
    providedByClass: 'Shaman',
    providedBySpec: 'Enhancement',
    spellId: 30806,
    roles: ['Physical DPS'],
    /*
     * 10% attack power, at the 94.18% uptime a real parse records — 0.1 x 0.9418, rounded to 0.094.
     *
     * **Both of the reasons this was refused have been answered rather than argued away.** The note
     * said it is "a proc with no fixed uptime", which was true until the repo owner supplied a
     * Hydross log measuring that uptime directly; and that an attack-power multiplier "would be
     * applied before attack power is derived from Strength and Agility, so it would multiply only the
     * flat portion from gear", which was also true and is what `statMultipliersAfterConversion`
     * exists to fix.
     *
     * Uptime-weighted rather than applied whole, matching how item procs are priced in this repo. The
     * honest cost of that choice: a fight where the shaman crits early and often runs closer to the
     * full 10%, and this understates it slightly. Understating is the right direction for a number
     * correcting an already-understated model.
     */
    statMultipliersAfterConversion: { attackPower: 0.094 },
    notes:
      "Rank 5: the Shaman's melee critical hits increase all party members' melee attack power by 10% for 10 sec. Modelled at 94.18% uptime, measured from the reference Hydross parse rather than assumed — it is a proc, and before that log there was no defensible number to weight it by.",
  },

  {
    id: 'bloodlust',
    name: 'Bloodlust',
    providedByClass: 'Shaman',
    spellId: 2825,
    notModelled:
      'Increases melee, ranged and spell casting speed by 30% for all party members for 40 sec, on a 10 min cooldown. A raid cooldown rather than a sustained buff: applying 30% haste for the whole fight would overstate it by an order of magnitude, and averaging it over the cooldown understates a burst everyone times deliberately.',
    notes: 'Horde only; the Alliance equivalent is Heroism (spell 32182), identical in every value.',
  },

  // ---- Warlock ----
  {
    id: 'blood-pact',
    name: 'Blood Pact',
    providedByClass: 'Warlock',
    spellId: 27268,
    stats: { stamina: 70 },
    notes:
      "Rank 6: \"Increases party members' Stamina by 70\". Requires the Warlock's Imp to be out. Improved Imp 3/3 raises it to 91.",
  },
]

export function getBuffById(id: string) {
  return sampleBuffs.find((buff) => buff.id === id)
}

/** Buffs this app actually applies to a character's stats. */
export const modelledBuffs = sampleBuffs.filter((buff) => !buff.notModelled)

/** Buffs listed for completeness whose effect has nowhere to go in `StatBlock`. */
export const unmodelledBuffs = sampleBuffs.filter((buff) => buff.notModelled)
