import type { Buff } from './buffTypes'

export const sampleBuffs: readonly Buff[] = [
  {
    id: 'battle-shout',
    name: 'Battle Shout',
    providedBy: 'Warrior',
    roles: ['Physical DPS', 'Tank'],
    stats: { attackPower: 306 },
    needsVerification: true,
    notes: 'Max-rank raid Battle Shout; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'blessing-of-might',
    name: 'Blessing of Might',
    providedBy: 'Paladin',
    roles: ['Physical DPS', 'Tank'],
    stats: { attackPower: 220 },
    needsVerification: true,
    notes: 'Approximate pending final Wowhead audit.',
  },
  {
    id: 'blessing-of-kings',
    name: 'Blessing of Kings',
    providedBy: 'Paladin',
    statMultipliers: { strength: 0.1, agility: 0.1, stamina: 0.1, intellect: 0.1, spirit: 0.1 },
    notes: 'Universal +10% to all five primary stats, applied after gear/gems/enchants are totaled.',
  },
  {
    id: 'blessing-of-wisdom',
    name: 'Blessing of Wisdom',
    providedBy: 'Paladin',
    roles: ['Caster DPS', 'Healer'],
    stats: { mp5: 41 },
    needsVerification: true,
    notes: 'Approximate pending final Wowhead audit.',
  },
  {
    id: 'arcane-intellect',
    name: 'Arcane Intellect',
    providedBy: 'Mage',
    roles: ['Caster DPS', 'Healer'],
    stats: { intellect: 40 },
    needsVerification: true,
    notes: 'Approximate pending final Wowhead audit.',
  },
  {
    id: 'prayer-of-fortitude',
    name: 'Prayer of Fortitude',
    providedBy: 'Priest',
    stats: { stamina: 66 },
    needsVerification: true,
    notes: 'Universal; approximate pending final Wowhead audit.',
  },
  {
    id: 'mark-of-the-wild',
    name: 'Gift of the Wild',
    providedBy: 'Druid',
    statMultipliers: { strength: 0.05, agility: 0.05, stamina: 0.05, intellect: 0.05, spirit: 0.05 },
    needsVerification: true,
    notes: 'Universal small percentage bonus to all five primary stats; also grants resistances (not modeled).',
  },
  {
    id: 'trueshot-aura',
    name: 'Trueshot Aura',
    providedBy: 'Hunter',
    roles: ['Physical DPS'],
    stats: { attackPower: 125 },
    needsVerification: true,
    notes: 'Passive raid-wide aura; approximate pending final Wowhead audit.',
  },
  {
    id: 'leader-of-the-pack',
    name: 'Leader of the Pack',
    providedBy: 'Feral Druid',
    roles: ['Physical DPS'],
    stats: { critRating: 34 },
    needsVerification: true,
    notes: 'Talent-driven raid aura; approximate crit rating conversion pending final Wowhead audit.',
  },
  {
    id: 'strength-of-earth-totem',
    name: 'Strength of Earth Totem',
    providedBy: 'Shaman',
    roles: ['Physical DPS', 'Tank'],
    stats: { strength: 86 },
    needsVerification: true,
    notes: 'Approximate pending final Wowhead audit.',
  },
  {
    id: 'grace-of-air-totem',
    name: 'Grace of Air Totem',
    providedBy: 'Shaman',
    roles: ['Physical DPS'],
    stats: { agility: 77 },
    needsVerification: true,
    notes: 'Approximate pending final Wowhead audit.',
  },
  {
    id: 'totem-of-wrath',
    name: 'Totem of Wrath',
    providedBy: 'Shaman',
    roles: ['Caster DPS', 'Healer'],
    stats: { spellPower: 141, spellHitRating: 60 },
    needsVerification: true,
    notes: 'Spell power scales with totem rank and stacks with Improved variant; approximate pending final Wowhead audit.',
  },
  {
    id: 'wrath-of-air-totem',
    name: 'Wrath of Air Totem',
    providedBy: 'Shaman',
    roles: ['Caster DPS', 'Healer'],
    stats: { spellHasteRating: 101 },
    needsVerification: true,
    notes: 'Approximate spell haste rating conversion pending final Wowhead audit.',
  },
  {
    id: 'moonkin-aura',
    name: 'Moonkin Aura',
    providedBy: 'Balance Druid',
    roles: ['Caster DPS', 'Healer'],
    stats: { spellCritRating: 34 },
    needsVerification: true,
    notes: 'Talent-driven raid aura; approximate crit rating conversion pending final Wowhead audit.',
  },
]

export function getBuffById(id: string) {
  return sampleBuffs.find((buff) => buff.id === id)
}
