import type { RaidBoss } from './raidTypes'

/**
 * `encounterOrder` here is the recommended clear order, not a hard gate: the first five bosses can
 * be killed in any sequence, and only after all five are dead does the ramp to Lady Vashj open.
 *
 * Tier 5 tokens redeem into several different set pieces per class, so the token entries are followed
 * by the specific catalog items they can be traded for. Warlock Tier 5 is the Corruptor Raiment set,
 * but the item catalog currently stores those pieces under the Tier 4 "Voidheart" names — those
 * entries are flagged so the mismatch is visible rather than silently propagated.
 */
export const serpentshrineCavernBosses: readonly RaidBoss[] = [
  {
    id: 'hydross-the-unstable',
    name: 'Hydross the Unstable',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 1,
    mechanics:
      'A two-tank resistance fight. Hydross flips between a frost form and a nature form each time he is dragged across the line in the middle of his platform, and each flip spawns four elemental adds of the opposite type. Both forms stack a Mark debuff on everyone every 15 seconds that only resets on a form change, which is the real timer. The frost tank needs a frost resistance set and the nature tank needs a nature resistance set; running this fight without resistance gear is how it fails.',
    roleNotes: [
      { role: 'Tank', note: 'Two tanks, one in a frost resistance set and one in a nature resistance set — they swap on every form change.' },
      { role: 'Physical DPS', note: 'Spread for Water Tomb in frost phase; the debuff stuns and damages anyone nearby.' },
      { role: 'Healer', note: 'Vile Sludge in nature phase halves the target\'s output and must be cleansed off healers first.' },
    ],
    loot: [
      { itemId: 'band-of-vile-aggression', name: 'Band of Vile Aggression', wowItemId: 33055, dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'blackfathom-warbands', name: 'Blackfathom Warbands', wowItemId: 30047, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'boots-of-the-shifting-nightmare', name: 'Boots of the Shifting Nightmare', wowItemId: 30050, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'brighthelm-of-justice', name: 'Brighthelm of Justice', wowItemId: 30048, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'fathomstone', name: 'Fathomstone', wowItemId: 30049, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'idol-of-the-crescent-goddess', name: 'Idol of the Crescent Goddess', wowItemId: 30051, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'living-root-of-the-wildheart', name: 'Living Root of the Wildheart', wowItemId: 30664, dropType: 'Boss', roles: ['Hybrid'] },
      { name: 'Pattern: Belt of Blasting', wowItemId: 30280, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Deep Shadow', wowItemId: 30302, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Natural Power', wowItemId: 30301, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Black Eagle', wowItemId: 30303, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Long Road', wowItemId: 30281, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Monsoon Belt', wowItemId: 30304, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'pauldrons-of-the-wardancer', name: 'Pauldrons of the Wardancer', wowItemId: 30053, dropType: 'Boss', roles: ['Physical DPS'] },
      { name: 'Plans: Belt of the Guardian', wowItemId: 30321, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Plans: Red Belt of Battle', wowItemId: 30322, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'ranger-generals-chestguard', name: 'Ranger-General\'s Chestguard', wowItemId: 30054, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'ring-of-lethality', name: 'Ring of Lethality', wowItemId: 30052, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'robe-of-hateful-echoes', name: 'Robe of Hateful Echoes', wowItemId: 30056, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'scarab-of-displacement', name: 'Scarab of Displacement', wowItemId: 30629, dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'shoulderpads-of-the-stranger', name: 'Shoulderpads of the Stranger', wowItemId: 30055, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'wraps-of-purification', name: 'Wraps of Purification', wowItemId: 32516, dropType: 'Boss', roles: ['Healer'] },
    ],
  },
  {
    id: 'the-lurker-below',
    name: 'The Lurker Below',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 2,
    mechanics:
      'Summoned by fishing the strange pool in the middle of the platform ring, which needs 300 fishing skill — clear the surrounding platforms first or the pull is unsurvivable. Spout is a rotating water beam that knocks everyone it touches into the water; the standard answer is for the whole raid to jump into the water before it starts and climb back out after. He casts Water Bolt on the raid if nobody is in melee range, so melee never all leave at once. Every two minutes he submerges and spawns Coilfang Ambushers and Guardians that have to be crowd-controlled or focused down.',
    roleNotes: [
      { role: 'Tank', note: 'Three tanks: one on the boss, two on the add packs during each submerge phase.' },
      { role: 'Physical DPS', note: 'Melee must keep someone in range at all times or Water Bolt goes out on the raid.' },
    ],
    loot: [
      { itemId: 'ancestral-ring-of-conquest', name: 'Ancestral Ring of Conquest', wowItemId: 30061, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'boots-of-effortless-striking', name: 'Boots of Effortless Striking', wowItemId: 30060, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'bracers-of-eradication', name: 'Bracers of Eradication', wowItemId: 30057, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'choker-of-animalistic-fury', name: 'Choker of Animalistic Fury', wowItemId: 30059, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'cord-of-screaming-terrors', name: 'Cord of Screaming Terrors', wowItemId: 30064, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'earring-of-soulful-meditation', name: 'Earring of Soulful Meditation', wowItemId: 30665, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'glowing-breastplate-of-truth', name: 'Glowing Breastplate of Truth', wowItemId: 30065, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'grove-bands-of-remulos', name: 'Grove-Bands of Remulos', wowItemId: 30062, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'libram-of-absolute-truth', name: 'Libram of Absolute Truth', wowItemId: 30063, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'mallet-of-the-tides', name: 'Mallet of the Tides', wowItemId: 30058, dropType: 'Boss', roles: ['Healer'] },
      { name: 'Pattern: Belt of Blasting', wowItemId: 30280, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Deep Shadow', wowItemId: 30302, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Natural Power', wowItemId: 30301, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Monsoon Belt', wowItemId: 30304, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'tempest-strider-boots', name: 'Tempest-Strider Boots', wowItemId: 30066, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'the-seal-of-danzalar', name: 'The Seal of Danzalar', wowItemId: 33054, dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'velvet-boots-of-the-guardian', name: 'Velvet Boots of the Guardian', wowItemId: 30067, dropType: 'Boss', roles: ['Caster DPS'] },
    ],
  },
  {
    id: 'leotheras-the-blind',
    name: 'Leotheras the Blind',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 3,
    mechanics:
      'Alternates every 45 seconds between a humanoid form that Whirlwinds and wipes threat afterwards, and a demon form that must be tanked by a warlock in fire resistance gear because of Chaos Blast. In demon form he casts Insidious Whisper on five players, spawning an Inner Demon copy that each of those players has to kill alone within 30 seconds or be permanently mind-controlled. Everyone stops attacking through the Whirlwind and lets the tank rebuild threat afterwards. At 15% both forms split apart and the fight becomes a straight burn.',
    roleNotes: [
      { role: 'Tank', note: 'A warlock tanks the demon form in fire resistance gear; the main tank only handles the humanoid form.' },
      { role: 'Caster DPS', note: 'Kill your own Inner Demon fast — nobody else can help, and a survivor mind-controls you for the rest of the fight.' },
      { role: 'Physical DPS', note: 'Stop damage entirely during Whirlwind; the threat wipe afterwards kills whoever pushed through it.' },
    ],
    loot: [
      { itemId: 'coral-barbed-shoulderpads', name: 'Coral-Barbed Shoulderpads', wowItemId: 30097, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'fang-of-the-leviathan', name: 'Fang of the Leviathan', wowItemId: 30095, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'girdle-of-the-invulnerable', name: 'Girdle of the Invulnerable', wowItemId: 30096, dropType: 'Boss', roles: ['Tank'] },
      { name: 'Gloves of the Vanquished Champion', wowItemId: 30239, dropType: 'Tier Token', needsVerification: true, notes: 'T5 gloves token — Paladin, Priest, Warlock.' },
      { name: 'Gloves of the Vanquished Defender', wowItemId: 30240, dropType: 'Tier Token', needsVerification: true, notes: 'T5 gloves token — Warrior, Priest, Druid.' },
      { name: 'Gloves of the Vanquished Hero', wowItemId: 30241, dropType: 'Tier Token', needsVerification: true, notes: 'T5 gloves token — Hunter, Mage, Rogue, Shaman.' },
      { itemId: 'orca-hide-boots', name: 'Orca-Hide Boots', wowItemId: 30092, dropType: 'Boss', roles: ['Physical DPS'] },
      { name: 'Pattern: Belt of Blasting', wowItemId: 30280, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Deep Shadow', wowItemId: 30302, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Natural Power', wowItemId: 30301, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Black Eagle', wowItemId: 30303, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Long Road', wowItemId: 30281, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Monsoon Belt', wowItemId: 30304, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Plans: Belt of the Guardian', wowItemId: 30321, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Plans: Red Belt of Battle', wowItemId: 30322, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'true-aim-stalker-bands', name: 'True-Aim Stalker Bands', wowItemId: 30091, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'tsunami-talisman', name: 'Tsunami Talisman', wowItemId: 30627, dropType: 'Boss', roles: ['Physical DPS'], notes: 'One of the strongest Phase 2 physical DPS trinkets.' },
      { itemId: 'destroyer-gauntlets', name: 'Destroyer Gauntlets', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Warrior T5 gloves, redeemed from Gloves of the Vanquished Defender.' },
      { itemId: 'crystalforge-handguards', name: 'Crystalforge Handguards', dropType: 'Tier Token', roles: ['Healer'], notes: 'Paladin T5 gloves, redeemed from Gloves of the Vanquished Champion.' },
      { itemId: 'gloves-of-the-avatar', name: 'Gloves of the Avatar', dropType: 'Tier Token', roles: ['Healer'], notes: 'Priest T5 gloves, redeemed from Gloves of the Vanquished Champion or Defender.' },
      { itemId: 'nordrassil-gauntlets', name: 'Nordrassil Gauntlets', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Druid T5 gloves, redeemed from Gloves of the Vanquished Defender.' },
      { itemId: 'rift-stalker-gauntlets', name: 'Rift Stalker Gauntlets', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Hunter T5 gloves, redeemed from Gloves of the Vanquished Hero.' },
      { itemId: 'deathmantle-handguards', name: 'Deathmantle Handguards', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Rogue T5 gloves, redeemed from Gloves of the Vanquished Hero.' },
      { itemId: 'cataclysm-gauntlets', name: 'Cataclysm Gauntlets', wowItemId: 30189, dropType: 'Tier Token', roles: ['Physical DPS', 'Caster DPS', 'Healer'], notes: 'Shaman T5 gloves, redeemed from Gloves of the Vanquished Hero.' },
    ],
  },
  {
    id: 'fathom-lord-karathress',
    name: 'Fathom-Lord Karathress',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 4,
    mechanics:
      'Four separate targets, each on its own tank. Karathress absorbs the abilities of every advisor that dies before him, so the kill order matters more than raw damage: Fathom-Guard Tidalvess first (Spitfire Totem must be killed on sight), then Sharkkis (his pet needs its own tank), then Caribdis (interrupt her heals, and she is pulled to a far corner so her Water Bolt Volley cannot reach the raid). Karathress himself is held above 75% until the advisors are dead, or Blessing of the Tides makes him unkillable.',
    roleNotes: [
      { role: 'Tank', note: 'Four tanks minimum, plus one for Sharkkis\'s pet. Assign every target by name before the pull.' },
      { role: 'Caster DPS', note: 'Caribdis is a caster-group kill and her heals must be interrupted on a rotation.' },
      { role: 'Physical DPS', note: 'Melee sit on Karathress but swap instantly to every Spitfire Totem that Tidalvess drops.' },
    ],
    loot: [
      { itemId: 'bloodsea-brigands-vest', name: 'Bloodsea Brigand\'s Vest', wowItemId: 30101, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'fathom-brooch-of-the-tidewalker', name: 'Fathom-Brooch of the Tidewalker', wowItemId: 30663, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'frayed-tether-of-the-drowned', name: 'Frayed Tether of the Drowned', wowItemId: 30099, dropType: 'Boss', roles: ['Healer'] },
      { name: 'Leggings of the Vanquished Champion', wowItemId: 30245, dropType: 'Tier Token', needsVerification: true, notes: 'T5 leg token — Paladin, Priest, Warlock.' },
      { name: 'Leggings of the Vanquished Defender', wowItemId: 30246, dropType: 'Tier Token', needsVerification: true, notes: 'T5 leg token — Warrior, Priest, Druid.' },
      { name: 'Leggings of the Vanquished Hero', wowItemId: 30247, dropType: 'Tier Token', needsVerification: true, notes: 'T5 leg token — Hunter, Mage, Rogue, Shaman.' },
      { name: 'Pattern: Belt of Blasting', wowItemId: 30280, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Deep Shadow', wowItemId: 30302, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Natural Power', wowItemId: 30301, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Black Eagle', wowItemId: 30303, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Long Road', wowItemId: 30281, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Monsoon Belt', wowItemId: 30304, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Plans: Belt of the Guardian', wowItemId: 30321, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Plans: Red Belt of Battle', wowItemId: 30322, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'sextant-of-unstable-currents', name: 'Sextant of Unstable Currents', wowItemId: 30626, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'soul-strider-boots', name: 'Soul-Strider Boots', wowItemId: 30100, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'world-breaker', name: 'World Breaker', wowItemId: 30090, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'destroyer-greaves', name: 'Destroyer Greaves', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Warrior T5 legs, redeemed from Leggings of the Vanquished Defender.' },
      { itemId: 'destroyer-legguards-tank', name: 'Destroyer Legguards', dropType: 'Tier Token', roles: ['Tank'], notes: 'Warrior T5 tanking legs, redeemed from Leggings of the Vanquished Defender.' },
      { itemId: 'crystalforge-legguards', name: 'Crystalforge Legguards', dropType: 'Tier Token', roles: ['Healer'], notes: 'Paladin T5 legs, redeemed from Leggings of the Vanquished Champion.' },
      { itemId: 'breeches-of-the-avatar', name: 'Breeches of the Avatar', dropType: 'Tier Token', roles: ['Healer'], notes: 'Priest T5 legs, redeemed from Leggings of the Vanquished Champion or Defender.' },
      { itemId: 'leggings-of-tirisfal', name: 'Leggings of Tirisfal', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Mage T5 legs, redeemed from Leggings of the Vanquished Hero.' },
      { itemId: 'rift-stalker-leggings', name: 'Rift Stalker Leggings', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Hunter T5 legs, redeemed from Leggings of the Vanquished Hero.' },
      { itemId: 'deathmantle-legguards', name: 'Deathmantle Legguards', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Rogue T5 legs, redeemed from Leggings of the Vanquished Hero.' },
      { itemId: 'cataclysm-legplates', name: 'Cataclysm Legplates', wowItemId: 30192, dropType: 'Tier Token', roles: ['Physical DPS', 'Caster DPS', 'Healer'], notes: 'Shaman T5 legs, redeemed from Leggings of the Vanquished Hero.' },
      { itemId: 'voidheart-leggings', name: 'Voidheart Leggings', dropType: 'Tier Token', roles: ['Caster DPS'], needsVerification: true, notes: 'Warlock Tier 5 legs redeemed from Leggings of the Vanquished Champion. The catalog records this under the Tier 4 "Voidheart" name; Warlock Tier 5 is the Corruptor Raiment set, so the catalog name needs auditing.' },
    ],
  },
  {
    id: 'morogrim-tidewalker',
    name: 'Morogrim Tidewalker',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 5,
    mechanics:
      'Earthquake damages everyone within 50 yards and spawns two packs of six murlocs from the room entrances; those packs are kited into the boss and AoE\'d down, which is where a paladin off-tank earns their place. Watery Grave teleports random players to the waterfall behind the boss, stuns them, and drops them for fall damage — those players need to be healed back up on arrival. Tidal Wave is a frontal cone, so the boss faces away from the raid. Below 25% the murlocs are replaced by Water Globules that fixate on players and explode on contact, turning the end into a kiting damage race.',
    roleNotes: [
      { role: 'Tank', note: 'Two extra tanks hold the murloc packs at the doorways; paladins handle this best because of consecration threat.' },
      { role: 'Healer', note: 'Players in Watery Grave are teleported away and take fall damage — watch the raid frame, not the room.' },
    ],
    loot: [
      { itemId: 'band-of-the-vigilant', name: 'Band of the Vigilant', wowItemId: 33058, dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'girdle-of-the-tidal-call', name: 'Girdle of the Tidal Call', wowItemId: 30068, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'gnarled-chestpiece-of-the-ancients', name: 'Gnarled Chestpiece of the Ancients', wowItemId: 30075, dropType: 'Boss', roles: ['Hybrid'] },
      { itemId: 'illidari-shoulderpads', name: 'Illidari Shoulderpads', wowItemId: 30079, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'luminescent-rod-of-the-naaru', name: 'Luminescent Rod of the Naaru', wowItemId: 30080, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'mantle-of-the-tireless-tracker', name: 'Mantle of the Tireless Tracker', wowItemId: 30085, dropType: 'Boss', roles: ['Physical DPS'] },
      { name: 'Pattern: Belt of Blasting', wowItemId: 30280, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Deep Shadow', wowItemId: 30302, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Natural Power', wowItemId: 30301, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Black Eagle', wowItemId: 30303, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Long Road', wowItemId: 30281, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Monsoon Belt', wowItemId: 30304, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'pauldrons-of-the-argent-sentinel', name: 'Pauldrons of the Argent Sentinel', wowItemId: 30084, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'pendant-of-the-lost-ages', name: 'Pendant of the Lost Ages', wowItemId: 30008, dropType: 'Boss', roles: ['Healer'] },
      { name: 'Plans: Belt of the Guardian', wowItemId: 30321, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Plans: Red Belt of Battle', wowItemId: 30322, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'razor-scale-battlecloak', name: 'Razor-Scale Battlecloak', wowItemId: 30098, dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'ring-of-sundered-souls', name: 'Ring of Sundered Souls', wowItemId: 30083, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'serpent-coil-braid', name: 'Serpent-Coil Braid', wowItemId: 30720, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'talon-of-azshara', name: 'Talon of Azshara', wowItemId: 30082, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'warboots-of-obliteration', name: 'Warboots of Obliteration', wowItemId: 30081, dropType: 'Boss', roles: ['Physical DPS'] },
    ],
  },
  {
    id: 'lady-vashj',
    name: 'Lady Vashj',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 6,
    mechanics:
      'Three phases and the hardest fight in Serpentshrine Cavern. Phase 1 is a spread-out tank fight — Static Charge chains to anyone nearby and Shock Blast one-shots whoever it lands on. Phase 2 makes her immune and puts the raid on four shield generators: Tainted Elementals drop Tainted Cores that must be hand-passed to the generators, while Coilfang Striders are ranged-tanked and Enchanted Elementals are stopped before they reach her. Phase 3 returns to Phase 1 mechanics plus endlessly spawning Toxic Spore Bats that leave poison clouds, making it a hard soft-enrage.',
    roleNotes: [
      { role: 'Tank', note: 'Threat fully resets entering Phase 3 — do not let a DPS open before the tank has re-established.' },
      { role: 'Physical DPS', note: 'Phase 2 is entirely about the Tainted Core relay; assign core runners in advance and do not improvise.' },
      { role: 'Healer', note: 'Phase 3 spore bat poison stacks on everyone; dispel priority is the tank, then core runners.' },
    ],
    loot: [
      { itemId: 'belt-of-one-hundred-deaths', name: 'Belt of One-Hundred Deaths', wowItemId: 30106, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'cobra-lash-boots', name: 'Cobra-Lash Boots', wowItemId: 30104, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'coral-band-of-the-revived', name: 'Coral Band of the Revived', wowItemId: 30110, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'fang-of-vashj', name: 'Fang of Vashj', wowItemId: 30103, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'glorious-gauntlets-of-crestfall', name: 'Glorious Gauntlets of Crestfall', wowItemId: 30112, dropType: 'Boss', roles: ['Healer'] },
      { name: 'Helm of the Vanquished Champion', wowItemId: 30242, dropType: 'Tier Token', needsVerification: true, notes: 'T5 helm token — Paladin, Priest, Warlock.' },
      { name: 'Helm of the Vanquished Defender', wowItemId: 30243, dropType: 'Tier Token', needsVerification: true, notes: 'T5 helm token — Warrior, Priest, Druid.' },
      { name: 'Helm of the Vanquished Hero', wowItemId: 30244, dropType: 'Tier Token', needsVerification: true, notes: 'T5 helm token — Hunter, Mage, Rogue, Shaman.' },
      { itemId: 'krakken-heart-breastplate', name: 'Krakken-Heart Breastplate', wowItemId: 30102, dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'lightfathom-scepter', name: 'Lightfathom Scepter', wowItemId: 30108, dropType: 'Boss', roles: ['Healer'] },
      { name: 'Nether Vortex', wowItemId: 30183, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Blasting', wowItemId: 30280, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Deep Shadow', wowItemId: 30302, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of Natural Power', wowItemId: 30301, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Black Eagle', wowItemId: 30303, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Belt of the Long Road', wowItemId: 30281, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Pattern: Monsoon Belt', wowItemId: 30304, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Plans: Belt of the Guardian', wowItemId: 30321, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { name: 'Plans: Red Belt of Battle', wowItemId: 30322, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'prism-of-inner-calm', name: 'Prism of Inner Calm', wowItemId: 30621, dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'ring-of-endless-coils', name: 'Ring of Endless Coils', wowItemId: 30109, dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'runetotems-mantle', name: 'Runetotem\'s Mantle', wowItemId: 30111, dropType: 'Boss', roles: ['Healer'] },
      { name: 'Scroll of the Maelstrom', wowItemId: 32895, dropType: 'Boss', needsVerification: true, notes: 'Real drop; not in the item catalogue, so it is listed by name only.' },
      { itemId: 'serpent-spine-longbow', name: 'Serpent Spine Longbow', wowItemId: 30105, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'vestments-of-the-sea-witch', name: 'Vestments of the Sea-Witch', wowItemId: 30107, dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'destroyer-greathelm', name: 'Destroyer Greathelm', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Warrior T5 helm, redeemed from Helm of the Vanquished Defender.' },
      { itemId: 'crystalforge-greathelm', name: 'Crystalforge Greathelm', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Paladin T5 helm, redeemed from Helm of the Vanquished Champion.' },
      { itemId: 'crystalforge-faceguard', name: 'Crystalforge Faceguard', dropType: 'Tier Token', roles: ['Tank'], notes: 'Paladin T5 tanking helm, redeemed from Helm of the Vanquished Champion.' },
      { itemId: 'cowl-of-the-avatar', name: 'Cowl of the Avatar', dropType: 'Tier Token', roles: ['Healer'], notes: 'Priest T5 helm, redeemed from Helm of the Vanquished Champion or Defender.' },
      { itemId: 'nordrassil-headpiece', name: 'Nordrassil Headpiece', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Druid T5 helm, redeemed from Helm of the Vanquished Defender.' },
      { itemId: 'nordrassil-headguard', name: 'Nordrassil Headguard', dropType: 'Tier Token', roles: ['Healer'], notes: 'Druid T5 healing helm, redeemed from Helm of the Vanquished Defender.' },
      { itemId: 'rift-stalker-helm', name: 'Rift Stalker Helm', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Hunter T5 helm, redeemed from Helm of the Vanquished Hero.' },
      { itemId: 'cowl-of-tirisfal', name: 'Cowl of Tirisfal', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Mage T5 helm, redeemed from Helm of the Vanquished Hero.' },
      { itemId: 'deathmantle-helm', name: 'Deathmantle Helm', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Rogue T5 helm, redeemed from Helm of the Vanquished Hero.' },
      { itemId: 'hood-of-the-corruptor', name: 'Hood of the Corruptor', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Warlock Tier 5 helm, redeemed from Helm of the Vanquished Champion.' },
      { name: 'Vashj\'s Vial Remnant', wowItemId: 29906, dropType: 'Quest Reward', notes: 'Quest item for the Mount Hyjal attunement chain, which becomes relevant in Phase 3 rather than Phase 2.' },
    ],
  },
]
