import type { RaidBoss } from './raidTypes'

/**
 * `encounterOrder` here is the recommended clear order, not a hard gate: the first five bosses can
 * be killed in any sequence, and only after all five are dead does the ramp to Lady Vashj open.
 *
 * Tier 5 tokens redeem into several different set pieces per class, so the token entries are followed
 * by the specific catalog items they can be traded for. Warlock Tier 5 is the Corruptor Raiment set,
 * but the item catalog currently stores those pieces under the Tier 4 "Voidheart" names — those
 * entries are flagged so the mismatch is visible rather than silently propagated.
 */
export const serpentshrineCavernBosses: readonly RaidBoss[] = [
  {
    id: 'hydross-the-unstable',
    name: 'Hydross the Unstable',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 1,
    mechanics:
      'A two-tank resistance fight. Hydross flips between a frost form and a nature form each time he is dragged across the line in the middle of his platform, and each flip spawns four elemental adds of the opposite type. Both forms stack a Mark debuff on everyone every 15 seconds that only resets on a form change, which is the real timer. The frost tank needs a frost resistance set and the nature tank needs a nature resistance set; running this fight without resistance gear is how it fails.',
    roleNotes: [
      { role: 'Tank', note: 'Two tanks, one in a frost resistance set and one in a nature resistance set — they swap on every form change.' },
      { role: 'Physical DPS', note: 'Spread for Water Tomb in frost phase; the debuff stuns and damages anyone nearby.' },
      { role: 'Healer', note: 'Vile Sludge in nature phase halves the target\'s output and must be cleansed off healers first.' },
    ],
    loot: [
      { itemId: 'fathomstone', name: 'Fathomstone', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'ring-of-lethality', name: 'Ring of Lethality', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'blackfathom-warbands', name: 'Blackfathom Warbands', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'shoulderpads-of-the-stranger', name: 'Shoulderpads of the Stranger', wowItemId: 30055, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'wraps-of-purification', name: 'Wraps of Purification', dropType: 'Boss', roles: ['Healer'] },
      { name: 'Living Root of the Wildheart', dropType: 'Boss', roles: ['Hybrid'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
      { name: 'Idol of the Crescent Goddess', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
      { name: 'Scarab of Displacement', dropType: 'Boss', roles: ['Tank'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
      { name: 'Band of Vile Aggression', dropType: 'Boss', roles: ['Tank'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
      { name: 'Brighthelm of Justice', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
      { name: 'Pauldrons of the Wardancer', dropType: 'Boss', roles: ['Physical DPS'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
      { name: "Ranger-General's Chestguard", dropType: 'Boss', roles: ['Physical DPS'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
      { name: 'Boots of the Shifting Nightmare', dropType: 'Boss', roles: ['Caster DPS'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
      { name: 'Robe of Hateful Echoes', dropType: 'Boss', roles: ['Caster DPS'], needsVerification: true, notes: 'Real Hydross drop, not yet in the item catalog.' },
    ],
  },
  {
    id: 'the-lurker-below',
    name: 'The Lurker Below',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 2,
    mechanics:
      'Summoned by fishing the strange pool in the middle of the platform ring, which needs 300 fishing skill — clear the surrounding platforms first or the pull is unsurvivable. Spout is a rotating water beam that knocks everyone it touches into the water; the standard answer is for the whole raid to jump into the water before it starts and climb back out after. He casts Water Bolt on the raid if nobody is in melee range, so melee never all leave at once. Every two minutes he submerges and spawns Coilfang Ambushers and Guardians that have to be crowd-controlled or focused down.',
    roleNotes: [
      { role: 'Tank', note: 'Three tanks: one on the boss, two on the add packs during each submerge phase.' },
      { role: 'Physical DPS', note: 'Melee must keep someone in range at all times or Water Bolt goes out on the raid.' },
    ],
    loot: [
      { itemId: 'earring-of-soulful-meditation', name: 'Earring of Soulful Meditation', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'choker-of-animalistic-fury', name: 'Choker of Animalistic Fury', wowItemId: 29381, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'ancestral-ring-of-conquest', name: 'Ancestral Ring of Conquest', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'the-seal-of-danzalar', name: 'The Seal of Danzalar', dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'bracers-of-eradication', name: 'Bracers of Eradication', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'grove-bands-of-remulos', name: 'Grove-Bands of Remulos', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'velvet-boots-of-the-guardian', name: 'Velvet Boots of the Guardian', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'mallet-of-the-tides', name: 'Mallet of the Tides', dropType: 'Boss', roles: ['Healer'] },
      { name: 'Libram of Absolute Truth', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Lurker drop, not yet in the item catalog.' },
      { name: 'Glowing Breastplate of Truth', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Lurker drop, not yet in the item catalog.' },
      { name: 'Tempest-Strider Boots', dropType: 'Boss', roles: ['Caster DPS'], needsVerification: true, notes: 'Real Lurker drop, not yet in the item catalog.' },
      { name: 'Boots of Effortless Striking', dropType: 'Boss', roles: ['Physical DPS'], needsVerification: true, notes: 'Real Lurker drop, not yet in the item catalog.' },
      { name: 'Cord of Screaming Terrors', dropType: 'Boss', roles: ['Caster DPS'], needsVerification: true, notes: 'Real Lurker drop, not yet in the item catalog.' },
    ],
  },
  {
    id: 'leotheras-the-blind',
    name: 'Leotheras the Blind',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 3,
    mechanics:
      'Alternates every 45 seconds between a humanoid form that Whirlwinds and wipes threat afterwards, and a demon form that must be tanked by a warlock in fire resistance gear because of Chaos Blast. In demon form he casts Insidious Whisper on five players, spawning an Inner Demon copy that each of those players has to kill alone within 30 seconds or be permanently mind-controlled. Everyone stops attacking through the Whirlwind and lets the tank rebuild threat afterwards. At 15% both forms split apart and the fight becomes a straight burn.',
    roleNotes: [
      { role: 'Tank', note: 'A warlock tanks the demon form in fire resistance gear; the main tank only handles the humanoid form.' },
      { role: 'Caster DPS', note: 'Kill your own Inner Demon fast — nobody else can help, and a survivor mind-controls you for the rest of the fight.' },
      { role: 'Physical DPS', note: 'Stop damage entirely during Whirlwind; the threat wipe afterwards kills whoever pushed through it.' },
    ],
    loot: [
      { name: 'Gloves of the Vanquished Champion', dropType: 'Tier Token', notes: 'T5 gloves token — Paladin, Priest, Warlock.' },
      { name: 'Gloves of the Vanquished Defender', dropType: 'Tier Token', notes: 'T5 gloves token — Warrior, Priest, Druid.' },
      { name: 'Gloves of the Vanquished Hero', dropType: 'Tier Token', notes: 'T5 gloves token — Hunter, Mage, Rogue, Shaman.' },
      { itemId: 'destroyer-gauntlets', name: 'Destroyer Gauntlets', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Warrior T5 gloves, redeemed from Gloves of the Vanquished Defender.' },
      { itemId: 'crystalforge-handguards', name: 'Crystalforge Handguards', dropType: 'Tier Token', roles: ['Healer'], notes: 'Paladin T5 gloves, redeemed from Gloves of the Vanquished Champion.' },
      { itemId: 'gloves-of-the-avatar', name: 'Gloves of the Avatar', dropType: 'Tier Token', roles: ['Healer'], notes: 'Priest T5 gloves, redeemed from Gloves of the Vanquished Champion or Defender.' },
      { itemId: 'nordrassil-gauntlets', name: 'Nordrassil Gauntlets', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Druid T5 gloves, redeemed from Gloves of the Vanquished Defender.' },
      { itemId: 'rift-stalker-gauntlets', name: 'Rift Stalker Gauntlets', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Hunter T5 gloves, redeemed from Gloves of the Vanquished Hero.' },
      { itemId: 'deathmantle-handguards', name: 'Deathmantle Handguards', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Rogue T5 gloves, redeemed from Gloves of the Vanquished Hero.' },
      { itemId: 'cataclysm-gauntlets', name: 'Cataclysm Gauntlets', wowItemId: 30189, dropType: 'Tier Token', roles: ['Physical DPS', 'Caster DPS', 'Healer'], notes: 'Shaman T5 gloves, redeemed from Gloves of the Vanquished Hero.' },
      { itemId: 'tsunami-talisman', name: 'Tsunami Talisman', wowItemId: 30627, dropType: 'Boss', roles: ['Physical DPS'], notes: 'One of the strongest Phase 2 physical DPS trinkets.' },
      { itemId: 'fang-of-the-leviathan', name: 'Fang of the Leviathan', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'true-aim-stalker-bands', name: 'True-Aim Stalker Bands', wowItemId: 30091, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'orca-hide-boots', name: 'Orca-Hide Boots', dropType: 'Boss', roles: ['Physical DPS'] },
      { name: 'Girdle of the Invulnerable', dropType: 'Boss', roles: ['Tank'], needsVerification: true, notes: 'Real Leotheras drop, not yet in the item catalog.' },
      { name: 'Coral-Barbed Shoulderpads', dropType: 'Boss', roles: ['Physical DPS'], needsVerification: true, notes: 'Real Leotheras drop, not yet in the item catalog.' },
    ],
  },
  {
    id: 'fathom-lord-karathress',
    name: 'Fathom-Lord Karathress',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 4,
    mechanics:
      'Four separate targets, each on its own tank. Karathress absorbs the abilities of every advisor that dies before him, so the kill order matters more than raw damage: Fathom-Guard Tidalvess first (Spitfire Totem must be killed on sight), then Sharkkis (his pet needs its own tank), then Caribdis (interrupt her heals, and she is pulled to a far corner so her Water Bolt Volley cannot reach the raid). Karathress himself is held above 75% until the advisors are dead, or Blessing of the Tides makes him unkillable.',
    roleNotes: [
      { role: 'Tank', note: 'Four tanks minimum, plus one for Sharkkis\'s pet. Assign every target by name before the pull.' },
      { role: 'Caster DPS', note: 'Caribdis is a caster-group kill and her heals must be interrupted on a rotation.' },
      { role: 'Physical DPS', note: 'Melee sit on Karathress but swap instantly to every Spitfire Totem that Tidalvess drops.' },
    ],
    loot: [
      { name: 'Leggings of the Vanquished Champion', dropType: 'Tier Token', notes: 'T5 leg token — Paladin, Priest, Warlock.' },
      { name: 'Leggings of the Vanquished Defender', dropType: 'Tier Token', notes: 'T5 leg token — Warrior, Priest, Druid.' },
      { name: 'Leggings of the Vanquished Hero', dropType: 'Tier Token', notes: 'T5 leg token — Hunter, Mage, Rogue, Shaman.' },
      { itemId: 'destroyer-greaves', name: 'Destroyer Greaves', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Warrior T5 legs, redeemed from Leggings of the Vanquished Defender.' },
      { itemId: 'destroyer-legguards-tank', name: 'Destroyer Legguards', dropType: 'Tier Token', roles: ['Tank'], notes: 'Warrior T5 tanking legs, redeemed from Leggings of the Vanquished Defender.' },
      { itemId: 'crystalforge-legguards', name: 'Crystalforge Legguards', dropType: 'Tier Token', roles: ['Healer'], notes: 'Paladin T5 legs, redeemed from Leggings of the Vanquished Champion.' },
      { itemId: 'breeches-of-the-avatar', name: 'Breeches of the Avatar', dropType: 'Tier Token', roles: ['Healer'], notes: 'Priest T5 legs, redeemed from Leggings of the Vanquished Champion or Defender.' },
      { itemId: 'leggings-of-tirisfal', name: 'Leggings of Tirisfal', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Mage T5 legs, redeemed from Leggings of the Vanquished Hero.' },
      { itemId: 'rift-stalker-leggings', name: 'Rift Stalker Leggings', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Hunter T5 legs, redeemed from Leggings of the Vanquished Hero.' },
      { itemId: 'deathmantle-legguards', name: 'Deathmantle Legguards', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Rogue T5 legs, redeemed from Leggings of the Vanquished Hero.' },
      { itemId: 'cataclysm-legplates', name: 'Cataclysm Legplates', wowItemId: 30192, dropType: 'Tier Token', roles: ['Physical DPS', 'Caster DPS', 'Healer'], notes: 'Shaman T5 legs, redeemed from Leggings of the Vanquished Hero.' },
      {
        itemId: 'voidheart-leggings',
        name: 'Voidheart Leggings',
        dropType: 'Tier Token',
        roles: ['Caster DPS'],
        needsVerification: true,
        notes: 'Warlock Tier 5 legs redeemed from Leggings of the Vanquished Champion. The catalog records this under the Tier 4 "Voidheart" name; Warlock Tier 5 is the Corruptor Raiment set, so the catalog name needs auditing.',
      },
      { itemId: 'sextant-of-unstable-currents', name: 'Sextant of Unstable Currents', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'bloodsea-brigands-vest', name: "Bloodsea Brigand's Vest", dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'soul-strider-boots', name: 'Soul-Strider Boots', dropType: 'Boss', roles: ['Healer'] },
      { name: 'World Breaker', dropType: 'Boss', roles: ['Physical DPS'], needsVerification: true, notes: 'Real Karathress drop, not yet in the item catalog.' },
      { name: 'Fathom-Brooch of the Tidewalker', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Karathress drop, not yet in the item catalog.' },
      { name: 'Frayed Tether of the Drowned', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Karathress drop, not yet in the item catalog.' },
    ],
  },
  {
    id: 'morogrim-tidewalker',
    name: 'Morogrim Tidewalker',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 5,
    mechanics:
      'Earthquake damages everyone within 50 yards and spawns two packs of six murlocs from the room entrances; those packs are kited into the boss and AoE\'d down, which is where a paladin off-tank earns their place. Watery Grave teleports random players to the waterfall behind the boss, stuns them, and drops them for fall damage — those players need to be healed back up on arrival. Tidal Wave is a frontal cone, so the boss faces away from the raid. Below 25% the murlocs are replaced by Water Globules that fixate on players and explode on contact, turning the end into a kiting damage race.',
    roleNotes: [
      { role: 'Tank', note: 'Two extra tanks hold the murloc packs at the doorways; paladins handle this best because of consecration threat.' },
      { role: 'Healer', note: 'Players in Watery Grave are teleported away and take fall damage — watch the raid frame, not the room.' },
    ],
    loot: [
      { itemId: 'talon-of-azshara', name: 'Talon of Azshara', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'serpent-coil-braid', name: 'Serpent-Coil Braid', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'luminescent-rod-of-the-naaru', name: 'Luminescent Rod of the Naaru', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'ring-of-sundered-souls', name: 'Ring of Sundered Souls', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'razor-scale-battlecloak', name: 'Razor-Scale Battlecloak', dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'warboots-of-obliteration', name: 'Warboots of Obliteration', dropType: 'Boss', roles: ['Physical DPS'] },
      { name: 'Pendant of the Lost Ages', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Morogrim drop, not yet in the item catalog.' },
      { name: 'Band of the Vigilant', dropType: 'Boss', roles: ['Tank'], needsVerification: true, notes: 'Real Morogrim drop, not yet in the item catalog.' },
      { name: 'Pauldrons of the Argent Sentinel', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Morogrim drop, not yet in the item catalog.' },
      { name: 'Mantle of the Tireless Tracker', dropType: 'Boss', roles: ['Physical DPS'], needsVerification: true, notes: 'Real Morogrim drop, not yet in the item catalog.' },
      { name: 'Girdle of the Tidal Call', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Morogrim drop, not yet in the item catalog.' },
      { name: 'Gnarled Chestpiece of the Ancients', dropType: 'Boss', roles: ['Hybrid'], needsVerification: true, notes: 'Real Morogrim drop, not yet in the item catalog.' },
      { name: 'Illidari Shoulderpads', dropType: 'Boss', roles: ['Physical DPS'], needsVerification: true, notes: 'Real Morogrim drop, not yet in the item catalog.' },
    ],
  },
  {
    id: 'lady-vashj',
    name: 'Lady Vashj',
    raidId: 'serpentshrine-cavern',
    encounterOrder: 6,
    mechanics:
      'Three phases and the hardest fight in Serpentshrine Cavern. Phase 1 is a spread-out tank fight — Static Charge chains to anyone nearby and Shock Blast one-shots whoever it lands on. Phase 2 makes her immune and puts the raid on four shield generators: Tainted Elementals drop Tainted Cores that must be hand-passed to the generators, while Coilfang Striders are ranged-tanked and Enchanted Elementals are stopped before they reach her. Phase 3 returns to Phase 1 mechanics plus endlessly spawning Toxic Spore Bats that leave poison clouds, making it a hard soft-enrage.',
    roleNotes: [
      { role: 'Tank', note: 'Threat fully resets entering Phase 3 — do not let a DPS open before the tank has re-established.' },
      { role: 'Physical DPS', note: 'Phase 2 is entirely about the Tainted Core relay; assign core runners in advance and do not improvise.' },
      { role: 'Healer', note: 'Phase 3 spore bat poison stacks on everyone; dispel priority is the tank, then core runners.' },
    ],
    loot: [
      { name: 'Helm of the Vanquished Champion', dropType: 'Tier Token', notes: 'T5 helm token — Paladin, Priest, Warlock.' },
      { name: 'Helm of the Vanquished Defender', dropType: 'Tier Token', notes: 'T5 helm token — Warrior, Priest, Druid.' },
      { name: 'Helm of the Vanquished Hero', dropType: 'Tier Token', notes: 'T5 helm token — Hunter, Mage, Rogue, Shaman.' },
      { itemId: 'destroyer-greathelm', name: 'Destroyer Greathelm', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Warrior T5 helm, redeemed from Helm of the Vanquished Defender.' },
      { itemId: 'crystalforge-greathelm', name: 'Crystalforge Greathelm', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Paladin T5 helm, redeemed from Helm of the Vanquished Champion.' },
      { itemId: 'crystalforge-faceguard', name: 'Crystalforge Faceguard', dropType: 'Tier Token', roles: ['Tank'], notes: 'Paladin T5 tanking helm, redeemed from Helm of the Vanquished Champion.' },
      { itemId: 'cowl-of-the-avatar', name: 'Cowl of the Avatar', dropType: 'Tier Token', roles: ['Healer'], notes: 'Priest T5 helm, redeemed from Helm of the Vanquished Champion or Defender.' },
      { itemId: 'nordrassil-headpiece', name: 'Nordrassil Headpiece', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Druid T5 helm, redeemed from Helm of the Vanquished Defender.' },
      { itemId: 'nordrassil-headguard', name: 'Nordrassil Headguard', dropType: 'Tier Token', roles: ['Healer'], notes: 'Druid T5 healing helm, redeemed from Helm of the Vanquished Defender.' },
      { itemId: 'rift-stalker-helm', name: 'Rift Stalker Helm', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Hunter T5 helm, redeemed from Helm of the Vanquished Hero.' },
      { itemId: 'cowl-of-tirisfal', name: 'Cowl of Tirisfal', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Mage T5 helm, redeemed from Helm of the Vanquished Hero.' },
      { itemId: 'deathmantle-helm', name: 'Deathmantle Helm', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Rogue T5 helm, redeemed from Helm of the Vanquished Hero.' },
      {
        itemId: 'voidheart-cover',
        name: 'Voidheart Cover',
        dropType: 'Tier Token',
        roles: ['Caster DPS'],
        needsVerification: true,
        notes: 'Warlock Tier 5 helm redeemed from Helm of the Vanquished Champion. The catalog records this under the Tier 4 "Voidheart" name; Warlock Tier 5 is the Corruptor Raiment set, so the catalog name needs auditing.',
      },
      { itemId: 'fang-of-vashj', name: 'Fang of Vashj', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'lightfathom-scepter', name: 'Lightfathom Scepter', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'belt-of-one-hundred-deaths', name: 'Belt of One-Hundred Deaths', wowItemId: 30106, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'glorious-gauntlets-of-crestfall', name: 'Glorious Gauntlets of Crestfall', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'cobra-lash-boots', name: 'Cobra-Lash Boots', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'ring-of-endless-coils', name: 'Ring of Endless Coils', dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'coral-band-of-the-revived', name: 'Coral Band of the Revived', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'vestments-of-the-sea-witch', name: 'Vestments of the Sea-Witch', dropType: 'Boss', roles: ['Caster DPS'] },
      { name: 'Serpent Spine Longbow', dropType: 'Boss', roles: ['Physical DPS'], needsVerification: true, notes: 'Real Vashj drop and a Phase 2 chase item for hunters; not yet in the item catalog.' },
      { name: 'Prism of Inner Calm', dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Vashj drop, not yet in the item catalog.' },
      { name: 'Krakken-Heart Breastplate', dropType: 'Boss', roles: ['Tank'], needsVerification: true, notes: 'Real Vashj drop, not yet in the item catalog.' },
      { name: "Runetotem's Mantle", dropType: 'Boss', roles: ['Healer'], needsVerification: true, notes: 'Real Vashj drop, not yet in the item catalog.' },
      { name: "Vashj's Vial Remnant", dropType: 'Quest Reward', notes: 'Quest item for the Mount Hyjal attunement chain, which becomes relevant in Phase 3 rather than Phase 2.' },
    ],
  },
]
