import type { RaidBoss } from './raidTypes'

/**
 * Four encounters. Void Reaver, Solarian, and Al'ar can be taken in any order; Kael'thas is gated
 * behind all three. Tier 5 shoulder and chest tokens both live here, so a full T5 set needs
 * Serpentshrine Cavern as well.
 *
 * Several entries flag mismatches with `src/domain/gear/sampleItems.ts` rather than silently
 * following it — the catalog attributes a handful of these items to the wrong boss or instance.
 */
export const tempestKeepBosses: readonly RaidBoss[] = [
  {
    id: 'alar',
    name: "Al'ar",
    raidId: 'tempest-keep',
    encounterOrder: 1,
    mechanics:
      'Phase 1 has Al\'ar cycling clockwise between four platforms every 30 seconds, dropping a Phoenix Hawk add on each move; a tank per platform picks the boss up as it lands and melee kill the adds. Flame Quills fires from the centre and forces the whole raid to run to the outer ring. Phase 2 begins at 0% health in Phase 1 — the boss lands in the middle, applies a stacking Melt Armor to the tank that forces swaps, Dive Bombs a random spot leaving a fire patch and an Ember of Al\'ar, and Charges random players. Ranged damage carries this fight; melee spend most of Phase 1 on adds.',
    roleNotes: [
      { role: 'Tank', note: 'Four platform tanks in Phase 1, then a two-tank Melt Armor swap in Phase 2.' },
      { role: 'Physical DPS', note: 'Melee handle the Phoenix Hawks in Phase 1; someone must stay in melee range or Flame Buffet hits the raid.' },
    ],
    loot: [
      { itemId: 'phoenix-wing-cloak', name: 'Phoenix-Wing Cloak', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'phoenix-ring-of-rebirth', name: 'Phoenix-Ring of Rebirth', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'band-of-alar', name: "Band of Al'ar", dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'tome-of-fiery-redemption', name: 'Tome of Fiery Redemption', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'gloves-of-the-searing-grip', name: 'Gloves of the Searing Grip', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'mindstorm-wristbands', name: 'Mindstorm Wristbands', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'claw-of-the-phoenix', name: 'Claw of the Phoenix', wowItemId: 29948, dropType: 'Boss', roles: ['Physical DPS'] },
      {
        itemId: 'talon-of-the-phoenix',
        name: 'Talon of the Phoenix',
        dropType: 'Boss',
        roles: ['Physical DPS'],
        needsVerification: true,
        notes: "Sources place this on Al'ar, but the item catalog records it as a Kael'thas Sunstrider drop with wowItemId 32944. Both the boss and the item id on the catalog entry need re-checking.",
      },
      {
        itemId: 'arcanite-steam-pistol',
        name: 'Arcanite Steam-Pistol',
        wowItemId: 29949,
        dropType: 'Boss',
        roles: ['Physical DPS'],
        needsVerification: true,
        notes: "Sources place this on Al'ar in The Eye, but the item catalog records it as a Serpentshrine Cavern drop. The catalog entry needs correcting.",
      },
      { itemId: 'talon-of-alar', name: "Talon of Al'ar", dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'fire-crest-breastplate', name: 'Fire Crest Breastplate', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'netherbane', name: 'Netherbane', dropType: 'Boss', roles: ['Tank'] },
    ],
  },
  {
    id: 'void-reaver',
    name: 'Void Reaver',
    raidId: 'tempest-keep',
    encounterOrder: 2,
    mechanics:
      'Mechanically the simplest boss in Tier 5 and famous for gearing raids fast. Knock Away throws the tank back and wipes their threat entirely, so tanks rotate and everyone else keeps threat well under the cap. Pounding is a channelled AoE that hits everything in melee range and is the main healing load. Arcane Orb launches a slow-moving orb at a random ranged player that silences and damages on contact — ranged spread out and simply walk around it.',
    roleNotes: [
      { role: 'Tank', note: 'Threat is fully wiped by Knock Away; plan a tank rotation rather than trying to out-threat it.' },
      { role: 'Caster DPS', note: 'Stay at least 18 yards out and side-step Arcane Orbs; a silence at the wrong moment is the usual cause of deaths.' },
      { role: 'Healer', note: 'Pounding is predictable raid damage on melee — pre-cast into it rather than reacting.' },
    ],
    loot: [
      { wowItemId: 30248, name: 'Pauldrons of the Vanquished Champion', dropType: 'Tier Token', notes: 'T5 shoulder token — Paladin, Priest, Warlock.' },
      { wowItemId: 30249, name: 'Pauldrons of the Vanquished Defender', dropType: 'Tier Token', notes: 'T5 shoulder token — Warrior, Priest, Druid.' },
      { wowItemId: 30250, name: 'Pauldrons of the Vanquished Hero', dropType: 'Tier Token', notes: 'T5 shoulder token — Hunter, Mage, Rogue, Shaman.' },
      { itemId: 'destroyer-shoulderblades', name: 'Destroyer Shoulderblades', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Warrior T5 shoulders, redeemed from Pauldrons of the Vanquished Defender.' },
      { itemId: 'destroyer-shoulderguards-tank', name: 'Destroyer Shoulderguards', dropType: 'Tier Token', roles: ['Tank'], notes: 'Warrior T5 tanking shoulders, redeemed from Pauldrons of the Vanquished Defender.' },
      { itemId: 'crystalforge-pauldrons', name: 'Crystalforge Pauldrons', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Paladin T5 shoulders, redeemed from Pauldrons of the Vanquished Champion.' },
      { itemId: 'mantle-of-the-avatar', name: 'Mantle of the Avatar', dropType: 'Tier Token', roles: ['Healer'], notes: 'Priest T5 shoulders, redeemed from Pauldrons of the Vanquished Champion or Defender.' },
      { itemId: 'nordrassil-wrath-mantle', name: 'Nordrassil Wrath-Mantle', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Druid T5 shoulders, redeemed from Pauldrons of the Vanquished Defender.' },
      { itemId: 'nordrassil-life-mantle', name: 'Nordrassil Life-Mantle', dropType: 'Tier Token', roles: ['Healer'], notes: 'Druid T5 healing shoulders, redeemed from Pauldrons of the Vanquished Defender.' },
      { itemId: 'rift-stalker-mantle', name: 'Rift Stalker Mantle', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Hunter T5 shoulders, redeemed from Pauldrons of the Vanquished Hero.' },
      { itemId: 'mantle-of-tirisfal', name: 'Mantle of Tirisfal', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Mage T5 shoulders, redeemed from Pauldrons of the Vanquished Hero.' },
      { itemId: 'deathmantle-shoulderpads', name: 'Deathmantle Shoulderpads', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Rogue T5 shoulders, redeemed from Pauldrons of the Vanquished Hero.' },
      { itemId: 'cataclysm-shoulderplates', name: 'Cataclysm Shoulderplates', wowItemId: 30194, dropType: 'Tier Token', roles: ['Physical DPS', 'Caster DPS', 'Healer'], notes: 'Shaman T5 shoulders, redeemed from Pauldrons of the Vanquished Hero.' },
      { itemId: 'warp-spring-coil', name: 'Warp-Spring Coil', wowItemId: 30450, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'cowl-of-the-grand-engineer', name: 'Cowl of the Grand Engineer', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'wristguards-of-determination', name: 'Wristguards of Determination', dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'fel-reavers-piston', name: "Fel Reaver's Piston", dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'girdle-of-zaetar', name: 'Girdle of Zaetar', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'void-reaver-greaves', name: 'Void Reaver Greaves', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'fel-steel-warhelm', name: 'Fel-Steel Warhelm', dropType: 'Boss', roles: ['Tank'] },
    ],
  },
  {
    id: 'high-astromancer-solarian',
    name: 'High Astromancer Solarian',
    raidId: 'tempest-keep',
    encounterOrder: 3,
    mechanics:
      'Three phases on a fixed timer. In Phase 1 she has no threat table and fires Arcane Missiles at random players, and Wrath of the Astromancer puts a bomb on someone who must run at least 20 yards clear before it detonates and knocks the raid around. Phase 2 spawns Solarium Agents from three portals plus Solarium Priests, which are stunned and interrupted and die first. At 20% she becomes a large Void Walker with Void Bolt and Psychic Scream — Fear Ward on the tank and a Tremor Totem down make the last phase manageable.',
    roleNotes: [
      { role: 'Tank', note: 'Fear in the final phase will drag you into the room; keep Fear Ward or a Tremor Totem covering you.' },
      { role: 'Caster DPS', note: 'Wrath of the Astromancer means run out, immediately, every time — the knockback wipes clumped raids.' },
    ],
    loot: [
      { itemId: 'wand-of-the-forgotten-star', name: 'Wand of the Forgotten Star', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'heartrazor', name: 'Heartrazor', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'trousers-of-the-astromancer', name: 'Trousers of the Astromancer', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'worldstorm-gauntlets', name: 'Worldstorm Gauntlets', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'boots-of-the-resilient', name: 'Boots of the Resilient', dropType: 'Boss', roles: ['Healer'] },
      {
        itemId: 'vambraces-of-ending',
        name: 'Vambraces of Ending',
        wowItemId: 29966,
        dropType: 'Boss',
        roles: ['Physical DPS'],
        needsVerification: true,
        notes: 'Sources place this on High Astromancer Solarian as item 29966, but the item catalog records it as a Phase 1 Karazhan drop with wowItemId 28514. The catalog entry needs correcting.',
      },
      { itemId: 'void-star-talisman', name: 'Void Star Talisman', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'solarians-sapphire', name: "Solarian's Sapphire", dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'ethereum-life-staff', name: 'Ethereum Life-Staff', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'star-soul-breeches', name: 'Star-Soul Breeches', dropType: 'Boss', roles: ['Healer'] },
      { itemId: 'star-strider-boots', name: 'Star-Strider Boots', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'greaves-of-the-bloodwarder', name: 'Greaves of the Bloodwarder', dropType: 'Boss', roles: ['Tank'] },
      { itemId: 'girdle-of-the-righteous-path', name: 'Girdle of the Righteous Path', dropType: 'Boss', roles: ['Healer'] },
    ],
  },
  {
    id: 'kaelthas-sunstrider',
    name: "Kael'thas Sunstrider",
    raidId: 'tempest-keep',
    encounterOrder: 4,
    mechanics:
      'A five-phase, 20-plus-minute encounter and the hardest fight of Phase 2. Phase 1 is the four advisors one at a time: Thaladred fixates a random player, Lord Sanguinar fears, Capernian is tanked at range by a warlock, and Telonicus applies a ranged-attack-speed debuff. Phase 2 spawns the seven Sunstrider weapons, which must be destroyed inside two minutes; players loot the Infinity Blade and Cosmic Infuser to use in Phase 3, where all four advisors return at once. Phase 4 is Kael\'thas himself with Phoenixes, Flamestrike, and Mind Control, and Phase 5 at 50% adds Gravity Lapse, which throws the raid into the air and turns the fight into a movement puzzle.',
    roleNotes: [
      { role: 'Tank', note: 'One tank kites the Phoenix in Phase 4; the advisor tanks must be pre-assigned by name for both Phase 1 and Phase 3.' },
      { role: 'Physical DPS', note: 'Loot the Infinity Blade in Phase 2 — its on-hit dispel is what breaks the Phase 4 Mind Controls.' },
      { role: 'Caster DPS', note: 'A warlock tanks Capernian at range; everyone else stays spread through Gravity Lapse.' },
      { role: 'Healer', note: 'Gravity Lapse removes your ability to stand still and cast — plan instant heals and pre-hots for it.' },
    ],
    loot: [
      { wowItemId: 30236, name: 'Chestguard of the Vanquished Champion', dropType: 'Tier Token', notes: 'T5 chest token — Paladin, Priest, Warlock.' },
      { wowItemId: 30237, name: 'Chestguard of the Vanquished Defender', dropType: 'Tier Token', notes: 'T5 chest token — Warrior, Priest, Druid.' },
      { wowItemId: 30238, name: 'Chestguard of the Vanquished Hero', dropType: 'Tier Token', notes: 'T5 chest token — Hunter, Mage, Rogue, Shaman.' },
      { itemId: 'destroyer-breastplate', name: 'Destroyer Breastplate', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Warrior T5 chest, redeemed from Chestguard of the Vanquished Defender.' },
      { itemId: 'destroyer-chestguard-tank', name: 'Destroyer Chestguard', dropType: 'Tier Token', roles: ['Tank'], notes: 'Warrior T5 tanking chest, redeemed from Chestguard of the Vanquished Defender.' },
      { itemId: 'crystalforge-chestpiece', name: 'Crystalforge Chestpiece', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Paladin T5 chest, redeemed from Chestguard of the Vanquished Champion.' },
      { itemId: 'crystalforge-breastplate', name: 'Crystalforge Breastplate', dropType: 'Tier Token', roles: ['Healer'], notes: 'Paladin T5 healing chest, redeemed from Chestguard of the Vanquished Champion.' },
      { itemId: 'vestments-of-the-avatar', name: 'Vestments of the Avatar', dropType: 'Tier Token', roles: ['Healer'], notes: 'Priest T5 chest, redeemed from Chestguard of the Vanquished Champion or Defender.' },
      { itemId: 'nordrassil-chestpiece', name: 'Nordrassil Chestpiece', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Druid T5 chest, redeemed from Chestguard of the Vanquished Defender.' },
      { itemId: 'nordrassil-chestguard', name: 'Nordrassil Chestguard', dropType: 'Tier Token', roles: ['Healer'], notes: 'Druid T5 healing chest, redeemed from Chestguard of the Vanquished Defender.' },
      { itemId: 'rift-stalker-hauberk', name: 'Rift Stalker Hauberk', dropType: 'Tier Token', roles: ['Physical DPS'], notes: 'Hunter T5 chest, redeemed from Chestguard of the Vanquished Hero.' },
      { itemId: 'robes-of-tirisfal', name: 'Robes of Tirisfal', dropType: 'Tier Token', roles: ['Caster DPS'], notes: 'Mage T5 chest, redeemed from Chestguard of the Vanquished Hero.' },
      { itemId: 'cataclysm-chestplate', name: 'Cataclysm Chestplate', wowItemId: 30185, dropType: 'Tier Token', roles: ['Physical DPS', 'Caster DPS', 'Healer'], notes: 'Shaman T5 chest, redeemed from Chestguard of the Vanquished Hero.' },
      {
        itemId: 'voidheart-robe',
        name: 'Voidheart Robe',
        dropType: 'Tier Token',
        roles: ['Caster DPS'],
        needsVerification: true,
        notes: 'Warlock Tier 5 chest redeemed from Chestguard of the Vanquished Champion. The catalog records this as a Serpentshrine Cavern / Lady Vashj drop under the Tier 4 "Voidheart" name; the T5 chest token comes from Kael\'thas, so both the boss and the set name on that entry need auditing.',
      },
      { itemId: 'the-nexus-key', name: 'The Nexus-Key', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'rod-of-the-sun-king', name: 'Rod of the Sun King', wowItemId: 29996, dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'twinblade-of-the-phoenix', name: 'Twinblade of the Phoenix', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'band-of-the-ranger-general', name: 'Band of the Ranger-General', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'gauntlets-of-the-sun-king', name: 'Gauntlets of the Sun King', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'leggings-of-murderous-intent', name: 'Leggings of Murderous Intent', dropType: 'Boss', roles: ['Physical DPS'] },
      { itemId: 'sunhawk-leggings', name: 'Sunhawk Leggings', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'thalassian-wildercloak', name: 'Thalassian Wildercloak', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'royal-cloak-of-the-sunstriders', name: 'Royal Cloak of the Sunstriders', dropType: 'Boss', roles: ['Caster DPS'] },
      { itemId: 'sunshower-light-cloak', name: 'Sunshower Light Cloak', dropType: 'Boss', roles: ['Healer'] },
      {
        itemId: 'warp-slicer',
        name: 'Warp Slicer',
        dropType: 'Boss',
        roles: ['Physical DPS'],
        needsVerification: true,
        notes: "One of the seven Sunstrider weapons; Kael'thas drops one of the set per kill. The item catalog records it as a Void Reaver drop, which needs correcting.",
      },
      {
        wowItemId: 30317,
        itemId: 'cosmic-infuser', name: 'Cosmic Infuser',
        dropType: 'Boss',
        roles: ['Healer'],
        notes: "One of the seven Sunstrider weapons. Kael'thas drops a single weapon from the set per kill.",
      },
      {
        wowItemId: 30316,
        itemId: 'devastation', name: 'Devastation',
        dropType: 'Boss',
        roles: ['Physical DPS'],
        notes: "One of the seven Sunstrider weapons. Kael'thas drops a single weapon from the set per kill.",
      },
      {
        wowItemId: 30312,
        itemId: 'infinity-blade', name: 'Infinity Blade',
        dropType: 'Boss',
        roles: ['Tank'],
        notes: "One of the seven Sunstrider weapons. Kael'thas drops a single weapon from the set per kill.",
      },
      {
        wowItemId: 30318,
        itemId: 'netherstrand-longbow', name: 'Netherstrand Longbow',
        dropType: 'Boss',
        roles: ['Physical DPS'],
        notes: "One of the seven Sunstrider weapons. Kael'thas drops a single weapon from the set per kill.",
      },
      {
        wowItemId: 30314,
        itemId: 'phaseshift-bulwark', name: 'Phaseshift Bulwark',
        dropType: 'Boss',
        roles: ['Tank'],
        notes: "One of the seven Sunstrider weapons. Kael'thas drops a single weapon from the set per kill.",
      },
      {
        wowItemId: 30313,
        itemId: 'staff-of-disintegration', name: 'Staff of Disintegration',
        dropType: 'Boss',
        roles: ['Caster DPS'],
        notes: "One of the seven Sunstrider weapons. Kael'thas drops a single weapon from the set per kill.",
      },
      {
        itemId: 'telonicus-pendant-of-mayhem',
        name: "Telonicus's Pendant of Mayhem",
        wowItemId: 30017,
        dropType: 'Quest Reward',
        roles: ['Physical DPS'],
        needsVerification: true,
        notes: "Chosen from the quest 'Kael'thas and the Verdant Sphere', started by the Verdant Sphere that Kael'thas drops. The item catalog records it as a High Astromancer Solarian drop, which needs correcting.",
      },
      {
        itemId: 'lord-sanguinars-claim',
        name: "Lord Sanguinar's Claim",
        wowItemId: 30018,
        dropType: 'Quest Reward',
        roles: ['Tank'],
        notes: "Alternative choice from 'Kael'thas and the Verdant Sphere'.",
      },
      {
        itemId: 'sun-kings-talisman',
        name: "The Sun King's Talisman",
        dropType: 'Quest Reward',
        roles: ['Caster DPS'],
        notes: "Alternative choice from 'Kael'thas and the Verdant Sphere'.",
      },
      { itemId: 'the-darkeners-grasp', name: "The Darkener's Grasp", dropType: 'Quest Reward' },
      { itemId: 'crown-of-the-sun', name: 'Crown of the Sun', dropType: 'Boss', roles: ['Caster DPS'] },
      { wowItemId: 32458, name: "Ashes of Al'ar", dropType: 'Boss', needsVerification: true, notes: 'Flying mount with a drop rate around 1-2%. Not in the item catalog.' },
    ],
  },
]
