import rawTierLists from './tierLists.json' with { type: 'json' }
import type { TbcClass, TbcSpec } from '../character/characterTypes'
import type { SpecTierList, SpecTierPlacement, TierListRole } from './tierListTypes'

/**
 * Wowhead's Phase 2 spec tier lists, generated by `tools/ingest/ingest-tier-lists.mjs`.
 *
 * Three lists, 28 placements, covering all 27 specs the app knows — every spec appears on at least
 * one list, and Feral Druid appears on two.
 *
 * **These rank specs, not items.** They cannot narrow a per-slot BiS list and are not wired into one;
 * the two datasets answer different questions and the tier list is the weaker of the two for gearing.
 *
 * The tier *letters and membership* are here. Wowhead's analysis prose is not, deliberately — that is
 * their writing rather than data, so each list carries `sourceUrl` and the view links out to it.
 */

const ROLE_ORDER: readonly TierListRole[] = ['DPS', 'Healer', 'Tank']

export const specTierLists = rawTierLists.lists as readonly SpecTierList[]

export function getTierList(role: TierListRole): SpecTierList | undefined {
  return specTierLists.find((list) => list.role === role)
}

/** The roles that actually have a list, in a stable published order. */
export const tierListRoles: readonly TierListRole[] = ROLE_ORDER.filter((role) => specTierLists.some((list) => list.role === role))

/**
 * Every placement for one spec, across all three lists.
 *
 * Returns an array rather than a single tier because a spec genuinely can hold two placements at
 * once — see `TierListRole`. Empty is not currently reachable (all 27 specs are covered, and the
 * ingest asserts it), but a Wowhead reshuffle could make it so, and a caller that assumed otherwise
 * would be the thing that broke.
 */
export function getPlacementsForSpec(className: TbcClass, spec: TbcSpec): readonly SpecTierPlacement[] {
  const found: SpecTierPlacement[] = []
  for (const list of specTierLists) {
    for (const tier of list.tiers) {
      if (tier.placements.some((placement) => placement.className === className && placement.spec === spec)) {
        found.push({ role: list.role, label: tier.label, sourceUrl: list.sourceUrl })
      }
    }
  }
  return found
}
