import rawConsumables from './consumableCatalogue.json' with { type: 'json' }
import type { BuildRole } from '../gear/itemTypes'
import type { Consumable } from './consumableTypes'

/**
 * Raid consumables, generated by `tools/ingest/ingest-consumables.mjs`.
 *
 * Two sources: the stat values come from wowsims (the numbers its sim runs on), and the names and
 * item ids from Wowhead, because wowsims only carries protobuf enum names. That split matters —
 * transforming `AdeptsElixir` into a display name loses the apostrophe, and the lookup is what turns
 * it back into "Adept's Elixir". It also caught `ElixirOfMajorFirePower`, which is really
 * "Elixir of Major Firepower", one word.
 *
 * Roles are derived from the stats each consumable grants rather than assigned per spec. The Wowhead
 * consumables guides do publish per-spec advice, but in prose, and inventing a per-spec opinion from
 * it is exactly the kind of plausible-looking guesswork that made the old item catalogue untrustworthy.
 * A flask granting attack power serves physical damage; that much the data actually says.
 */
export const sampleConsumables: readonly Consumable[] = rawConsumables.consumables as Consumable[]

const byId = new Map(sampleConsumables.map((consumable) => [consumable.id, consumable]))

export function getConsumableById(id: string | undefined) {
  return id ? byId.get(id) : undefined
}

/** Consumables worth showing a role. Anything with no role at all is offered to everyone. */
export function getConsumablesForRole(role: BuildRole): readonly Consumable[] {
  return sampleConsumables.filter((consumable) => !consumable.roles?.length || consumable.roles.includes(role))
}
