import type { Consumable } from './consumableTypes'

export const sampleConsumables: readonly Consumable[] = [
  {
    id: 'flask-of-relentless-assault',
    name: 'Flask of Relentless Assault',
    category: 'Flask',
    roles: ['Physical DPS'],
    stats: { attackPower: 120 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 325,
      recipeSource: 'Alchemy trainer (Outland).',
      materials: [
        { name: 'Netherbloom', quantity: 4, farmSource: 'Herbalism gathering node in Netherstorm/Shadowmoon Valley.', needsVerification: true },
        { name: 'Felweed', quantity: 4, farmSource: 'Herbalism gathering node throughout Outland.', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Persists through death; occupies both elixir slots. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'flask-of-pure-death',
    name: 'Flask of Pure Death',
    category: 'Flask',
    roles: ['Caster DPS'],
    stats: { spellPower: 80 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 350,
      specialization: 'Requires exalted Sha’tari Skyguard reputation to purchase the recipe.',
      recipeSource: "Sha'tari Skyguard quartermaster (Blade's Edge Mountains), exalted reputation required.",
      materials: [
        { name: 'Netherbloom', quantity: 4, farmSource: 'Herbalism gathering node in Netherstorm/Shadowmoon Valley.', needsVerification: true },
        { name: 'Felweed', quantity: 4, farmSource: 'Herbalism gathering node throughout Outland.', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Persists through death; occupies both elixir slots. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'flask-of-mighty-restoration',
    name: 'Flask of Mighty Restoration',
    category: 'Flask',
    roles: ['Healer'],
    stats: { mp5: 25 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 350,
      recipeSource: 'Alchemy trainer (Outland, higher-tier recipe).',
      materials: [
        { name: 'Netherbloom', quantity: 4, farmSource: 'Herbalism gathering node in Netherstorm/Shadowmoon Valley.', needsVerification: true },
        { name: 'Mana Thistle', quantity: 2, farmSource: 'Herbalism gathering node in Netherstorm/Shadowmoon Valley (rare spawn).', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Persists through death; occupies both elixir slots. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'flask-of-fortification',
    name: 'Flask of Fortification',
    category: 'Flask',
    roles: ['Tank'],
    stats: { stamina: 60, defenseRating: 27 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 325,
      recipeSource: 'Alchemy trainer (Outland).',
      materials: [
        { name: 'Felweed', quantity: 4, farmSource: 'Herbalism gathering node throughout Outland.', needsVerification: true },
        { name: 'Dreaming Glory', quantity: 4, farmSource: 'Herbalism gathering node in Zangarmarsh/Terokkar Forest.', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Persists through death; occupies both elixir slots. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'elixir-of-major-strength',
    name: 'Elixir of Major Strength',
    category: 'Battle Elixir',
    roles: ['Physical DPS'],
    stats: { strength: 35 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 300,
      recipeSource: 'Alchemy trainer (Outland).',
      materials: [
        { name: 'Felweed', quantity: 2, farmSource: 'Herbalism gathering node throughout Outland.', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Battle elixir slot; mutually exclusive with a Flask. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'elixir-of-major-agility',
    name: 'Elixir of Major Agility',
    category: 'Battle Elixir',
    roles: ['Physical DPS'],
    stats: { agility: 35 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 320,
      recipeSource: 'Alchemy trainer (Outland).',
      materials: [
        { name: 'Fel Lotus', quantity: 1, farmSource: 'Rare Herbalism gathering node throughout Outland.', needsVerification: true },
        { name: 'Felweed', quantity: 2, farmSource: 'Herbalism gathering node throughout Outland.', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Battle elixir slot; mutually exclusive with a Flask. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'elixir-of-major-firepower',
    name: 'Elixir of Major Firepower',
    category: 'Battle Elixir',
    roles: ['Caster DPS'],
    stats: { spellPower: 55 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 340,
      recipeSource: 'Alchemy trainer (Outland).',
      materials: [
        { name: 'Netherbloom', quantity: 2, farmSource: 'Herbalism gathering node in Netherstorm/Shadowmoon Valley.', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Spell-school-specific in real TBC (Fire); modeled here as generic spell power. Battle elixir slot; mutually exclusive with a Flask.',
  },
  {
    id: 'elixir-of-draenic-wisdom',
    name: 'Elixir of Draenic Wisdom',
    category: 'Battle Elixir',
    roles: ['Healer'],
    stats: { intellect: 30, spirit: 30 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 325,
      recipeSource: 'Alchemy trainer (Outland).',
      materials: [
        { name: 'Felweed', quantity: 2, farmSource: 'Herbalism gathering node throughout Outland.', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Battle elixir slot; mutually exclusive with a Flask. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'elixir-of-major-fortitude',
    name: 'Elixir of Major Fortitude',
    category: 'Guardian Elixir',
    roles: ['Tank'],
    stats: { stamina: 43 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 300,
      recipeSource: 'Alchemy trainer (Outland).',
      materials: [
        { name: 'Golden Sansam', quantity: 1, farmSource: 'Herbalism gathering node, Eastern Kingdoms/Kalimdor (pre-Outland herb).', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Guardian elixir slot; mutually exclusive with a Flask. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'elixir-of-major-defense',
    name: 'Elixir of Major Defense',
    category: 'Guardian Elixir',
    roles: ['Tank'],
    stats: { defenseRating: 44 },
    source: 'Crafted',
    craftedBy: 'Alchemy',
    crafting: {
      requiredSkill: 300,
      recipeSource: 'Alchemy trainer (Outland).',
      materials: [
        { name: 'Dreaming Glory', quantity: 2, farmSource: 'Herbalism gathering node in Zangarmarsh/Terokkar Forest.', needsVerification: true },
        { name: 'Crystal Vial', quantity: 1, farmSource: 'Vendor-purchased or looted from various Outland containers.', needsVerification: true },
      ],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Guardian elixir slot; mutually exclusive with a Flask. Stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'grilled-mudfish',
    name: 'Grilled Mudfish',
    category: 'Food',
    roles: ['Physical DPS'],
    stats: { hasteRating: 20 },
    source: 'Crafted',
    craftedBy: 'Cooking',
    crafting: {
      requiredSkill: 260,
      recipeSource: 'Cooking trainer (Outland) or Cooking dailies vendor (Zangarmarsh).',
      materials: [{ name: 'Mudfish', quantity: 1, farmSource: 'Fished from Zangarmarsh pools.', needsVerification: true }],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Well-fed buff; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'spicy-hot-talbuk',
    name: 'Spicy Hot Talbuk',
    category: 'Food',
    roles: ['Physical DPS'],
    stats: { hitRating: 20 },
    source: 'Crafted',
    craftedBy: 'Cooking',
    crafting: {
      requiredSkill: 300,
      recipeSource: 'Cooking trainer (Outland) or Cenarion Expedition quartermaster.',
      materials: [{ name: 'Claw Meat', quantity: 1, farmSource: 'Skinned from talbuk throughout Nagrand.', needsVerification: true }],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Well-fed buff; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'blackened-basilisk',
    name: 'Blackened Basilisk',
    category: 'Food',
    roles: ['Caster DPS'],
    stats: { spellCritRating: 20 },
    source: 'Crafted',
    craftedBy: 'Cooking',
    crafting: {
      requiredSkill: 300,
      recipeSource: 'Cooking trainer (Outland).',
      materials: [{ name: 'Basilisk Meat', quantity: 1, farmSource: 'Skinned from basilisks throughout Terokkar Forest/Nagrand.', needsVerification: true }],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Well-fed buff; stats are approximate pending final Wowhead audit.',
  },
  {
    id: 'golden-fish-sticks',
    name: 'Golden Fish Sticks',
    category: 'Food',
    roles: ['Healer'],
    stats: { mp5: 14, spirit: 14 },
    source: 'Crafted',
    craftedBy: 'Cooking',
    crafting: {
      requiredSkill: 300,
      recipeSource: 'Cooking trainer (Outland) or fishing dailies vendor (Zangarmarsh).',
      materials: [{ name: 'Golden Darter', quantity: 1, farmSource: 'Fished from Zangarmarsh/Terokkar Forest pools.', needsVerification: true }],
      needsVerification: true,
    },
    needsVerification: true,
    notes: 'Well-fed buff; stats are approximate pending final Wowhead audit.',
  },
]

export function getConsumableById(id: string) {
  return sampleConsumables.find((consumable) => consumable.id === id)
}
