import rawIcons from './icons.json' with { type: 'json' }

/**
 * Wowhead icon *names* for every catalogued item and gem, generated by `tools/ingest/ingest-icons.mjs`.
 *
 * 4,740 entries map to 1,238 distinct icons — items share artwork heavily, which is why vendoring the
 * art is 2.1 MB rather than the tens of megabytes a per-item estimate suggests.
 *
 * This module deliberately knows nothing about where the artwork lives or how a URL is built. The
 * name is the durable fact and comes from MIT-licensed upstream data pinned to the same commit as the
 * item catalogue; resolving it to a path is a UI concern, and doing it here would drag Vite's
 * `import.meta.env` into the domain layer for no gain. See `ItemIcon` for the rendering side.
 */

// Cast at the boundary, as the other generated-JSON modules do: TypeScript infers 4,740 literal keys
// from the file otherwise, which is both useless to callers and slow to check.
const iconsByItemId = rawIcons.icons as Record<string, string>


/** Undefined for anything with no `wowItemId` — a few curated entries have no real item behind them. */
export function getIconName(wowItemId: number | undefined): string | undefined {
  if (wowItemId === undefined) return undefined
  return iconsByItemId[String(wowItemId)]
}

/** Both counts are computed at generation time and asserted by the test suite. */
export const mappedIconCount = rawIcons.mappedCount
export const distinctIconCount = rawIcons.distinctIconCount
