// Ingests the wowsims/tbc item database into this repo's GearItem shape.
//
// Why this exists: the previous catalogue was generated by *inferring* what an item should look like
// for its role and slot. All 48 items ever audited against a real tooltip were wrong — invented stats,
// sockets wrong in both directions, placeholder item levels. Plausibility is not evidence. This script
// replaces inference with a real, structured source.
//
// Source: https://github.com/wowsims/tbc (MIT), sim/core/items/all_items.go — itself generated from
// Wowhead/Blizzard API data by that repo's item generator. Pinned to a commit so a re-run is
// reproducible rather than "whatever master says today".
//
// Run: node tools/ingest/ingest-items.mjs [--offline]
// Writes: src/domain/gear/itemCatalogue.json

import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(HERE, '../..')

/** Pinned so ingestion is reproducible. Bump deliberately, then re-run the Wowhead spot-check. */
const UPSTREAM_SHA = '3301fca59306a747e521274c36e073e69acc7b77'
const UPSTREAM_URL = `https://raw.githubusercontent.com/wowsims/tbc/${UPSTREAM_SHA}/sim/core/items/all_items.go`

const CACHE_PATH = resolve(HERE, `.cache/all_items.${UPSTREAM_SHA.slice(0, 8)}.go`)
const OUT_PATH = resolve(REPO, 'src/domain/gear/itemCatalogue.json')

// ---------------------------------------------------------------------------
// Mapping tables. Every one of these was read off the actual data in all_items.go
// (`grep -oE 'proto\.ItemType_ItemType[A-Za-z]+' | sort -u`), not recalled.
// ---------------------------------------------------------------------------

/** wowsims ItemType -> this repo's GearSlot. Finger/Trinket/Weapon need extra context; see slotFor(). */
const SLOT_BY_TYPE = {
  Head: 'Head',
  Neck: 'Neck',
  Shoulder: 'Shoulders',
  Back: 'Back',
  Chest: 'Chest',
  Wrist: 'Wrists',
  Hands: 'Hands',
  Waist: 'Waist',
  Legs: 'Legs',
  Feet: 'Feet',
  Finger: 'Finger 1',
  Trinket: 'Trinket 1',
  Ranged: 'Ranged',
  Weapon: 'Main Hand',
}

/** Ranged-slot items that are really relics. In TBC these occupy the relic slot, not the ranged slot. */
const RELIC_TYPES = new Set(['Idol', 'Libram', 'Totem'])

/**
 * Relic type determines class outright — only shamans use totems, druids idols, paladins librams.
 * The upstream data only class-locks 36 of 80 relics, which would otherwise let a druid equip a totem.
 * Derived rather than looked up because the rule is exact, in the spirit of the armor derivation.
 */
const RELIC_CLASS = { Totem: 'Shaman', Idol: 'Druid', Libram: 'Paladin' }

const WEAPON_TYPE_BY_NAME = {
  Axe: 'Axe',
  Dagger: 'Dagger',
  Fist: 'Fist Weapon',
  Mace: 'Mace',
  Sword: 'Sword',
  Staff: 'Staff',
  Polearm: 'Polearm',
  Shield: 'Shield',
  OffHand: 'Held In Off-hand',
}

const RANGED_TYPE_BY_NAME = {
  Bow: 'Bow',
  Crossbow: 'Crossbow',
  Gun: 'Gun',
  Thrown: 'Thrown',
  Wand: 'Wand',
  Totem: 'Totem',
  Libram: 'Libram',
  Idol: 'Idol',
}

/** wowsims stat key -> StatBlock key. Keys absent here are preserved in `extraStats`, never dropped. */
const STAT_MAP = {
  Strength: 'strength',
  Agility: 'agility',
  Stamina: 'stamina',
  Intellect: 'intellect',
  Spirit: 'spirit',
  AttackPower: 'attackPower',
  RangedAttackPower: 'rangedAttackPower',
  FeralAttackPower: 'feralAttackPower',
  SpellPower: 'spellPower',
  HealingPower: 'healingPower',
  MeleeHit: 'hitRating',
  SpellHit: 'spellHitRating',
  MeleeCrit: 'critRating',
  SpellCrit: 'spellCritRating',
  MeleeHaste: 'hasteRating',
  SpellHaste: 'spellHasteRating',
  Expertise: 'expertiseRating',
  ArmorPenetration: 'armorPenetration',
  Defense: 'defenseRating',
  Dodge: 'dodgeRating',
  Parry: 'parryRating',
  Block: 'blockRating',
  BlockValue: 'blockValue',
  Resilience: 'resilienceRating',
  Armor: 'armor',
  MP5: 'mp5',
}

const CLASS_MAP = {
  Warrior: 'Warrior',
  Paladin: 'Paladin',
  Hunter: 'Hunter',
  Rogue: 'Rogue',
  Priest: 'Priest',
  Shaman: 'Shaman',
  Mage: 'Mage',
  Warlock: 'Warlock',
  Druid: 'Druid',
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

/**
 * Blizzard's own test and NPC-only entries. They are real rows in the item database — and Wowhead
 * serves them — but they are not obtainable, and "Tom's Legs 3" at item level 145 outranked every
 * real Tier 5 legging and became the default gear for every class.
 */
const EXCLUDED_NAME = /^Tom's Legs |^Monster - |^OLD |^zz|\[PH\]|^Deprecated|^NPC /i

const rx = {
  name: /(?:^|\{)Name: "((?:[^"\\]|\\.)*)"/,
  id: /[,{]\s*ID: (\d+)/,
  type: /[,{]\s*Type: proto\.ItemType_ItemType(\w+)/,
  armorType: /[,{]\s*ArmorType: proto\.ArmorType_ArmorType(\w+)/,
  weaponType: /[,{]\s*WeaponType: proto\.WeaponType_WeaponType(\w+)/,
  handType: /[,{]\s*HandType: proto\.HandType_HandType(\w+)/,
  rangedType: /[,{]\s*RangedWeaponType: proto\.RangedWeaponType_RangedWeaponType(\w+)/,
  phase: /[,{]\s*Phase: (\d+)/,
  quality: /[,{]\s*Quality: proto\.ItemQuality_ItemQuality(\w+)/,
  ilvl: /[,{]\s*Ilvl: (\d+)/,
  unique: /[,{]\s*Unique: true/,
  wdMin: /[,{]\s*WeaponDamageMin: ([\d.]+)/,
  wdMax: /[,{]\s*WeaponDamageMax: ([\d.]+)/,
  swing: /[,{]\s*SwingSpeed: ([\d.]+)/,
  stats: /[,{]\s*Stats: stats\.Stats\{([^}]*)\}/,
  socketBonus: /[,{]\s*SocketBonus: stats\.Stats\{([^}]*)\}/,
  gemSockets: /[,{]\s*GemSockets: \[\]proto\.GemColor\{([^}]*)\}/,
  setName: /[,{]\s*SetName: "((?:[^"\\]|\\.)*)"/,
  classAllowlist: /[,{]\s*ClassAllowlist: \[\]proto\.Class\{([^}]*)\}/,
}

function match(line, re, transform = (v) => v) {
  const m = line.match(re)
  return m ? transform(m[1]) : undefined
}

/** Splits a `stats.Stats{...}` body into mapped StatBlock entries and unmapped leftovers. */
function parseStats(body, unmappedTally) {
  const stats = {}
  const extra = {}
  if (!body) return { stats, extra }

  for (const m of body.matchAll(/stats\.(\w+):\s*(-?[\d.]+)/g)) {
    const [, key, raw] = m
    const value = Number(raw)
    if (value === 0) continue
    const mapped = STAT_MAP[key]
    if (mapped) {
      stats[mapped] = (stats[mapped] ?? 0) + value
    } else {
      extra[key] = value
      unmappedTally.set(key, (unmappedTally.get(key) ?? 0) + 1)
    }
  }
  return { stats, extra }
}

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

/** Decides the GearSlot, which needs weapon hand/ranged context that ItemType alone does not carry. */
function slotFor({ type, handType, weaponType, rangedType }) {
  if (type === 'Ranged' && rangedType && RELIC_TYPES.has(rangedType)) return 'Relic'
  if (type === 'Weapon') {
    // OffHand covers both shields and held-in-off-hand items; everything else sits in the main hand.
    // One-handers are surfaced in the off hand by slot-compatibility rules, not by duplicating them here.
    if (handType === 'OffHand' || weaponType === 'Shield' || weaponType === 'OffHand') return 'Off Hand'
    return 'Main Hand'
  }
  return SLOT_BY_TYPE[type]
}

function parseLine(line, unmappedTally) {
  const name = match(line, rx.name)
  const id = match(line, rx.id, Number)
  if (!name || !id) return undefined
  if (EXCLUDED_NAME.test(name)) return { skipped: { name, id, reason: 'test/NPC-only item' } }

  const type = match(line, rx.type)
  const handType = match(line, rx.handType)
  const weaponType = match(line, rx.weaponType)
  const rangedType = match(line, rx.rangedType)
  const slot = slotFor({ type, handType, weaponType, rangedType })
  if (!slot) return { skipped: { name, id, reason: `unmapped ItemType "${type}"` } }

  const { stats, extra } = parseStats(match(line, rx.stats), unmappedTally)
  const { stats: socketBonus } = parseStats(match(line, rx.socketBonus), unmappedTally)

  const sockets = match(line, rx.gemSockets, (body) =>
    [...body.matchAll(/GemColor_GemColor(\w+)/g)].map((m) => m[1]),
  )

  const declaredClasses = match(line, rx.classAllowlist, (body) =>
    [...body.matchAll(/Class_Class(\w+)/g)].map((m) => CLASS_MAP[m[1]]).filter(Boolean),
  )
  const relicClass = rangedType && RELIC_TYPES.has(rangedType) ? RELIC_CLASS[rangedType] : undefined
  const allowedClasses = declaredClasses?.length ? declaredClasses : relicClass ? [relicClass] : undefined

  const resolvedWeaponType = WEAPON_TYPE_BY_NAME[weaponType] ?? RANGED_TYPE_BY_NAME[rangedType]
  const setName = match(line, rx.setName)

  const item = {
    id: slugify(name),
    wowItemId: id,
    name,
    slot,
    quality: match(line, rx.quality),
    itemLevel: match(line, rx.ilvl, Number),
    phase: match(line, rx.phase, Number),
    stats,
  }

  if (match(line, rx.armorType)) item.armorType = match(line, rx.armorType)
  else if (weaponType === 'Shield') item.armorType = 'Shield'
  else if (rangedType && RELIC_TYPES.has(rangedType)) item.armorType = 'Relic'

  if (resolvedWeaponType) item.weaponType = resolvedWeaponType
  if (handType) item.handType = handType === 'OneHand' ? 'One Hand' : handType === 'TwoHand' ? 'Two Hand' : handType === 'MainHand' ? 'Main Hand' : 'Off Hand'

  const swing = match(line, rx.swing, Number)
  const wdMin = match(line, rx.wdMin, Number)
  const wdMax = match(line, rx.wdMax, Number)
  if (swing) item.weaponSpeed = swing
  if (wdMin) item.weaponDamageMin = wdMin
  if (wdMax) item.weaponDamageMax = wdMax

  if (sockets?.length) item.sockets = sockets
  if (Object.keys(socketBonus).length) item.socketBonus = socketBonus
  if (setName) item.setId = slugify(setName)
  if (allowedClasses?.length) item.allowedClasses = allowedClasses
  if (rx.unique.test(line)) item.unique = true
  // Resistances and school-specific spell power have no StatBlock field yet. Kept rather than dropped
  // so adding those fields later is a display change, not a re-ingestion.
  if (Object.keys(extra).length) item.extraStats = extra

  return { item, setName }
}

// ---------------------------------------------------------------------------
// Fetch + run
// ---------------------------------------------------------------------------

async function loadSource() {
  if (existsSync(CACHE_PATH)) return readFileSync(CACHE_PATH, 'utf8')
  if (process.argv.includes('--offline')) {
    throw new Error(`--offline given but no cache at ${CACHE_PATH}`)
  }
  process.stderr.write(`fetching ${UPSTREAM_URL}\n`)
  const res = await fetch(UPSTREAM_URL)
  if (!res.ok) throw new Error(`upstream fetch failed: ${res.status} ${res.statusText}`)
  const text = await res.text()
  mkdirSync(dirname(CACHE_PATH), { recursive: true })
  writeFileSync(CACHE_PATH, text)
  return text
}

const source = await loadSource()
const unmappedTally = new Map()
const items = []
const skipped = []
const setNames = new Map()

for (const line of source.split('\n')) {
  const trimmed = line.trim()
  if (!trimmed.startsWith('{Name:')) continue
  const parsed = parseLine(trimmed, unmappedTally)
  if (!parsed) continue
  if (parsed.skipped) {
    skipped.push(parsed.skipped)
    continue
  }
  items.push(parsed.item)
  if (parsed.setName) setNames.set(slugify(parsed.setName), parsed.setName)
}

// Ids must be unique — the catalogue is keyed by them. Duplicate names are real (recoloured drops,
// faction mirrors), so collisions get the wow item id appended rather than one entry silently winning.
const byId = new Map()
for (const item of items) {
  const seen = byId.get(item.id)
  if (seen) item.id = `${item.id}-${item.wowItemId}`
  byId.set(item.id, item)
}

// Deterministic order keeps the diff empty on a no-op re-run. This repo lives in OneDrive; churn matters.
items.sort((a, b) => a.wowItemId - b.wowItemId)

const payload = {
  $schema: 'wowsims-tbc item ingestion',
  upstream: { repo: 'wowsims/tbc', sha: UPSTREAM_SHA, path: 'sim/core/items/all_items.go', license: 'MIT' },
  generatedBy: 'tools/ingest/ingest-items.mjs',
  itemCount: items.length,
  sets: Object.fromEntries([...setNames.entries()].sort(([a], [b]) => a.localeCompare(b))),
  items,
}

const json = `${JSON.stringify(payload, null, 2)}\n`
const previous = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, 'utf8') : ''
const changed = previous !== json
if (changed) writeFileSync(OUT_PATH, json)

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

const bySlot = {}
for (const item of items) bySlot[item.slot] = (bySlot[item.slot] ?? 0) + 1
const socketed = items.filter((i) => i.sockets?.length).length
const withSet = items.filter((i) => i.setId).length
const classLocked = items.filter((i) => i.allowedClasses?.length).length

process.stdout.write(
  [
    `ingested   ${items.length} items from wowsims/tbc@${UPSTREAM_SHA.slice(0, 8)}`,
    `output     ${changed ? 'written' : 'unchanged (idempotent)'} -> src/domain/gear/itemCatalogue.json`,
    `sha256     ${createHash('sha256').update(json).digest('hex').slice(0, 16)}`,
    `sets       ${setNames.size} named sets, ${withSet} items in a set`,
    `sockets    ${socketed} items carry sockets`,
    `class-lock ${classLocked} items restricted to specific classes`,
    `skipped    ${skipped.length}${skipped.length ? ` (${[...new Set(skipped.map((s) => s.reason))].join('; ')})` : ''}`,
    '',
    'by slot:',
    ...Object.entries(bySlot)
      .sort(([, a], [, b]) => b - a)
      .map(([slot, n]) => `  ${slot.padEnd(12)} ${n}`),
    '',
    unmappedTally.size
      ? `stats with no StatBlock field (preserved in extraStats, not surfaced):\n${[...unmappedTally.entries()]
          .sort(([, a], [, b]) => b - a)
          .map(([k, n]) => `  ${k.padEnd(20)} ${n}`)
          .join('\n')}`
      : 'every stat mapped to a StatBlock field',
    '',
  ].join('\n'),
)
